# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.


"""
(No short description)

Attributes:
    HIPFFT_FORWARD (:py:obj:`~.int`):
        Macro constant.

    HIPFFT_BACKWARD (:py:obj:`~.int`):
        Macro constant.

    hipfftResult:
        alias of :py:obj:`~.hipfftResult_t`

    hipfftType:
        alias of :py:obj:`~.hipfftType_t`

    hipfftLibraryPropertyType:
        alias of :py:obj:`~.hipfftLibraryPropertyType_t`

    hipfftHandle:
        alias of :py:obj:`~.hipfftHandle_t`

    hipfftComplex:
        alias of :py:obj:`~.float2`

    hipfftDoubleComplex:
        alias of :py:obj:`~.double2`

"""

import cython
import ctypes
import enum
# cimport (not import) is required so the with-nogil emitter can use
# the util types in `cdef` declarations — `cdef <T> name = ...` only
# works when T is visible to Cython at compile time, which means the
# defining module must be cimported. The plain Python `import` form
# would only make the names available to runtime attribute access.
cimport rocm.bindings.util.types
def has_symbol(name) -> bool:
    r"""Probe whether the runtime-linked DLL exports a symbol.

    Non-raising. Lazily opens the DLL on first call (same
    resolution path as the per-symbol lazy loaders), then
    asks the loader whether the named symbol is present.
    Returns ``False`` if the DLL fails to open or the symbol
    isn't there.

    Args:
        name: Symbol name to probe (``str`` or ``bytes``).

    Returns:
        True if the symbol resolves, False otherwise.
    """
    cdef bytes name_bytes
    if isinstance(name, str):
        name_bytes = name.encode("utf-8")
    elif isinstance(name, (bytes, bytearray)):
        name_bytes = bytes(name)
    else:
        raise TypeError("name must be str, bytes, or bytearray")
    return cyhipfft.__hipfft_has_symbol(<const char*>name_bytes)


HIPFFT_FORWARD = cyhipfft.HIPFFT_FORWARD

HIPFFT_BACKWARD = cyhipfft.HIPFFT_BACKWARD

class _hipfftResult_t__Base(enum.IntEnum):
    """Empty enum base class that allows subclassing.
    """
    pass
class hipfftResult_t(_hipfftResult_t__Base):
    """Result/status/error codes

    Attributes:
        HIPFFT_SUCCESS:
            hipFFT operation was successful
        HIPFFT_INVALID_PLAN:
            hipFFT was passed an invalid plan handle
        HIPFFT_ALLOC_FAILED:
            hipFFT failed to allocate GPU or CPU memory
        HIPFFT_INVALID_TYPE:
            No longer used
        HIPFFT_INVALID_VALUE:
            User specified an invalid pointer or parameter
        HIPFFT_INTERNAL_ERROR:
            Driver or internal hipFFT library error
        HIPFFT_EXEC_FAILED:
            Failed to execute an FFT on the GPU
        HIPFFT_SETUP_FAILED:
            hipFFT failed to initialize
        HIPFFT_INVALID_SIZE:
            User specified an invalid transform size
        HIPFFT_UNALIGNED_DATA:
            No longer used
        HIPFFT_INCOMPLETE_PARAMETER_LIST:
            Missing parameters in call
        HIPFFT_INVALID_DEVICE:
            Execution of a plan was on different GPU than plan creation
        HIPFFT_PARSE_ERROR:
            Internal plan database error
        HIPFFT_NO_WORKSPACE:
            No workspace has been provided prior to plan execution
        HIPFFT_NOT_IMPLEMENTED:
            Function does not implement functionality for parameters given.
        HIPFFT_NOT_SUPPORTED:
            Operation is not supported for parameters given.
    """
    HIPFFT_SUCCESS = cyhipfft.HIPFFT_SUCCESS
    HIPFFT_INVALID_PLAN = cyhipfft.HIPFFT_INVALID_PLAN
    HIPFFT_ALLOC_FAILED = cyhipfft.HIPFFT_ALLOC_FAILED
    HIPFFT_INVALID_TYPE = cyhipfft.HIPFFT_INVALID_TYPE
    HIPFFT_INVALID_VALUE = cyhipfft.HIPFFT_INVALID_VALUE
    HIPFFT_INTERNAL_ERROR = cyhipfft.HIPFFT_INTERNAL_ERROR
    HIPFFT_EXEC_FAILED = cyhipfft.HIPFFT_EXEC_FAILED
    HIPFFT_SETUP_FAILED = cyhipfft.HIPFFT_SETUP_FAILED
    HIPFFT_INVALID_SIZE = cyhipfft.HIPFFT_INVALID_SIZE
    HIPFFT_UNALIGNED_DATA = cyhipfft.HIPFFT_UNALIGNED_DATA
    HIPFFT_INCOMPLETE_PARAMETER_LIST = cyhipfft.HIPFFT_INCOMPLETE_PARAMETER_LIST
    HIPFFT_INVALID_DEVICE = cyhipfft.HIPFFT_INVALID_DEVICE
    HIPFFT_PARSE_ERROR = cyhipfft.HIPFFT_PARSE_ERROR
    HIPFFT_NO_WORKSPACE = cyhipfft.HIPFFT_NO_WORKSPACE
    HIPFFT_NOT_IMPLEMENTED = cyhipfft.HIPFFT_NOT_IMPLEMENTED
    HIPFFT_NOT_SUPPORTED = cyhipfft.HIPFFT_NOT_SUPPORTED
    @staticmethod
    def ctypes_type():
        """The type of the enum constants as ctypes type."""
        return ctypes.c_uint


hipfftResult = hipfftResult_t

class _hipfftType_t__Base(enum.IntEnum):
    """Empty enum base class that allows subclassing.
    """
    pass
class hipfftType_t(_hipfftType_t__Base):
    """Transform type

    Attributes:
        HIPFFT_R2C:
            Real to complex (interleaved)
        HIPFFT_C2R:
            Complex (interleaved) to real
        HIPFFT_C2C:
            Complex to complex (interleaved)
        HIPFFT_D2Z:
            Double to double-complex (interleaved)
        HIPFFT_Z2D:
            Double-complex (interleaved) to double
        HIPFFT_Z2Z:
            Double-complex to double-complex (interleaved)
    """
    HIPFFT_R2C = cyhipfft.HIPFFT_R2C
    HIPFFT_C2R = cyhipfft.HIPFFT_C2R
    HIPFFT_C2C = cyhipfft.HIPFFT_C2C
    HIPFFT_D2Z = cyhipfft.HIPFFT_D2Z
    HIPFFT_Z2D = cyhipfft.HIPFFT_Z2D
    HIPFFT_Z2Z = cyhipfft.HIPFFT_Z2Z
    @staticmethod
    def ctypes_type():
        """The type of the enum constants as ctypes type."""
        return ctypes.c_uint


hipfftType = hipfftType_t

class _hipfftLibraryPropertyType_t__Base(enum.IntEnum):
    """Empty enum base class that allows subclassing.
    """
    pass
class hipfftLibraryPropertyType_t(_hipfftLibraryPropertyType_t__Base):
    """hipfftLibraryPropertyType_t

    Attributes:
        HIPFFT_MAJOR_VERSION:
            (undocumented)
        HIPFFT_MINOR_VERSION:
            (undocumented)
        HIPFFT_PATCH_LEVEL:
            (undocumented)
    """
    HIPFFT_MAJOR_VERSION = cyhipfft.HIPFFT_MAJOR_VERSION
    HIPFFT_MINOR_VERSION = cyhipfft.HIPFFT_MINOR_VERSION
    HIPFFT_PATCH_LEVEL = cyhipfft.HIPFFT_PATCH_LEVEL
    @staticmethod
    def ctypes_type():
        """The type of the enum constants as ctypes type."""
        return ctypes.c_uint


hipfftLibraryPropertyType = hipfftLibraryPropertyType_t

cdef class hipfftHandle_t(rocm.bindings.util.types.Pointer):
    """Python wrapper for cdef class cyhipfft.hipfftHandle_t.

    Python wrapper for cdef class cyhipfft.hipfftHandle_t.

    If this type is initialized via its `__init__` method, it allocates a
    member of the underlying C type and destroys it again if the wrapper
    type is deallocated.

    This type also serves as adapter when appearing as argument type in a
    function signature. In this case, the type can further be initialized
    from a number of Python objects:

    * `None`:

      This will set the ``self._ptr`` attribute to ``NULL``.

    * `int`:

      Interprets the integer value as pointer address and writes it to ``self._ptr``.
      No ownership is transferred.

    * `ctypes.c_void_p`:

      Takes the pointer address ``pyobj.value`` and writes it to ``self._ptr``.
      No ownership is transferred.

    * `object` that implements the `CUDA Array Interface <https://numba.readthedocs.io/en/stable/cuda/cuda_array_interface.html>`_ protocol:

      Takes the integer-valued pointer address, i.e. the first entry of the `data` tuple
      from `pyobj`'s member ``__cuda_array_interface__``  and writes it to ``self._ptr``.

    * `object` that implements the Python buffer protocol:

      If the object represents a simple contiguous array,
      writes the `Py_buffer` associated with ``pyobj`` to `self._py_buffer`,
      sets the `self._py_buffer_acquired` flag to `True`, and
      writes `self._py_buffer.buf` to the data pointer `self._ptr`.

    * `rocm.bindings.util.types.Pointer`:

      Takes the pointer address ``pyobj._ptr`` and writes it to ``self._ptr``.
      No ownership is transferred.

    Type checks are performed in the above order.

    C Attributes:
        _ptr (C type ``void *``, protected):
            Stores a pointer to the data of the original Python object.
        _is_ptr_owner (C type ``bint``, protected):
            If this wrapper is the owner of the underlying data.
        _py_buffer (C type ``Py_buffer`, protected):
            Stores a pointer to the data of the original Python object.
        _py_buffer_acquired (C type ``bint``, protected):
            Stores a pointer to the data of the original Python object.
    """
    # C members declared in pxd file

    def __cinit__(self):
        self._ptr = NULL
        self._is_ptr_owner = False
        self._py_buffer_acquired = False

    cdef cyhipfft.hipfftHandle_t* getElementPtr(self):
        return <cyhipfft.hipfftHandle_t*>self._ptr

    @staticmethod
    cdef hipfftHandle_t fromPtr(void* ptr, bint owner=False):
        """Factory function to create ``hipfftHandle_t`` objects from
        given ``cyhipfft.hipfftHandle_t`` pointer.
        """
        # Fast call to __new__() that bypasses the __init__() constructor.
        cdef hipfftHandle_t wrapper = hipfftHandle_t.__new__(hipfftHandle_t)
        wrapper._ptr = ptr
        wrapper._is_ptr_owner = owner
        return wrapper

    @staticmethod
    def fromObj(pyobj):
        """Creates a hipfftHandle_t from a Python object.

        Derives a hipfftHandle_t from the given Python object ``pyobj``.
        In case ``pyobj`` is itself an ``hipfftHandle_t`` reference, this method
        returns it directly. No new ``hipfftHandle_t`` is created in this case.
        """
        return hipfftHandle_t.fromPyobj(pyobj)

    @staticmethod
    cdef hipfftHandle_t fromPyobj(object pyobj):
        """Creates a hipfftHandle_t from a Python object.

        Derives a hipfftHandle_t from the given Python object ``pyobj``.
        In case ``pyobj`` is itself an ``hipfftHandle_t`` reference, this method
        returns it directly. No new ``hipfftHandle_t`` is created in this case.

        Args:
            pyobj (object): Must be either `None`; a `rocm.bindings.util.types.Pointer`; a simple, contiguous buffer according to the buffer protocol;
                            or of type `hipfftHandle_t`; `int`; or `ctypes.c_void_p`.

        Note:
            This routine does not perform a copy but returns the original ``pyobj``
            if ``pyobj`` is an instance of hipfftHandle_t!
        """
        cdef hipfftHandle_t wrapper

        if isinstance(pyobj,hipfftHandle_t):
            return pyobj
        else:
            wrapper = hipfftHandle_t.__new__(hipfftHandle_t)
            wrapper.init_from_pyobj(pyobj)
            return wrapper

    def __dealloc__(self):
        # Release the buffer handle
        if self._py_buffer_acquired is True:
            cpython.buffer.PyBuffer_Release(&self._py_buffer)

    def __int__(self):
        """Returns the data's address as long integer.
        """
        return cpython.long.PyLong_FromVoidPtr(self._ptr)

    def __repr__(self):
        return f"<hipfftHandle_t object, ptr: {int(self)}>"

    def as_c_void_p(self):
        """Returns the data's address as `ctypes.c_void_p`
        Note:
            Implemented as function to not collide with
            autogenerated property names.
        """
        return ctypes.c_void_p(int(self))

    @staticmethod
    def PROPERTIES():
        return []

    def __contains__(self,item):
        properties = self.PROPERTIES()
        return item in properties

    def __getitem__(self,item):
        properties = self.PROPERTIES()
        if isinstance(item,int):
            if item < 0 or item >= len(properties):
                raise IndexError()
            return getattr(self,properties[item])
        raise ValueError("'item' type must be 'int'")


hipfftHandle = hipfftHandle_t

hipfftComplex = float2

hipfftDoubleComplex = double2

@cython.embedsignature(True)
def hipfftPlan1d(int nx, object type, int batch):
    r"""Create a new one-dimensional FFT plan.

    Allocate and initialize a new one-dimensional FFT plan.

    Args:
        nx (:py:obj:`~.int`) -- *IN*:
            FFT length.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to compute.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.hipfftHandle_t`:
                Pointer to the FFT plan handle.

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftPlan1d(hipfftHandle * plan, int nx, hipfftType type, int batch)
    """
    cdef hipfftHandle_t plan = hipfftHandle_t.fromPtr(NULL)
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef cyhipfft.hipfftType_t _cy_hipfftPlan1d__arg_2 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftPlan1d__retval
    with nogil:
        _cy_hipfftPlan1d__retval = cyhipfft.hipfftPlan1d(<cyhipfft.hipfftHandle_t**>&plan._ptr,nx,_cy_hipfftPlan1d__arg_2,batch)
    return (hipfftResult_t(_cy_hipfftPlan1d__retval),None if plan._ptr == NULL else plan)


@cython.embedsignature(True)
def hipfftPlan2d(int nx, int ny, object type):
    r"""Create a new two-dimensional FFT plan.

    Allocate and initialize a new two-dimensional FFT plan.
    Two-dimensional data should be stored in C ordering (row-major
    format), so that indexes in y-direction (j index) vary the
    fastest.

    Args:
        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction (slow index).

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction (fast index).

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.hipfftHandle_t`:
                Pointer to the FFT plan handle.

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftPlan2d(hipfftHandle * plan, int nx, int ny, hipfftType type)
    """
    cdef hipfftHandle_t plan = hipfftHandle_t.fromPtr(NULL)
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef cyhipfft.hipfftType_t _cy_hipfftPlan2d__arg_3 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftPlan2d__retval
    with nogil:
        _cy_hipfftPlan2d__retval = cyhipfft.hipfftPlan2d(<cyhipfft.hipfftHandle_t**>&plan._ptr,nx,ny,_cy_hipfftPlan2d__arg_3)
    return (hipfftResult_t(_cy_hipfftPlan2d__retval),None if plan._ptr == NULL else plan)


@cython.embedsignature(True)
def hipfftPlan3d(int nx, int ny, int nz, object type):
    r"""Create a new three-dimensional FFT plan.

    Allocate and initialize a new three-dimensional FFT plan.
    Three-dimensional data should be stored in C ordering (row-major
    format), so that indexes in z-direction (k index) vary the
    fastest.

    Args:
        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction (slowest index).

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction.

        nz (:py:obj:`~.int`) -- *IN*:
            Number of elements in the z-direction (fastest index).

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.hipfftHandle_t`:
                Pointer to the FFT plan handle.

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftPlan3d(hipfftHandle * plan, int nx, int ny, int nz, hipfftType type)
    """
    cdef hipfftHandle_t plan = hipfftHandle_t.fromPtr(NULL)
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef cyhipfft.hipfftType_t _cy_hipfftPlan3d__arg_4 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftPlan3d__retval
    with nogil:
        _cy_hipfftPlan3d__retval = cyhipfft.hipfftPlan3d(<cyhipfft.hipfftHandle_t**>&plan._ptr,nx,ny,nz,_cy_hipfftPlan3d__arg_4)
    return (hipfftResult_t(_cy_hipfftPlan3d__retval),None if plan._ptr == NULL else plan)


@cython.embedsignature(True)
def hipfftPlanMany(int rank, object n, object inembed, int istride, int idist, object onembed, int ostride, int odist, object type, int batch):
    r"""Create a new batched rank-dimensional FFT plan with advanced data layout.

    Allocate and initialize a new batched rank-dimensional
    FFT plan. The number of elements to transform in each direction of
    the input data is specified in n.

    The batch parameter tells hipFFT how many transforms to perform.
    The distance between the first elements of two consecutive batches
    of the input and output data are specified with the idist and odist
    parameters.

    The inembed and onembed parameters define the input and output data
    layouts. The number of elements in the data is assumed to be larger
    than the number of elements in the transform. Strided data layouts
    are also supported. Strides along the fastest direction in the input
    and output data are specified via the istride and ostride parameters.

    If both inembed and onembed parameters are set to NULL, all the
    advanced data layout parameters are ignored and reverted to default
    values, i.e., the batched transform is performed with non-strided data
    access and the number of data/transform elements are assumed to be
    equivalent.

    Args:
        rank (:py:obj:`~.int`) -- *IN*:
            Dimension of transform (1, 2, or 3).

        n (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements to transform in the x/y/z directions.

        inembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements in the input data in the x/y/z directions.

        istride (:py:obj:`~.int`) -- *IN*:
            Distance between two successive elements in the input data.

        idist (:py:obj:`~.int`) -- *IN*:
            Distance between input batches.

        onembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements in the output data in the x/y/z directions.

        ostride (:py:obj:`~.int`) -- *IN*:
            Distance between two successive elements in the output data.

        odist (:py:obj:`~.int`) -- *IN*:
            Distance between output batches.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to perform.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.hipfftHandle_t`:
                Pointer to the FFT plan handle.

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftPlanMany(hipfftHandle * plan, int rank, int * n, int * inembed, int istride, int idist, int * onembed, int ostride, int odist, hipfftType type, int batch)
    """
    cdef hipfftHandle_t plan = hipfftHandle_t.fromPtr(NULL)
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftPlanMany__arg_2_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(n)
    cdef int * _cy_hipfftPlanMany__arg_2 = <int *>_cy_hipfftPlanMany__arg_2_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftPlanMany__arg_3_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(inembed)
    cdef int * _cy_hipfftPlanMany__arg_3 = <int *>_cy_hipfftPlanMany__arg_3_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftPlanMany__arg_6_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(onembed)
    cdef int * _cy_hipfftPlanMany__arg_6 = <int *>_cy_hipfftPlanMany__arg_6_obj.getPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftPlanMany__arg_9 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftPlanMany__retval
    with nogil:
        _cy_hipfftPlanMany__retval = cyhipfft.hipfftPlanMany(<cyhipfft.hipfftHandle_t**>&plan._ptr,rank,_cy_hipfftPlanMany__arg_2,_cy_hipfftPlanMany__arg_3,istride,idist,_cy_hipfftPlanMany__arg_6,ostride,odist,_cy_hipfftPlanMany__arg_9,batch)
    return (hipfftResult_t(_cy_hipfftPlanMany__retval),None if plan._ptr == NULL else plan)


@cython.embedsignature(True)
def hipfftCreate():
    r"""Allocate a new plan.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.hipfftHandle_t`:
                Pointer to the FFT plan handle to be allocated.

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftCreate(hipfftHandle * plan)
    """
    cdef hipfftHandle_t plan = hipfftHandle_t.fromPtr(NULL)
    cdef cyhipfft.hipfftResult_t _cy_hipfftCreate__retval
    with nogil:
        _cy_hipfftCreate__retval = cyhipfft.hipfftCreate(<cyhipfft.hipfftHandle_t**>&plan._ptr)
    return (hipfftResult_t(_cy_hipfftCreate__retval),None if plan._ptr == NULL else plan)


@cython.embedsignature(True)
def hipfftExtPlanScaleFactor(object plan, double scalefactor):
    r"""Set scaling factor.

    hipFFT multiplies each element of the result by the given factor at the end of the transform.

    The supplied factor must be a finite number.  That is, it must neither be infinity nor NaN.

    This function must be called after the plan is allocated using
    ::hipfftCreate, but before the plan is initialized by any of the
    "MakePlan" functions.  Therefore, API functions that combine
    creation and initialization (::hipfftPlan1d, ::hipfftPlan2d,
    ::hipfftPlan3d, and ::hipfftPlanMany) cannot set a scale factor.

    Note that the scale factor applies to both forward and
    backward transforms executed with the specified plan handle.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`):
            (undocumented)

        scalefactor (:py:obj:`~.float`/:py:obj:`~.int`):
            (undocumented)

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExtPlanScaleFactor(hipfftHandle plan, double scalefactor)
    """
    cdef hipfftHandle_t _cy_hipfftExtPlanScaleFactor__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExtPlanScaleFactor__arg_0 = _cy_hipfftExtPlanScaleFactor__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExtPlanScaleFactor__retval
    with nogil:
        _cy_hipfftExtPlanScaleFactor__retval = cyhipfft.hipfftExtPlanScaleFactor(_cy_hipfftExtPlanScaleFactor__arg_0,scalefactor)
    return (hipfftResult_t(_cy_hipfftExtPlanScaleFactor__retval),)


@cython.embedsignature(True)
def hipfftMakePlan1d(object plan, int nx, object type, int batch):
    r"""Initialize a new one-dimensional FFT plan.

    Assumes that the plan has been created already, and
    modifies the plan associated with the plan handle.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Handle of the FFT plan.

        nx (:py:obj:`~.int`) -- *IN*:
            FFT length.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to compute.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftMakePlan1d(hipfftHandle plan, int nx, hipfftType type, int batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftMakePlan1d__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftMakePlan1d__arg_0 = _cy_hipfftMakePlan1d__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftMakePlan1d__arg_2 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftMakePlan1d__retval
    with nogil:
        _cy_hipfftMakePlan1d__retval = cyhipfft.hipfftMakePlan1d(_cy_hipfftMakePlan1d__arg_0,nx,_cy_hipfftMakePlan1d__arg_2,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftMakePlan1d__retval),workSize)


@cython.embedsignature(True)
def hipfftMakePlan2d(object plan, int nx, int ny, object type):
    r"""Initialize a new two-dimensional FFT plan.

    Assumes that the plan has been created already, and
    modifies the plan associated with the plan handle.
    Two-dimensional data should be stored in C ordering (row-major
    format), so that indexes in y-direction (j index) vary the
    fastest.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Handle of the FFT plan.

        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction (slow index).

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction (fast index).

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftMakePlan2d(hipfftHandle plan, int nx, int ny, hipfftType type, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftMakePlan2d__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftMakePlan2d__arg_0 = _cy_hipfftMakePlan2d__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftMakePlan2d__arg_3 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftMakePlan2d__retval
    with nogil:
        _cy_hipfftMakePlan2d__retval = cyhipfft.hipfftMakePlan2d(_cy_hipfftMakePlan2d__arg_0,nx,ny,_cy_hipfftMakePlan2d__arg_3,&workSize)
    return (hipfftResult_t(_cy_hipfftMakePlan2d__retval),workSize)


@cython.embedsignature(True)
def hipfftMakePlan3d(object plan, int nx, int ny, int nz, object type):
    r"""Initialize a new two-dimensional FFT plan.

    Assumes that the plan has been created already, and
    modifies the plan associated with the plan handle.
    Three-dimensional data should be stored in C ordering (row-major
    format), so that indexes in z-direction (k index) vary the
    fastest.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Handle of the FFT plan.

        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction (slowest index).

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction.

        nz (:py:obj:`~.int`) -- *IN*:
            Number of elements in the z-direction (fastest index).

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftMakePlan3d(hipfftHandle plan, int nx, int ny, int nz, hipfftType type, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftMakePlan3d__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftMakePlan3d__arg_0 = _cy_hipfftMakePlan3d__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftMakePlan3d__arg_4 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftMakePlan3d__retval
    with nogil:
        _cy_hipfftMakePlan3d__retval = cyhipfft.hipfftMakePlan3d(_cy_hipfftMakePlan3d__arg_0,nx,ny,nz,_cy_hipfftMakePlan3d__arg_4,&workSize)
    return (hipfftResult_t(_cy_hipfftMakePlan3d__retval),workSize)


@cython.embedsignature(True)
def hipfftMakePlanMany(int rank, object n, object inembed, int istride, int idist, object onembed, int ostride, int odist, object type, int batch):
    r"""Initialize a new batched rank-dimensional FFT plan with advanced data layout.

    Assumes that the plan has been created already, and
    modifies the plan associated with the plan handle. The number
    of elements to transform in each direction of the input data
    in the FFT plan is specified in n.

    The batch parameter tells hipFFT how many transforms to perform.
    The distance between the first elements of two consecutive batches
    of the input and output data are specified with the idist and odist
    parameters.

    The inembed and onembed parameters define the input and output data
    layouts. The number of elements in the data is assumed to be larger
    than the number of elements in the transform. Strided data layouts
    are also supported. Strides along the fastest direction in the input
    and output data are specified via the istride and ostride parameters.

    If both inembed and onembed parameters are set to NULL, all the
    advanced data layout parameters are ignored and reverted to default
    values, i.e., the batched transform is performed with non-strided data
    access and the number of data/transform elements are assumed to be
    equivalent.

    Args:
        rank (:py:obj:`~.int`) -- *IN*:
            Dimension of transform (1, 2, or 3).

        n (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements to transform in the x/y/z directions.

        inembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements in the input data in the x/y/z directions.

        istride (:py:obj:`~.int`) -- *IN*:
            Distance between two successive elements in the input data.

        idist (:py:obj:`~.int`) -- *IN*:
            Distance between input batches.

        onembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements in the output data in the x/y/z directions.

        ostride (:py:obj:`~.int`) -- *IN*:
            Distance between two successive elements in the output data.

        odist (:py:obj:`~.int`) -- *IN*:
            Distance between output batches.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to perform.

    Returns:
        A :py:obj:`~.tuple` of size 3 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.hipfftHandle_t`:
                Pointer to the FFT plan handle.
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftMakePlanMany(hipfftHandle plan, int rank, int * n, int * inembed, int istride, int idist, int * onembed, int ostride, int odist, hipfftType type, int batch, size_t * workSize)
    """
    cdef hipfftHandle_t plan = hipfftHandle_t.new()
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftMakePlanMany__arg_2_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(n)
    cdef int * _cy_hipfftMakePlanMany__arg_2 = <int *>_cy_hipfftMakePlanMany__arg_2_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftMakePlanMany__arg_3_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(inembed)
    cdef int * _cy_hipfftMakePlanMany__arg_3 = <int *>_cy_hipfftMakePlanMany__arg_3_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftMakePlanMany__arg_6_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(onembed)
    cdef int * _cy_hipfftMakePlanMany__arg_6 = <int *>_cy_hipfftMakePlanMany__arg_6_obj.getPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftMakePlanMany__arg_9 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftMakePlanMany__retval
    with nogil:
        _cy_hipfftMakePlanMany__retval = cyhipfft.hipfftMakePlanMany(<cyhipfft.hipfftHandle_t*>plan._ptr,rank,_cy_hipfftMakePlanMany__arg_2,_cy_hipfftMakePlanMany__arg_3,istride,idist,_cy_hipfftMakePlanMany__arg_6,ostride,odist,_cy_hipfftMakePlanMany__arg_9,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftMakePlanMany__retval),plan,workSize)


@cython.embedsignature(True)
def hipfftMakePlanMany64(object plan, int rank, object n, object inembed, long long istride, long long idist, object onembed, long long ostride, long long odist, object type, long long batch):
    r"""(No short description, might be part of a group.)

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`):
            (undocumented)

        rank (:py:obj:`~.int`):
            (undocumented)

        n (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        inembed (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        istride (:py:obj:`~.int`):
            (undocumented)

        idist (:py:obj:`~.int`):
            (undocumented)

        onembed (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        ostride (:py:obj:`~.int`):
            (undocumented)

        odist (:py:obj:`~.int`):
            (undocumented)

        type (:py:obj:`~.hipfftType_t`):
            (undocumented)

        batch (:py:obj:`~.int`):
            (undocumented)

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * workSize (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftMakePlanMany64(hipfftHandle plan, int rank, long long * n, long long * inembed, long long istride, long long idist, long long * onembed, long long ostride, long long odist, hipfftType type, long long batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftMakePlanMany64__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftMakePlanMany64__arg_0 = _cy_hipfftMakePlanMany64__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftMakePlanMany64__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(n)
    cdef long long * _cy_hipfftMakePlanMany64__arg_2 = <long long *>_cy_hipfftMakePlanMany64__arg_2_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftMakePlanMany64__arg_3_obj = rocm.bindings.util.types.Pointer.fromPyobj(inembed)
    cdef long long * _cy_hipfftMakePlanMany64__arg_3 = <long long *>_cy_hipfftMakePlanMany64__arg_3_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftMakePlanMany64__arg_6_obj = rocm.bindings.util.types.Pointer.fromPyobj(onembed)
    cdef long long * _cy_hipfftMakePlanMany64__arg_6 = <long long *>_cy_hipfftMakePlanMany64__arg_6_obj.getPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftMakePlanMany64__arg_9 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftMakePlanMany64__retval
    with nogil:
        _cy_hipfftMakePlanMany64__retval = cyhipfft.hipfftMakePlanMany64(_cy_hipfftMakePlanMany64__arg_0,rank,_cy_hipfftMakePlanMany64__arg_2,_cy_hipfftMakePlanMany64__arg_3,istride,idist,_cy_hipfftMakePlanMany64__arg_6,ostride,odist,_cy_hipfftMakePlanMany64__arg_9,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftMakePlanMany64__retval),workSize)


@cython.embedsignature(True)
def hipfftEstimate1d(int nx, object type, int batch):
    r"""Return an estimate of the work area size required for a 1D plan.

    Args:
        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to perform.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftEstimate1d(int nx, hipfftType type, int batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef cyhipfft.hipfftType_t _cy_hipfftEstimate1d__arg_1 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftEstimate1d__retval
    with nogil:
        _cy_hipfftEstimate1d__retval = cyhipfft.hipfftEstimate1d(nx,_cy_hipfftEstimate1d__arg_1,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftEstimate1d__retval),workSize)


@cython.embedsignature(True)
def hipfftEstimate2d(int nx, int ny, object type):
    r"""Return an estimate of the work area size required for a 2D plan.

    Args:
        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction.

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftEstimate2d(int nx, int ny, hipfftType type, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef cyhipfft.hipfftType_t _cy_hipfftEstimate2d__arg_2 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftEstimate2d__retval
    with nogil:
        _cy_hipfftEstimate2d__retval = cyhipfft.hipfftEstimate2d(nx,ny,_cy_hipfftEstimate2d__arg_2,&workSize)
    return (hipfftResult_t(_cy_hipfftEstimate2d__retval),workSize)


@cython.embedsignature(True)
def hipfftEstimate3d(int nx, int ny, int nz, object type):
    r"""Return an estimate of the work area size required for a 3D plan.

    Args:
        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction.

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction.

        nz (:py:obj:`~.int`) -- *IN*:
            Number of elements in the z-direction.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftEstimate3d(int nx, int ny, int nz, hipfftType type, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef cyhipfft.hipfftType_t _cy_hipfftEstimate3d__arg_3 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftEstimate3d__retval
    with nogil:
        _cy_hipfftEstimate3d__retval = cyhipfft.hipfftEstimate3d(nx,ny,nz,_cy_hipfftEstimate3d__arg_3,&workSize)
    return (hipfftResult_t(_cy_hipfftEstimate3d__retval),workSize)


@cython.embedsignature(True)
def hipfftEstimateMany(int rank, object n, object inembed, int istride, int idist, object onembed, int ostride, int odist, object type, int batch):
    r"""Return an estimate of the work area size required for a rank-dimensional plan.

    Args:
        rank (:py:obj:`~.int`) -- *IN*:
            Dimension of FFT transform (1, 2, or 3).

        n (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements in the x/y/z directions.

        inembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:

        istride (:py:obj:`~.int`) -- *IN*:

        idist (:py:obj:`~.int`) -- *IN*:
            Distance between input batches.

        onembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:

        ostride (:py:obj:`~.int`) -- *IN*:

        odist (:py:obj:`~.int`) -- *IN*:
            Distance between output batches.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to perform.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftEstimateMany(int rank, int * n, int * inembed, int istride, int idist, int * onembed, int ostride, int odist, hipfftType type, int batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftEstimateMany__arg_1_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(n)
    cdef int * _cy_hipfftEstimateMany__arg_1 = <int *>_cy_hipfftEstimateMany__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftEstimateMany__arg_2_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(inembed)
    cdef int * _cy_hipfftEstimateMany__arg_2 = <int *>_cy_hipfftEstimateMany__arg_2_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftEstimateMany__arg_5_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(onembed)
    cdef int * _cy_hipfftEstimateMany__arg_5 = <int *>_cy_hipfftEstimateMany__arg_5_obj.getPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftEstimateMany__arg_8 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftEstimateMany__retval
    with nogil:
        _cy_hipfftEstimateMany__retval = cyhipfft.hipfftEstimateMany(rank,_cy_hipfftEstimateMany__arg_1,_cy_hipfftEstimateMany__arg_2,istride,idist,_cy_hipfftEstimateMany__arg_5,ostride,odist,_cy_hipfftEstimateMany__arg_8,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftEstimateMany__retval),workSize)


@cython.embedsignature(True)
def hipfftGetSize1d(object plan, int nx, object type, int batch):
    r"""Return size of the work area size required for a 1D plan.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to perform.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetSize1d(hipfftHandle plan, int nx, hipfftType type, int batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftGetSize1d__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftGetSize1d__arg_0 = _cy_hipfftGetSize1d__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftGetSize1d__arg_2 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetSize1d__retval
    with nogil:
        _cy_hipfftGetSize1d__retval = cyhipfft.hipfftGetSize1d(_cy_hipfftGetSize1d__arg_0,nx,_cy_hipfftGetSize1d__arg_2,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftGetSize1d__retval),workSize)


@cython.embedsignature(True)
def hipfftGetSize2d(object plan, int nx, int ny, object type):
    r"""Return size of the work area size required for a 2D plan.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction.

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetSize2d(hipfftHandle plan, int nx, int ny, hipfftType type, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftGetSize2d__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftGetSize2d__arg_0 = _cy_hipfftGetSize2d__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftGetSize2d__arg_3 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetSize2d__retval
    with nogil:
        _cy_hipfftGetSize2d__retval = cyhipfft.hipfftGetSize2d(_cy_hipfftGetSize2d__arg_0,nx,ny,_cy_hipfftGetSize2d__arg_3,&workSize)
    return (hipfftResult_t(_cy_hipfftGetSize2d__retval),workSize)


@cython.embedsignature(True)
def hipfftGetSize3d(object plan, int nx, int ny, int nz, object type):
    r"""Return size of the work area size required for a 3D plan.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

        nx (:py:obj:`~.int`) -- *IN*:
            Number of elements in the x-direction.

        ny (:py:obj:`~.int`) -- *IN*:
            Number of elements in the y-direction.

        nz (:py:obj:`~.int`) -- *IN*:
            Number of elements in the z-direction.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetSize3d(hipfftHandle plan, int nx, int ny, int nz, hipfftType type, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftGetSize3d__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftGetSize3d__arg_0 = _cy_hipfftGetSize3d__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftGetSize3d__arg_4 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetSize3d__retval
    with nogil:
        _cy_hipfftGetSize3d__retval = cyhipfft.hipfftGetSize3d(_cy_hipfftGetSize3d__arg_0,nx,ny,nz,_cy_hipfftGetSize3d__arg_4,&workSize)
    return (hipfftResult_t(_cy_hipfftGetSize3d__retval),workSize)


@cython.embedsignature(True)
def hipfftGetSizeMany(object plan, int rank, object n, object inembed, int istride, int idist, object onembed, int ostride, int odist, object type, int batch):
    r"""Return size of the work area size required for a rank-dimensional plan.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

        rank (:py:obj:`~.int`) -- *IN*:
            Dimension of FFT transform (1, 2, or 3).

        n (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:
            Number of elements in the x/y/z directions.

        inembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:

        istride (:py:obj:`~.int`) -- *IN*:

        idist (:py:obj:`~.int`) -- *IN*:
            Distance between input batches.

        onembed (:py:obj:`~.rocm.bindings.util.types.PointerToInt`/:py:obj:`~.object`) -- *IN*:

        ostride (:py:obj:`~.int`) -- *IN*:

        odist (:py:obj:`~.int`) -- *IN*:
            Distance between output batches.

        type (:py:obj:`~.hipfftType_t`) -- *IN*:
            FFT type.

        batch (:py:obj:`~.int`) -- *IN*:
            Number of batched transforms to perform.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetSizeMany(hipfftHandle plan, int rank, int * n, int * inembed, int istride, int idist, int * onembed, int ostride, int odist, hipfftType type, int batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftGetSizeMany__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftGetSizeMany__arg_0 = _cy_hipfftGetSizeMany__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftGetSizeMany__arg_2_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(n)
    cdef int * _cy_hipfftGetSizeMany__arg_2 = <int *>_cy_hipfftGetSizeMany__arg_2_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftGetSizeMany__arg_3_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(inembed)
    cdef int * _cy_hipfftGetSizeMany__arg_3 = <int *>_cy_hipfftGetSizeMany__arg_3_obj.getPtr()
    cdef rocm.bindings.util.types.PointerToInt _cy_hipfftGetSizeMany__arg_6_obj = rocm.bindings.util.types.PointerToInt.fromPyobj(onembed)
    cdef int * _cy_hipfftGetSizeMany__arg_6 = <int *>_cy_hipfftGetSizeMany__arg_6_obj.getPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftGetSizeMany__arg_9 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetSizeMany__retval
    with nogil:
        _cy_hipfftGetSizeMany__retval = cyhipfft.hipfftGetSizeMany(_cy_hipfftGetSizeMany__arg_0,rank,_cy_hipfftGetSizeMany__arg_2,_cy_hipfftGetSizeMany__arg_3,istride,idist,_cy_hipfftGetSizeMany__arg_6,ostride,odist,_cy_hipfftGetSizeMany__arg_9,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftGetSizeMany__retval),workSize)


@cython.embedsignature(True)
def hipfftGetSizeMany64(object plan, int rank, object n, object inembed, long long istride, long long idist, object onembed, long long ostride, long long odist, object type, long long batch):
    r"""(No short description, might be part of a group.)

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`):
            (undocumented)

        rank (:py:obj:`~.int`):
            (undocumented)

        n (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        inembed (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        istride (:py:obj:`~.int`):
            (undocumented)

        idist (:py:obj:`~.int`):
            (undocumented)

        onembed (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        ostride (:py:obj:`~.int`):
            (undocumented)

        odist (:py:obj:`~.int`):
            (undocumented)

        type (:py:obj:`~.hipfftType_t`):
            (undocumented)

        batch (:py:obj:`~.int`):
            (undocumented)

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * workSize (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetSizeMany64(hipfftHandle plan, int rank, long long * n, long long * inembed, long long istride, long long idist, long long * onembed, long long ostride, long long odist, hipfftType type, long long batch, size_t * workSize)
    """
    if not isinstance(type,_hipfftType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftType_t__Base'")
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftGetSizeMany64__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftGetSizeMany64__arg_0 = _cy_hipfftGetSizeMany64__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftGetSizeMany64__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(n)
    cdef long long * _cy_hipfftGetSizeMany64__arg_2 = <long long *>_cy_hipfftGetSizeMany64__arg_2_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftGetSizeMany64__arg_3_obj = rocm.bindings.util.types.Pointer.fromPyobj(inembed)
    cdef long long * _cy_hipfftGetSizeMany64__arg_3 = <long long *>_cy_hipfftGetSizeMany64__arg_3_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftGetSizeMany64__arg_6_obj = rocm.bindings.util.types.Pointer.fromPyobj(onembed)
    cdef long long * _cy_hipfftGetSizeMany64__arg_6 = <long long *>_cy_hipfftGetSizeMany64__arg_6_obj.getPtr()
    cdef cyhipfft.hipfftType_t _cy_hipfftGetSizeMany64__arg_9 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetSizeMany64__retval
    with nogil:
        _cy_hipfftGetSizeMany64__retval = cyhipfft.hipfftGetSizeMany64(_cy_hipfftGetSizeMany64__arg_0,rank,_cy_hipfftGetSizeMany64__arg_2,_cy_hipfftGetSizeMany64__arg_3,istride,idist,_cy_hipfftGetSizeMany64__arg_6,ostride,odist,_cy_hipfftGetSizeMany64__arg_9,batch,&workSize)
    return (hipfftResult_t(_cy_hipfftGetSizeMany64__retval),workSize)


@cython.embedsignature(True)
def hipfftGetSize(object plan):
    r"""Return size of the work area size required for a rank-dimensional plan.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Pointer to work area size (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetSize(hipfftHandle plan, size_t * workSize)
    """
    cdef size_t workSize
    cdef hipfftHandle_t _cy_hipfftGetSize__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftGetSize__arg_0 = _cy_hipfftGetSize__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetSize__retval
    with nogil:
        _cy_hipfftGetSize__retval = cyhipfft.hipfftGetSize(_cy_hipfftGetSize__arg_0,&workSize)
    return (hipfftResult_t(_cy_hipfftGetSize__retval),workSize)


@cython.embedsignature(True)
def hipfftSetAutoAllocation(object plan, int autoAllocate):
    r"""Set the plan's auto-allocation flag.  The plan will allocate its own workarea.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

        autoAllocate (:py:obj:`~.int`) -- *IN*:
            0 to disable auto-allocation, non-zero to enable.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftSetAutoAllocation(hipfftHandle plan, int autoAllocate)
    """
    cdef hipfftHandle_t _cy_hipfftSetAutoAllocation__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftSetAutoAllocation__arg_0 = _cy_hipfftSetAutoAllocation__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftSetAutoAllocation__retval
    with nogil:
        _cy_hipfftSetAutoAllocation__retval = cyhipfft.hipfftSetAutoAllocation(_cy_hipfftSetAutoAllocation__arg_0,autoAllocate)
    return (hipfftResult_t(_cy_hipfftSetAutoAllocation__retval),)


@cython.embedsignature(True)
def hipfftSetWorkArea(object plan, object workArea):
    r"""Set the plan's work area.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Pointer to the FFT plan.

        workArea (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Pointer to the work area (on device).

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftSetWorkArea(hipfftHandle plan, void * workArea)
    """
    cdef hipfftHandle_t _cy_hipfftSetWorkArea__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftSetWorkArea__arg_0 = _cy_hipfftSetWorkArea__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftSetWorkArea__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(workArea)
    cdef void * _cy_hipfftSetWorkArea__arg_1 = <void *>_cy_hipfftSetWorkArea__arg_1_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftSetWorkArea__retval
    with nogil:
        _cy_hipfftSetWorkArea__retval = cyhipfft.hipfftSetWorkArea(_cy_hipfftSetWorkArea__arg_0,_cy_hipfftSetWorkArea__arg_1)
    return (hipfftResult_t(_cy_hipfftSetWorkArea__retval),)


@cython.embedsignature(True)
def hipfftExecC2C(object plan, object idata, object odata, int direction):
    r"""Execute a (float) complex-to-complex FFT.

    If the input and output buffers are equal, an in-place
    transform is performed.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        idata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Input data (on device).

        odata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *OUT*:
            Output data (on device).

        direction (:py:obj:`~.int`) -- *IN*:
            Either `HIPFFT_FORWARD` or `HIPFFT_BACKWARD`.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExecC2C(hipfftHandle plan, hipfftComplex * idata, hipfftComplex * odata, int direction)
    """
    cdef hipfftHandle_t _cy_hipfftExecC2C__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExecC2C__arg_0 = _cy_hipfftExecC2C__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecC2C__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(idata)
    cdef cyhipfft.float2 * _cy_hipfftExecC2C__arg_1 = <cyhipfft.float2 *>_cy_hipfftExecC2C__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecC2C__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(odata)
    cdef cyhipfft.float2 * _cy_hipfftExecC2C__arg_2 = <cyhipfft.float2 *>_cy_hipfftExecC2C__arg_2_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExecC2C__retval
    with nogil:
        _cy_hipfftExecC2C__retval = cyhipfft.hipfftExecC2C(_cy_hipfftExecC2C__arg_0,_cy_hipfftExecC2C__arg_1,_cy_hipfftExecC2C__arg_2,direction)
    return (hipfftResult_t(_cy_hipfftExecC2C__retval),)


@cython.embedsignature(True)
def hipfftExecR2C(object plan, object idata, object odata):
    r"""Execute a (float) real-to-complex FFT.

    If the input and output buffers are equal, an in-place
    transform is performed.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        idata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Input data (on device).

        odata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *OUT*:
            Output data (on device).

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExecR2C(hipfftHandle plan, hipfftReal * idata, hipfftComplex * odata)
    """
    cdef hipfftHandle_t _cy_hipfftExecR2C__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExecR2C__arg_0 = _cy_hipfftExecR2C__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecR2C__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(idata)
    cdef float * _cy_hipfftExecR2C__arg_1 = <float *>_cy_hipfftExecR2C__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecR2C__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(odata)
    cdef cyhipfft.float2 * _cy_hipfftExecR2C__arg_2 = <cyhipfft.float2 *>_cy_hipfftExecR2C__arg_2_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExecR2C__retval
    with nogil:
        _cy_hipfftExecR2C__retval = cyhipfft.hipfftExecR2C(_cy_hipfftExecR2C__arg_0,_cy_hipfftExecR2C__arg_1,_cy_hipfftExecR2C__arg_2)
    return (hipfftResult_t(_cy_hipfftExecR2C__retval),)


@cython.embedsignature(True)
def hipfftExecC2R(object plan, object idata, object odata):
    r"""Execute a (float) complex-to-real FFT.

    If the input and output buffers are equal, an in-place
    transform is performed.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        idata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Input data (on device).

        odata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *OUT*:
            Output data (on device).

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExecC2R(hipfftHandle plan, hipfftComplex * idata, hipfftReal * odata)
    """
    cdef hipfftHandle_t _cy_hipfftExecC2R__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExecC2R__arg_0 = _cy_hipfftExecC2R__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecC2R__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(idata)
    cdef cyhipfft.float2 * _cy_hipfftExecC2R__arg_1 = <cyhipfft.float2 *>_cy_hipfftExecC2R__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecC2R__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(odata)
    cdef float * _cy_hipfftExecC2R__arg_2 = <float *>_cy_hipfftExecC2R__arg_2_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExecC2R__retval
    with nogil:
        _cy_hipfftExecC2R__retval = cyhipfft.hipfftExecC2R(_cy_hipfftExecC2R__arg_0,_cy_hipfftExecC2R__arg_1,_cy_hipfftExecC2R__arg_2)
    return (hipfftResult_t(_cy_hipfftExecC2R__retval),)


@cython.embedsignature(True)
def hipfftExecZ2Z(object plan, object idata, object odata, int direction):
    r"""Execute a (double) complex-to-complex FFT.

    If the input and output buffers are equal, an in-place
    transform is performed.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        idata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Input data (on device).

        odata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *OUT*:
            Output data (on device).

        direction (:py:obj:`~.int`) -- *IN*:
            Either `HIPFFT_FORWARD` or `HIPFFT_BACKWARD`.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExecZ2Z(hipfftHandle plan, hipfftDoubleComplex * idata, hipfftDoubleComplex * odata, int direction)
    """
    cdef hipfftHandle_t _cy_hipfftExecZ2Z__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExecZ2Z__arg_0 = _cy_hipfftExecZ2Z__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecZ2Z__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(idata)
    cdef cyhipfft.double2 * _cy_hipfftExecZ2Z__arg_1 = <cyhipfft.double2 *>_cy_hipfftExecZ2Z__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecZ2Z__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(odata)
    cdef cyhipfft.double2 * _cy_hipfftExecZ2Z__arg_2 = <cyhipfft.double2 *>_cy_hipfftExecZ2Z__arg_2_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExecZ2Z__retval
    with nogil:
        _cy_hipfftExecZ2Z__retval = cyhipfft.hipfftExecZ2Z(_cy_hipfftExecZ2Z__arg_0,_cy_hipfftExecZ2Z__arg_1,_cy_hipfftExecZ2Z__arg_2,direction)
    return (hipfftResult_t(_cy_hipfftExecZ2Z__retval),)


@cython.embedsignature(True)
def hipfftExecD2Z(object plan, object idata, object odata):
    r"""Execute a (double) real-to-complex FFT.

    If the input and output buffers are equal, an in-place
    transform is performed.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        idata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Input data (on device).

        odata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *OUT*:
            Output data (on device).

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExecD2Z(hipfftHandle plan, hipfftDoubleReal * idata, hipfftDoubleComplex * odata)
    """
    cdef hipfftHandle_t _cy_hipfftExecD2Z__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExecD2Z__arg_0 = _cy_hipfftExecD2Z__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecD2Z__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(idata)
    cdef double * _cy_hipfftExecD2Z__arg_1 = <double *>_cy_hipfftExecD2Z__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecD2Z__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(odata)
    cdef cyhipfft.double2 * _cy_hipfftExecD2Z__arg_2 = <cyhipfft.double2 *>_cy_hipfftExecD2Z__arg_2_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExecD2Z__retval
    with nogil:
        _cy_hipfftExecD2Z__retval = cyhipfft.hipfftExecD2Z(_cy_hipfftExecD2Z__arg_0,_cy_hipfftExecD2Z__arg_1,_cy_hipfftExecD2Z__arg_2)
    return (hipfftResult_t(_cy_hipfftExecD2Z__retval),)


@cython.embedsignature(True)
def hipfftExecZ2D(object plan, object idata, object odata):
    r"""Execute a (double) complex-to-real FFT.

    If the input and output buffers are equal, an in-place
    transform is performed.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        idata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            Input data (on device).

        odata (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *OUT*:
            Output data (on device).

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftExecZ2D(hipfftHandle plan, hipfftDoubleComplex * idata, hipfftDoubleReal * odata)
    """
    cdef hipfftHandle_t _cy_hipfftExecZ2D__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftExecZ2D__arg_0 = _cy_hipfftExecZ2D__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecZ2D__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(idata)
    cdef cyhipfft.double2 * _cy_hipfftExecZ2D__arg_1 = <cyhipfft.double2 *>_cy_hipfftExecZ2D__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftExecZ2D__arg_2_obj = rocm.bindings.util.types.Pointer.fromPyobj(odata)
    cdef double * _cy_hipfftExecZ2D__arg_2 = <double *>_cy_hipfftExecZ2D__arg_2_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftExecZ2D__retval
    with nogil:
        _cy_hipfftExecZ2D__retval = cyhipfft.hipfftExecZ2D(_cy_hipfftExecZ2D__arg_0,_cy_hipfftExecZ2D__arg_1,_cy_hipfftExecZ2D__arg_2)
    return (hipfftResult_t(_cy_hipfftExecZ2D__retval),)


@cython.embedsignature(True)
def hipfftSetStream(object plan, object stream):
    r"""Set HIP stream to execute plan on.

    Associates a HIP stream with a hipFFT plan.  All kernels
    launched by this plan are associated with the provided stream.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            The FFT plan.

        stream (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`) -- *IN*:
            The HIP stream.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftSetStream(hipfftHandle plan, hipStream_t stream)
    """
    cdef hipfftHandle_t _cy_hipfftSetStream__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftSetStream__arg_0 = _cy_hipfftSetStream__arg_0_obj.getElementPtr()
    cdef rocm.bindings.util.types.Pointer _cy_hipfftSetStream__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(stream)
    cdef cyhipfft.hipStream_t _cy_hipfftSetStream__arg_1 = <cyhipfft.hipStream_t>_cy_hipfftSetStream__arg_1_obj.getPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftSetStream__retval
    with nogil:
        _cy_hipfftSetStream__retval = cyhipfft.hipfftSetStream(_cy_hipfftSetStream__arg_0,_cy_hipfftSetStream__arg_1)
    return (hipfftResult_t(_cy_hipfftSetStream__retval),)


@cython.embedsignature(True)
def hipfftDestroy(object plan):
    r"""Destroy and deallocate an existing plan.

    Args:
        plan (:py:obj:`~.hipfftHandle_t`/:py:obj:`~.object`) -- *IN*:
            Handle of the FFT plan to be destroyed.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftDestroy(hipfftHandle plan)
    """
    cdef hipfftHandle_t _cy_hipfftDestroy__arg_0_obj = hipfftHandle_t.fromPyobj(plan)
    cdef cyhipfft.hipfftHandle _cy_hipfftDestroy__arg_0 = _cy_hipfftDestroy__arg_0_obj.getElementPtr()
    cdef cyhipfft.hipfftResult_t _cy_hipfftDestroy__retval
    with nogil:
        _cy_hipfftDestroy__retval = cyhipfft.hipfftDestroy(_cy_hipfftDestroy__arg_0)
    return (hipfftResult_t(_cy_hipfftDestroy__retval),)


@cython.embedsignature(True)
def hipfftGetVersion():
    r"""Get rocFFT/cuFFT version.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                cuFFT/rocFFT version (returned value).

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetVersion(int * version)
    """
    cdef int version
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetVersion__retval
    with nogil:
        _cy_hipfftGetVersion__retval = cyhipfft.hipfftGetVersion(&version)
    return (hipfftResult_t(_cy_hipfftGetVersion__retval),version)


@cython.embedsignature(True)
def hipfftGetProperty(object type):
    r"""Get library property.

    Args:
        type (:py:obj:`~.hipfftLibraryPropertyType_t`) -- *IN*:
            Property type.

    Returns:
        A :py:obj:`~.tuple` of size 2 that contains (in that order):

        * :py:obj:`~.hipfftResult_t`: (undocumented)
        * :py:obj:`~.int`:
                Returned value.

    .. rubric:: C signature

    .. code-block:: c

        hipfftResult hipfftGetProperty(hipfftLibraryPropertyType type, int * value)
    """
    if not isinstance(type,_hipfftLibraryPropertyType_t__Base):
        raise TypeError("argument 'type' must be of type '_hipfftLibraryPropertyType_t__Base'")
    cdef int value
    cdef cyhipfft.hipfftLibraryPropertyType_t _cy_hipfftGetProperty__arg_0 = type.value
    cdef cyhipfft.hipfftResult_t _cy_hipfftGetProperty__retval
    with nogil:
        _cy_hipfftGetProperty__retval = cyhipfft.hipfftGetProperty(_cy_hipfftGetProperty__arg_0,&value)
    return (hipfftResult_t(_cy_hipfftGetProperty__retval),value)

__all__ = [
    "HIPFFT_FORWARD",
    "HIPFFT_BACKWARD",
    "_hipfftResult_t__Base",
    "hipfftResult_t",
    "hipfftResult",
    "_hipfftType_t__Base",
    "hipfftType_t",
    "hipfftType",
    "_hipfftLibraryPropertyType_t__Base",
    "hipfftLibraryPropertyType_t",
    "hipfftLibraryPropertyType",
    "hipfftHandle_t",
    "hipfftHandle",
    "hipfftComplex",
    "hipfftDoubleComplex",
    "hipfftPlan1d",
    "hipfftPlan2d",
    "hipfftPlan3d",
    "hipfftPlanMany",
    "hipfftCreate",
    "hipfftExtPlanScaleFactor",
    "hipfftMakePlan1d",
    "hipfftMakePlan2d",
    "hipfftMakePlan3d",
    "hipfftMakePlanMany",
    "hipfftMakePlanMany64",
    "hipfftEstimate1d",
    "hipfftEstimate2d",
    "hipfftEstimate3d",
    "hipfftEstimateMany",
    "hipfftGetSize1d",
    "hipfftGetSize2d",
    "hipfftGetSize3d",
    "hipfftGetSizeMany",
    "hipfftGetSizeMany64",
    "hipfftGetSize",
    "hipfftSetAutoAllocation",
    "hipfftSetWorkArea",
    "hipfftExecC2C",
    "hipfftExecR2C",
    "hipfftExecC2R",
    "hipfftExecZ2Z",
    "hipfftExecD2Z",
    "hipfftExecZ2D",
    "hipfftSetStream",
    "hipfftDestroy",
    "hipfftGetVersion",
    "hipfftGetProperty",
    "has_symbol",
]