# MIT License
#
# Copyright (c) 2023-2024 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

__author__ = "Advanced Micro Devices, Inc."

import keyword
import logging
import os
import sys
import textwrap

import clang.cindex

from . import cparser, doxyparser, tree
from .support import cython as support
from .support.recipes import control

_log = logging.getLogger("interfacegen")

# import original tree nodes so that the treefactory can use them via backend.
for name, attr in vars(tree).items():
    try:
        if issubclass(attr, tree.Node):
            globals()[name] = attr
    except TypeError:
        pass


indent = " " * 2

# TODO
restricted_names = []

restricted_names = keyword.kwlist + [
    "cdef",
    "cpdef",  # TODO extend
]

c_interface_funptr_name_template = "_{name}__funptr"

python_interface_retval_template = "_{name}__retval"

python_interface_record_properties_name = "PROPERTIES"

python_interface_pyobj_role_template = r":py:obj:`.{name}`"


def C_TO_FORTRAN(canonical_ctype: str):
    """Map a canonical C type to the Fortran type.

    Returns:
        `str`: The Fortran type.

    Note:
        For implementation details, see
        https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fC_005fBINDING.html
    """
    tokens = [
        tk
        for tk in canonical_ctype.split(" ")
        if tk not in ("const", "unsigned")
    ]
    if tokens in [
        ["char", "*"],
        ["char", "[]"],
    ]:
        raise NotImplementedError(
            "string handling not implemented, distinction between buffer and null-terminated strings required"
        )
        return "bytes"
    elif tokens == ["char"]:
        return "character(kind=c_char)"
    elif tokens in (["short"], ["int"], ["long"], ["long", "long"]):
        return f"integer(kind=c_{'_'.join(tokens)})"
    elif tokens in [
        ["float"],
        ["double"],
        ["long", "double"],
    ]:
        return f"real(kind=c_{'_'.join(tokens)})"
    elif tokens in [
        ["bint"],
    ]:
        return "bool"
    elif len(tokens) == 2 and tokens[0] in ("union", "struct", "enum"):
        raise NotImplementedError("struct, union, enum types are not handled")
    else:
        raise NotImplementedError(
            f"unsure how to handle type '{canonical_ctype}'"
        )


def DEFAULT_RENAMER(name):  # backend-specific
    result = name
    while result in restricted_names:
        result += "_"
    if "[]" in result:  # Fortran does not like this in certain signatures
        result = result.replace("[]", "*")
    return result


def DEFAULT_RAW_COMMENT_CLEANER(raw_comment: str):
    return raw_comment


def DEFAULT_DOXYGEN_CLEANER(doxygen: str):
    return doxygen


def DEFAULT_MACRO_TYPE(node):  # backend-specific
    return "integer(kind=c_int)"


# Utility types

LICENSE_TEXT = f"""\
{support.render_license_MIT(year_start=2021,comment_char="!")}
"""

default_module_prolog = f"""\
{LICENSE_TEXT}

! This file has been autogenerated, do not modify.
"""


class FortranMixin:
    def __init__(self):
        self.renamer = DEFAULT_RENAMER
        self.raw_comment_cleaner = lambda comment: comment
        self.sep = "_"

    @property
    def fortran_name(self):
        return self.renamer(self.name)

    @property
    def fortran_global_name(self):
        return self.renamer(self.global_name)

    def _raw_comment_cleaned(self):
        from . import tree

        assert isinstance(self, tree.Node)
        if self.raw_comment is not None:
            cleaned_raw_comment = self.raw_comment_cleaner(self.raw_comment)
            return doxyparser.remove_doxygen_comment_chars(cleaned_raw_comment)
        else:
            return ""

    def _remove_doxygen_comment_chars(self, text: str):
        return doxyparser.remove_doxygen_comment_chars(text)

    def _raw_comment_as_fortran_comment(self, comment_chars="!<"):
        from . import tree

        assert isinstance(self, tree.Node)
        if self.raw_comment is not None:
            comment = self._raw_comment_cleaned()
            return "".join(
                [
                    f"{comment_chars} " + ln
                    for ln in comment.splitlines(keepends=True)
                ]
            )
        else:
            return ""

    def render_c_bindings(self):
        """Render a Fortran interface for external C code."""
        return None


class Root(tree.Root, FortranMixin):
    def __init__(self, *args, **kwargs):
        tree.Root.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)


class Typed:
    @property
    def fortran_global_typename(self):
        from . import tree

        assert isinstance(self, tree.Typed)
        result = self.global_typename(
            self.sep, self.renamer, prefer_canonical=True
        )
        # if "[]" in result: # Fortran does not like this in signatures
        #    result = result.replace("[]", "*")
        return result

    @property
    def actual_rank(self):
        """The actual rank of the parameter, if this is an indirection."""
        return self.ptr_rank(self)

    @property
    def has_array_rank(self):
        from . import tree

        assert isinstance(self, tree.Typed)
        if self.is_any_array:
            return True
        else:
            return self.actual_rank(self)

    @property
    def is_ptr(self):
        from . import tree

        assert isinstance(self, tree.Parm)
        return self.get_pointer_degree(incomplete_array=True) > 0

    @property
    def is_indirection(self):
        """If this is not the actual value but an indirection.

        Returns:
            bool: If this is not the actual value but an indirection.
        """
        from . import tree

        actual_rank = self.ptr_rank(self)
        assert isinstance(self, tree.Parm)
        return self.get_pointer_degree() > actual_rank

    @property
    def is_out_ptr(self):
        """If this parameter has been specified as out parameter."""
        assert self.is_ptr
        return self.ptr_intent(self) == control.ParmIntent.OUT

    @property
    def is_inout_ptr(self):
        """If this is an inout parameter."""
        assert self.is_ptr
        return self.ptr_intent(self) == control.ParmIntent.INOUT

    @property
    def is_in_ptr(self):
        """If this is an inout parameter."""
        assert self.is_ptr
        return self.ptr_intent(self) == control.ParmIntent.IN

    # TODO fortran fix this
    @property
    def is_autoconverted_by_cython(self):
        from . import tree

        assert isinstance(self, tree.Typed)

        return (
            self.is_basic_type
            or self.is_basic_type_constantarray(rank=1)
            or self.is_pointer_to_char(incomplete_array=True)
        )


class Enum(tree.Enum, FortranMixin):
    # Examples:
    # enum, bind(c)
    #    enumerator :: HIP_SUCCESS = 0
    #    enumerator :: HIP_ERROR_INVALID_VALUE
    #    enumerator :: HIP_ERROR_NOT_INITIALIZED
    #    enumerator :: HIP_ERROR_LAUNCH_OUT_OF_RESOURCES
    # end enum
    #
    # enum, bind(c)
    #    enumerator :: hipMemoryTypeHost
    #    enumerator :: hipMemoryTypeDevice
    #    enumerator :: hipMemoryTypeArray
    #    enumerator :: hipMemoryTypeUnified
    # end enum

    def __init__(self, *args, **kwargs):
        tree.Enum.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)

    def _render_fortran_enums(self):
        """Yields expressions of the form '"enumerator" "::" name [ "=" value]'."""
        for child_cursor in self.cursor.get_children():
            assert isinstance(child_cursor, clang.cindex.Cursor)
            name = self.renamer(child_cursor.spelling)
            value = child_cursor.enum_value
            if value:
                yield f"enumerator :: {name} = {value}"
            else:
                yield f"enumerator ::  {name}"

    def render_c_bindings(self):
        # TODO fortran implement correctly
        global indent
        return (
            "enum, bind(c)\n"
            + textwrap.indent("\n".join(self._render_fortran_enums()), indent)
            + "\nend enum"
        )


class Parm(tree.Parm, FortranMixin, Typed):
    def __init__(self, *args, **kwargs):
        tree.Parm.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)
        self.ptr_rank = control.DEFAULT_PTR_RANK
        self.ptr_intent = control.DEFAULT_PTR_PARM_INTENT

    @property
    def fortran_c_binding_decl(self):
        """Returns the Fortran C binding declaration
        for the parameter.

        1. If the is a pointer and the parameter is no output
           parameter, adds the 'value' qualifier to pass
           the pointer value.
        2. If the type is a pointer and the parameter
           is an output parameter, do not add the 'value'
           qualifier as the pointer value must be written by the
           callee. We must pass a reference to the
           'type(c_ptr)' instance, essentially we must pass
           a `void**` pointer.
        """
        name = self.fortran_name
        if self.is_any_pointer:
            if self.ptr_intent(self) == control.ParmIntent.OUT:
                return f"type(c_ptr) :: {name}"
            else:
                return f"type(c_ptr), value :: {name}"
        else:
            return f"{C_TO_FORTRAN(self.cursor.type.get_canonical().spelling)}, value :: {name}"


class Function(tree.Function, FortranMixin, Typed):

    def __init__(self, *args, **kwargs):
        tree.Function.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)
        Typed.__init__(self)
        self.decl_list_prolog = ""

    @property
    def _has_funptr_parm(self):
        from . import tree

        assert isinstance(self, tree.Function)
        for node in self.walk():
            if isinstance(node, tree.Parm):
                if isinstance(node.typeref, tree.FunctionPointer):
                    return True
        return False

    def _fortran_retval(self, fn_name):
        """Returns"""

        typename = self.fortran_global_typename
        if self.is_void:
            return ""
        elif self.is_any_pointer:
            return f"type(c_ptr) :: {fn_name}"
        elif self.is_basic_type:
            return f"{C_TO_FORTRAN(typename)} :: {fn_name}"
        elif self.is_enum or self.is_record:
            return f"integer(kind({typename})) :: {fn_name}"
        else:
            raise NotImplementedError(
                f"cannot handle return value of type '{typename}' yet"
            )

    def render_c_bindings(self, modifiers_front="", modifiers=""):
        r"""
        Renders the C interface.

        Todos:

            * TODO add user-friendly overloads that take Fortran
              array arget and pointer variables.
            * TODO Hipify information must be made available
              to get a CUDA name. Note that hipify information should be
              supplied via codegen_hipfort.py, which uses
              `from interfacegen.support.recipes.hipify import parse_hipify_perl`.

              Implementation should however be generic in sense that
              a list of `#if` conditions plus the associated binding name
              are supplied.

        Example output:

        ```f90
        !>  \brief BLAS Level 1 API
        !>
        !>     \details
        !>     amax finds the first index of the element of maximum magnitude of a vector x.
        !>
        !>     @param[in]
        !>     handle    [hipblasHandle_t]
        !>               handle to the hipblas library context queue.
        !>     @param[in]
        !>     n         [int]
        !>               the number of elements in x.
        !>     @param[in]
        !>     x         device pointer storing vector x.
        !>     @param[in]
        !>     incx      [int]
        !>               specifies the increment for the elements of y.
        !>     @param[inout]
        !>     result
        !>               device pointer or host pointer to store the amax index.
        !>               return is 0.0 if n, incx<=0.
        interface hipblasIzamax
        #ifdef USE_CUDA_NAMES
            function hipblasIzamax_(handle,n,x,incx,myResult) bind(c, name="cublasIzamax_v2")
        #else
            function hipblasIzamax_(handle,n,x,incx,myResult) bind(c, name="hipblasIzamax")
        #endif
            use iso_c_binding
            use hipfort_hipblas_enums
            implicit none
            integer(kind(HIPBLAS_STATUS_SUCCESS)) :: hipblasIzamax_
            type(c_ptr),value :: handle
            integer(c_int),value :: n
            type(c_ptr),value :: x
            integer(c_int),value :: incx
            type(c_ptr),value :: myResult
            end function

        #ifdef USE_FPOINTER_INTERFACES
            module procedure &
            hipblasIzamax_rank_0,&
            hipblasIzamax_rank_1
        #endif
        end interface
        ```
        """
        fn_name = self.fortran_name
        binding = f"{fn_name}"
        parm_names = ",".join(parm.name for parm in self.parms)
        parm_decls = "\n".join(
            parm.fortran_c_binding_decl for parm in self.parms
        )
        retval_decl = self._fortran_retval(fn_name)

        c_binding = textwrap.dedent(
            f"""\
            function {fn_name}_({parm_names}) bind(c, name="{binding}")
              use iso_c_binding
            {{decl_list_prolog}}
              implicit none
            {{parm_decls}}
            {indent}{retval_decl}
            end function
            """
        ).format(
            decl_list_prolog=textwrap.indent(self.decl_list_prolog, indent),
            parm_decls=textwrap.indent(parm_decls, indent),
        )
        interface_members = [c_binding]
        # TODO fortran add names of user-friendly interface overloads that call
        # the C binding
        # TODO fortran add a 'contains' section that contains
        # the implementations of user-friendly interface overloads
        # that call the C binding

        declarations = textwrap.dedent(
            f"""\
            {{doxygen}}
            interface {fn_name}
            {{interface_members}}
            end interface
            """
        ).format(
            doxygen=self._raw_comment_as_fortran_comment().rstrip(),
            interface_members=textwrap.indent(
                "\n".join(interface_members), indent
            ),
        )
        implementations = None
        return declarations, implementations


class FortranBackend:

    @staticmethod
    def from_libclang_translation_unit(
        translation_unit: clang.cindex.TranslationUnit,
        filename: str,
        warn_mode: control.Warnings = control.Warnings.IGNORE,
        **opts,
    ):
        """See `FortranBackend.__init__` for further details."""
        from . import treefactory

        root = treefactory.from_libclang_translation_unit(
            backend=sys.modules[__name__],  # this module is the backend
            translation_unit=translation_unit,
            warn_mode=warn_mode,
        )
        return FortranBackend(
            root,
            filename,
            **opts,
        )

    def __init__(
        self,
        root,
        filename: str,
        util_pkg: str = "",
        node_filter: callable = control.DEFAULT_NODE_FILTER,
        macro_type: callable = DEFAULT_MACRO_TYPE,
        ptr_parm_intent: callable = control.DEFAULT_PTR_PARM_INTENT,
        ptr_rank: callable = control.DEFAULT_PTR_RANK,
        renamer: callable = DEFAULT_RENAMER,
        raw_comment_cleaner: callable = DEFAULT_RAW_COMMENT_CLEANER,
        doxygen_cleaner: callable = DEFAULT_DOXYGEN_CLEANER,
        node_init: callable = lambda node: None,
        function_preamble: str = "",
        module_preamble: str = "",
        enum_module_preamble: str = "",
    ):
        """Constructor.

        Args:
            node_filter (callable, optional):
                Filter for selecting the nodes to include in generated output. Defaults to ``lambda x: True``.
                Note that other callbacks are applied to non-filtered nodes also.
            node_init (callable, optional):
                Callback that can be used to modify certain nodes arbitrarily.
                Note that this callback is applied after all other callbacks (excluding ``node_filter``).
                Defaults to no-operation.
            macro_type (callable, optional):
                Assigns a type to a macro node. Defaults to ``lambda x: "int"``.
            ptr_parm_intent (callable, optional):
                Assigns the intent (in,out,inout,create) to a pointer-type function parameter/struct field node..
            ptr_rank (callable, optional):
                Assigns the "rank" (scalar,buffer) to a function parameter node.
            module_preamble (`str`):
                Specify the declaration section of the function-containing module.
                Defaults to empty string.
            enum_module_preamble (`str`):
                Specify the declaration section of the enum-containing module.
                Defaults to empty string.
            function_preamble (`str`):
                Additional declarations that are prepended
                to the declaration list of a function.
        Note:
            Argument 'root' has no type hint in order to prevent a circular inclusion error.
            Instead an assertion is used in the body that checks if the type is `tree.Root`.
        """
        from . import tree

        assert isinstance(root, tree.Root)
        self.root = root
        self.filename = filename
        self.util_pkg = util_pkg
        self.node_filter = node_filter
        self.macro_type = macro_type
        self.ptr_parm_intent = ptr_parm_intent
        self.ptr_rank = ptr_rank
        self.renamer = renamer
        self.raw_comment_cleaner = raw_comment_cleaner
        self.doxygen_cleaner = doxygen_cleaner
        self.node_init = node_init
        self.module_preamble = module_preamble
        self.enum_module_preamble = enum_module_preamble
        self.function_preamble = function_preamble

        self.initialize_nodes()

    def initialize_nodes(self):
        """Initializes all nodes.

        Note:
            Post-order walk, touches nested struct/union/enum declarations before their
            parent.
        """
        for node in self.root.walk(postorder=True):
            if isinstance(node, FortranMixin):
                node.sep = "_"
                node.renamer = self.renamer
                node.raw_comment_cleaner = self.raw_comment_cleaner
                if isinstance(node, Parm):
                    node.ptr_rank = self.ptr_rank
                    node.ptr_intent = self.ptr_parm_intent
                    # setattr(
                    #     node,
                    #     "ptr_complicated_type_handler",
                    #     self.ptr_complicated_type_handler,
                    # )
                elif isinstance(node, Function):
                    setattr(node, "ptr_rank", self.ptr_rank)
                    # setattr(
                    #     node,
                    #     "ptr_complicated_type_handler",
                    #     self.ptr_complicated_type_handler,
                    # )
                    # node.
                    node.decl_list_prolog = self.function_preamble
                self.node_init(node)

    def walk_filtered_nodes(self):
        """Walks the filtered nodes in post-order and sets the renamer of each node.

        Note:
            Post-order walk, touches nested struct/union/enum declarations before their
            parent.
        """
        for node in self.root.walk(postorder=True):
            if isinstance(node, FortranMixin):
                if not isinstance(node, (Parm, Root)):
                    if self.node_filter(node):
                        _log.debug(
                            f" touch {node.__class__.__name__} {node.name} from {node.cursor.kind} {node.cursor.spelling} ({node.render_location()})"
                        )
                        yield node

    def render_module(self, name, enums=False):
        """Returns the content of a Fortran bindings file.

        Creates the content of a Fortran bindings file.
        Contains Fortran declarations per C declaration
        plus helper types that have been introduced for nested enum/struct/union types.
        """
        global indent

        # Example:
        # module hipfort
        # #ifdef USE_CUDA_NAMES
        #   use hipfort_cuda_errors
        # #endif
        #   use hipfort_enums
        #   use hipfort_types
        #   use hipfort_hipmalloc
        #   use hipfort_hipmemcpy
        #   use hipfort_auxiliary
        #   implicit none
        #
        # ...
        # end module hipfort

        declarations = []
        implementations = []
        for node in self.walk_filtered_nodes():
            if isinstance(node, Enum if enums else Function):
                try:
                    contrib = node.render_c_bindings()

                    if contrib is not None:
                        if isinstance(contrib, str):  # only declarations
                            declarations.append(
                                textwrap.indent(contrib, indent)
                            )
                        elif isinstance(contrib, tuple):
                            declarations.append(
                                textwrap.indent(contrib[0], indent)
                            )
                            if contrib[1]:
                                implementations.append(
                                    textwrap.indent(contrib[1], indent)
                                )
                except (
                    NotImplementedError
                ) as err:  # TODO fortran enable more and more bindings
                    _log.warn(str(err))
        return textwrap.dedent(
            f"""\
            module {name}
            {{preamble}}
              implicit none
            {{declarations}}
            {"contains" if len(declarations) else ""}
            {{implementations}}
            end module
            """
        ).format(
            preamble=textwrap.indent(
                self.enum_module_preamble if enums else self.module_preamble,
                indent,
            ),
            declarations="\n\n".join(declarations),
            implementations="\n\n".join(implementations),
        )


class FortranModuleGenerator:
    """Generate Fortran modules for a C library.

    Generates a Fortran module from a C header file.
    """

    def __init__(
        self,
        module_name: str,
        module_ext: str,
        include_dir: str,
        header: str,
        cflags=[],
        **opts,
    ):
        r"""Constructor.

        Args:
            module_name (str):
                The Fortran module name without the Fortran file extension, e.g.,
                "mymodule" instead of "mymodule.f".
            module_ext (str):
                Module file extension to use, e.g., ".f" or ".f90".
                Defaults to ".f90".
            include_dir (str):
                Name of the main include dir.
            header (str|tuple):
                Name of the header file. Absolute paths or w.r.t. to include dir.
            cflags (list(str), optional):
                Flags to pass to the C parser.
            \*\*opts:
                Further optional keyword arguments.
                See `FortranBackend` for further details.
        """
        global default_module_prolog
        self.module_name = module_name
        self.enum_module_name = module_name + "_enums"
        self.module_ext = module_ext

        self.include_dir = include_dir
        self.header = header
        self.cflags = cflags

        if isinstance(header, str):
            filename = header
            unsaved_files = None
        elif isinstance(header, tuple):
            filename = header[0]
            unsaved_files = [header]
        else:
            raise ValueError("type of 'headers' must be str or tuple")
        _log.info(" " + filename)
        if include_dir is not None:
            abspath = os.path.join(include_dir, filename)
        else:
            abspath = filename
        cflags = self.cflags + ["-I", f"{include_dir}"]
        parser = cparser.CParser(
            abspath, append_cflags=cflags, unsaved_files=unsaved_files
        )
        parser.parse()

        self.backend: FortranBackend = (
            FortranBackend.from_libclang_translation_unit(
                parser.translation_unit, header, **opts
            )
        )

    def write_module_files(self, output_dir: str = None):
        """Write all files required to build this Fortran module.

        Args:
            module_name (str): Name of the module that should be generated. Influences filesnames.
        """

        # enums, types
        enum_module_name = f"{self.module_name}_enums"
        fileext = self.module_ext.lstrip(".")
        with open(
            f"{output_dir}/{enum_module_name}.{fileext}", "w"
        ) as outfile:
            outfile.write(default_module_prolog)
            outfile.write(
                self.backend.render_module(enum_module_name, enums=True)
            )

        # functions, other
        with open(
            f"{output_dir}/{self.module_name}.{fileext}", "w"
        ) as outfile:
            outfile.write(default_module_prolog)
            outfile.write(
                self.backend.render_module(self.module_name, enums=False)
            )
