# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.


"""
(No short description)


"""

import cython
import ctypes
import enum
# cimport (not import) is required so the with-nogil emitter can use
# the util types in `cdef` declarations — `cdef <T> name = ...` only
# works when T is visible to Cython at compile time, which means the
# defining module must be cimported. The plain Python `import` form
# would only make the names available to runtime attribute access.
cimport rocm.bindings.util.types

from rocm.bindings.llvm.c.types import LLVMMemoryBufferRef
from rocm.bindings.llvm.c.types import LLVMContextRef
from rocm.bindings.llvm.c.types import LLVMModuleRef
from rocm.bindings.llvm.c.types import LLVMTypeRef
from rocm.bindings.llvm.c.types import LLVMValueRef
from rocm.bindings.llvm.c.types import LLVMBasicBlockRef
from rocm.bindings.llvm.c.types import LLVMMetadataRef
from rocm.bindings.llvm.c.types import LLVMNamedMDNodeRef
from rocm.bindings.llvm.c.types import LLVMValueMetadataEntry
from rocm.bindings.llvm.c.types import LLVMBuilderRef
from rocm.bindings.llvm.c.types import LLVMDIBuilderRef
from rocm.bindings.llvm.c.types import LLVMModuleProviderRef
from rocm.bindings.llvm.c.types import LLVMPassManagerRef
from rocm.bindings.llvm.c.types import LLVMUseRef
from rocm.bindings.llvm.c.types import LLVMOperandBundleRef
from rocm.bindings.llvm.c.types import LLVMAttributeRef
from rocm.bindings.llvm.c.types import LLVMDiagnosticInfoRef
from rocm.bindings.llvm.c.types import LLVMComdatRef
from rocm.bindings.llvm.c.types import LLVMModuleFlagEntry
from rocm.bindings.llvm.c.types import LLVMJITEventListenerRef
from rocm.bindings.llvm.c.types import LLVMBinaryRef
from rocm.bindings.llvm.c.types import LLVMDbgRecordRef



def has_symbol(name) -> bool:
    r"""Probe whether the runtime-linked DLL exports a symbol.

    Non-raising. Lazily opens the DLL on first call (same
    resolution path as the per-symbol lazy loaders), then
    asks the loader whether the named symbol is present.
    Returns ``False`` if the DLL fails to open or the symbol
    isn't there.

    Args:
        name: Symbol name to probe (``str`` or ``bytes``).

    Returns:
        True if the symbol resolves, False otherwise.
    """
    cdef bytes name_bytes
    if isinstance(name, str):
        name_bytes = name.encode("utf-8")
    elif isinstance(name, (bytes, bytearray)):
        name_bytes = bytes(name)
    else:
        raise TypeError("name must be str, bytes, or bytearray")
    return cybitwriter.__bitwriter_has_symbol(<const char*>name_bytes)


@cython.embedsignature(True)
def LLVMWriteBitcodeToFile(object M, object Path):
    r"""Writes a module to the specified path. Returns 0 on success.

    Args:
        M (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        Path (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        int LLVMWriteBitcodeToFile(LLVMModuleRef M, const char * Path)
    """
    cdef rocm.bindings.util.types.Pointer _cy_LLVMWriteBitcodeToFile__arg_0_obj = rocm.bindings.util.types.Pointer.fromPyobj(M)
    cdef cybitwriter.LLVMModuleRef _cy_LLVMWriteBitcodeToFile__arg_0 = <cybitwriter.LLVMModuleRef>_cy_LLVMWriteBitcodeToFile__arg_0_obj.getPtr()
    cdef rocm.bindings.util.types.CStr _cy_LLVMWriteBitcodeToFile__arg_1_obj = rocm.bindings.util.types.CStr.fromPyobj(Path)
    cdef const char * _cy_LLVMWriteBitcodeToFile__arg_1 = <const char *>_cy_LLVMWriteBitcodeToFile__arg_1_obj.getPtr()
    cdef int _cy_LLVMWriteBitcodeToFile__retval
    with nogil:
        _cy_LLVMWriteBitcodeToFile__retval = cybitwriter.LLVMWriteBitcodeToFile(_cy_LLVMWriteBitcodeToFile__arg_0,_cy_LLVMWriteBitcodeToFile__arg_1)
    return _cy_LLVMWriteBitcodeToFile__retval


@cython.embedsignature(True)
def LLVMWriteBitcodeToFD(object M, int FD, int ShouldClose, int Unbuffered):
    r"""Writes a module to an open file descriptor. Returns 0 on success.

    Args:
        M (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        FD (:py:obj:`~.int`):
            (undocumented)

        ShouldClose (:py:obj:`~.int`):
            (undocumented)

        Unbuffered (:py:obj:`~.int`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        int LLVMWriteBitcodeToFD(LLVMModuleRef M, int FD, int ShouldClose, int Unbuffered)
    """
    cdef rocm.bindings.util.types.Pointer _cy_LLVMWriteBitcodeToFD__arg_0_obj = rocm.bindings.util.types.Pointer.fromPyobj(M)
    cdef cybitwriter.LLVMModuleRef _cy_LLVMWriteBitcodeToFD__arg_0 = <cybitwriter.LLVMModuleRef>_cy_LLVMWriteBitcodeToFD__arg_0_obj.getPtr()
    cdef int _cy_LLVMWriteBitcodeToFD__retval
    with nogil:
        _cy_LLVMWriteBitcodeToFD__retval = cybitwriter.LLVMWriteBitcodeToFD(_cy_LLVMWriteBitcodeToFD__arg_0,FD,ShouldClose,Unbuffered)
    return _cy_LLVMWriteBitcodeToFD__retval


@cython.embedsignature(True)
def LLVMWriteBitcodeToFileHandle(object M, int Handle):
    r"""Deprecated for LLVMWriteBitcodeToFD.

    Writes a module to an open file
    descriptor. Returns 0 on success. Closes the Handle.

    Args:
        M (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        Handle (:py:obj:`~.int`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        int LLVMWriteBitcodeToFileHandle(LLVMModuleRef M, int Handle)
    """
    cdef rocm.bindings.util.types.Pointer _cy_LLVMWriteBitcodeToFileHandle__arg_0_obj = rocm.bindings.util.types.Pointer.fromPyobj(M)
    cdef cybitwriter.LLVMModuleRef _cy_LLVMWriteBitcodeToFileHandle__arg_0 = <cybitwriter.LLVMModuleRef>_cy_LLVMWriteBitcodeToFileHandle__arg_0_obj.getPtr()
    cdef int _cy_LLVMWriteBitcodeToFileHandle__retval
    with nogil:
        _cy_LLVMWriteBitcodeToFileHandle__retval = cybitwriter.LLVMWriteBitcodeToFileHandle(_cy_LLVMWriteBitcodeToFileHandle__arg_0,Handle)
    return _cy_LLVMWriteBitcodeToFileHandle__retval


@cython.embedsignature(True)
def LLVMWriteBitcodeToMemoryBuffer(object M):
    r"""Writes a module to a new memory buffer and returns it.

    Args:
        M (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMMemoryBufferRef LLVMWriteBitcodeToMemoryBuffer(LLVMModuleRef M)
    """
    cdef rocm.bindings.util.types.Pointer _cy_LLVMWriteBitcodeToMemoryBuffer__arg_0_obj = rocm.bindings.util.types.Pointer.fromPyobj(M)
    cdef cybitwriter.LLVMModuleRef _cy_LLVMWriteBitcodeToMemoryBuffer__arg_0 = <cybitwriter.LLVMModuleRef>_cy_LLVMWriteBitcodeToMemoryBuffer__arg_0_obj.getPtr()
    cdef cybitwriter.LLVMMemoryBufferRef _cy_LLVMWriteBitcodeToMemoryBuffer__retval
    with nogil:
        _cy_LLVMWriteBitcodeToMemoryBuffer__retval = cybitwriter.LLVMWriteBitcodeToMemoryBuffer(_cy_LLVMWriteBitcodeToMemoryBuffer__arg_0)
    return None if _cy_LLVMWriteBitcodeToMemoryBuffer__retval == NULL else LLVMOpaqueMemoryBuffer.fromPtr(_cy_LLVMWriteBitcodeToMemoryBuffer__retval)

__all__ = [
    "LLVMWriteBitcodeToFile",
    "LLVMWriteBitcodeToFD",
    "LLVMWriteBitcodeToFileHandle",
    "LLVMWriteBitcodeToMemoryBuffer",
    "has_symbol",
]