# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.

cimport rocm.bindings.util.loader as loader
cdef void* _lib_handle = NULL

cdef bytes _dll_path = b""  # Cached path, computed on first access

cdef int __init() except 1 nogil:
    global _dll_path, _lib_handle
    cdef char* dll = NULL
    if _lib_handle == NULL:
        with gil:
            # Lazy path resolution - only happens on first function call
            if not _dll_path:
                from rocm.bindings.util.paths import get_library_path
                _dll_path = get_library_path('LLVM')
            dll = _dll_path
        return loader.open_library(&_lib_handle, dll)
    return 0

cdef int __init_symbol(void** result, const char* name) except 1 nogil:
    global _lib_handle
    cdef int init_result = 0
    if _lib_handle == NULL:
        init_result = __init()
        if init_result > 0:
            return init_result
    if result[0] == NULL:
        return loader.load_symbol(result,_lib_handle, name)
    return 0

cdef bint __bitreader_has_symbol(const char* name) noexcept nogil:
    # Non-raising symbol-presence probe. Lazy-loads the DLL
    # the same way __init_symbol does, then asks the loader
    # whether the symbol exists. Returns False on any DLL
    # open failure or missing symbol — never raises. Used by
    # the python-visible `has_symbol(name)` wrapper in the
    # high-level module.
    global _lib_handle
    cdef int init_result = 0
    if _lib_handle == NULL:
        with gil:
            try:
                init_result = __init()
            except Exception:
                return False
        if init_result > 0:
            return False
    return loader.has_symbol(_lib_handle, name)


cdef void* _LLVMParseBitcode__funptr = NULL
# 
# @defgroup LLVMCBitReader Bit Reader
# @ingroup LLVMC
#
cdef int LLVMParseBitcode(LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutModule,char ** OutMessage) except? -1 nogil:
    global _LLVMParseBitcode__funptr
    if __init_symbol(&_LLVMParseBitcode__funptr,"LLVMParseBitcode") > 0:
        return -1
    return (<int (*)(LLVMMemoryBufferRef,LLVMModuleRef *,char **) noexcept nogil> _LLVMParseBitcode__funptr)(MemBuf,OutModule,OutMessage)


cdef void* _LLVMParseBitcode2__funptr = NULL
cdef int LLVMParseBitcode2(LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutModule) except? -1 nogil:
    global _LLVMParseBitcode2__funptr
    if __init_symbol(&_LLVMParseBitcode2__funptr,"LLVMParseBitcode2") > 0:
        return -1
    return (<int (*)(LLVMMemoryBufferRef,LLVMModuleRef *) noexcept nogil> _LLVMParseBitcode2__funptr)(MemBuf,OutModule)


cdef void* _LLVMParseBitcodeInContext__funptr = NULL
cdef int LLVMParseBitcodeInContext(LLVMContextRef ContextRef,LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutModule,char ** OutMessage) except? -1 nogil:
    global _LLVMParseBitcodeInContext__funptr
    if __init_symbol(&_LLVMParseBitcodeInContext__funptr,"LLVMParseBitcodeInContext") > 0:
        return -1
    return (<int (*)(LLVMContextRef,LLVMMemoryBufferRef,LLVMModuleRef *,char **) noexcept nogil> _LLVMParseBitcodeInContext__funptr)(ContextRef,MemBuf,OutModule,OutMessage)


cdef void* _LLVMParseBitcodeInContext2__funptr = NULL
cdef int LLVMParseBitcodeInContext2(LLVMContextRef ContextRef,LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutModule) except? -1 nogil:
    global _LLVMParseBitcodeInContext2__funptr
    if __init_symbol(&_LLVMParseBitcodeInContext2__funptr,"LLVMParseBitcodeInContext2") > 0:
        return -1
    return (<int (*)(LLVMContextRef,LLVMMemoryBufferRef,LLVMModuleRef *) noexcept nogil> _LLVMParseBitcodeInContext2__funptr)(ContextRef,MemBuf,OutModule)


cdef void* _LLVMGetBitcodeModuleInContext__funptr = NULL
# Reads a module from the specified path, returning via the OutMP parameter
# a module provider which performs lazy deserialization. Returns 0 on success.
# Optionally returns a human-readable error message via OutMessage.
# This is deprecated. Use LLVMGetBitcodeModuleInContext2.
cdef int LLVMGetBitcodeModuleInContext(LLVMContextRef ContextRef,LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutM,char ** OutMessage) except? -1 nogil:
    global _LLVMGetBitcodeModuleInContext__funptr
    if __init_symbol(&_LLVMGetBitcodeModuleInContext__funptr,"LLVMGetBitcodeModuleInContext") > 0:
        return -1
    return (<int (*)(LLVMContextRef,LLVMMemoryBufferRef,LLVMModuleRef *,char **) noexcept nogil> _LLVMGetBitcodeModuleInContext__funptr)(ContextRef,MemBuf,OutM,OutMessage)


cdef void* _LLVMGetBitcodeModuleInContext2__funptr = NULL
#  Reads a module from the given memory buffer, returning via the OutMP
# parameter a module provider which performs lazy deserialization.
# 
# Returns 0 on success.
# 
# Takes ownership of \p MemBuf if (and only if) the module was read
# successfully.
cdef int LLVMGetBitcodeModuleInContext2(LLVMContextRef ContextRef,LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutM) except? -1 nogil:
    global _LLVMGetBitcodeModuleInContext2__funptr
    if __init_symbol(&_LLVMGetBitcodeModuleInContext2__funptr,"LLVMGetBitcodeModuleInContext2") > 0:
        return -1
    return (<int (*)(LLVMContextRef,LLVMMemoryBufferRef,LLVMModuleRef *) noexcept nogil> _LLVMGetBitcodeModuleInContext2__funptr)(ContextRef,MemBuf,OutM)


cdef void* _LLVMGetBitcodeModule__funptr = NULL
cdef int LLVMGetBitcodeModule(LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutM,char ** OutMessage) except? -1 nogil:
    global _LLVMGetBitcodeModule__funptr
    if __init_symbol(&_LLVMGetBitcodeModule__funptr,"LLVMGetBitcodeModule") > 0:
        return -1
    return (<int (*)(LLVMMemoryBufferRef,LLVMModuleRef *,char **) noexcept nogil> _LLVMGetBitcodeModule__funptr)(MemBuf,OutM,OutMessage)


cdef void* _LLVMGetBitcodeModule2__funptr = NULL
cdef int LLVMGetBitcodeModule2(LLVMMemoryBufferRef MemBuf,LLVMModuleRef * OutM) except? -1 nogil:
    global _LLVMGetBitcodeModule2__funptr
    if __init_symbol(&_LLVMGetBitcodeModule2__funptr,"LLVMGetBitcodeModule2") > 0:
        return -1
    return (<int (*)(LLVMMemoryBufferRef,LLVMModuleRef *) noexcept nogil> _LLVMGetBitcodeModule2__funptr)(MemBuf,OutM)
