# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.

cimport rocm.bindings.util.loader as loader
cdef void* _lib_handle = NULL

cdef bytes _dll_path = b""  # Cached path, computed on first access

cdef int __init() except 1 nogil:
    global _dll_path, _lib_handle
    cdef char* dll = NULL
    if _lib_handle == NULL:
        with gil:
            # Lazy path resolution - only happens on first function call
            if not _dll_path:
                from rocm.bindings.util.paths import get_library_path
                _dll_path = get_library_path('LLVM')
            dll = _dll_path
        return loader.open_library(&_lib_handle, dll)
    return 0

cdef int __init_symbol(void** result, const char* name) except 1 nogil:
    global _lib_handle
    cdef int init_result = 0
    if _lib_handle == NULL:
        init_result = __init()
        if init_result > 0:
            return init_result
    if result[0] == NULL:
        return loader.load_symbol(result,_lib_handle, name)
    return 0

cdef bint __datatypes_has_symbol(const char* name) noexcept nogil:
    # Non-raising symbol-presence probe. Lazy-loads the DLL
    # the same way __init_symbol does, then asks the loader
    # whether the symbol exists. Returns False on any DLL
    # open failure or missing symbol — never raises. Used by
    # the python-visible `has_symbol(name)` wrapper in the
    # high-level module.
    global _lib_handle
    cdef int init_result = 0
    if _lib_handle == NULL:
        with gil:
            try:
                init_result = __init()
            except Exception:
                return False
        if init_result > 0:
            return False
    return loader.has_symbol(_lib_handle, name)
