# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.


"""
(No short description)


"""

import cython
import ctypes
import enum
# cimport (not import) is required so the with-nogil emitter can use
# the util types in `cdef` declarations — `cdef <T> name = ...` only
# works when T is visible to Cython at compile time, which means the
# defining module must be cimported. The plain Python `import` form
# would only make the names available to runtime attribute access.
cimport rocm.bindings.util.types
def has_symbol(name) -> bool:
    r"""Probe whether the runtime-linked DLL exports a symbol.

    Non-raising. Lazily opens the DLL on first call (same
    resolution path as the per-symbol lazy loaders), then
    asks the loader whether the named symbol is present.
    Returns ``False`` if the DLL fails to open or the symbol
    isn't there.

    Args:
        name: Symbol name to probe (``str`` or ``bytes``).

    Returns:
        True if the symbol resolves, False otherwise.
    """
    cdef bytes name_bytes
    if isinstance(name, str):
        name_bytes = name.encode("utf-8")
    elif isinstance(name, (bytes, bytearray)):
        name_bytes = bytes(name)
    else:
        raise TypeError("name must be str, bytes, or bytearray")
    return cydeprecated.__deprecated_has_symbol(<const char*>name_bytes)




__all__ = [
    "has_symbol",
]