# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.

from libc cimport stdlib
from libc cimport string
from libc.stdint cimport *
cimport cpython.long
cimport cpython.buffer
ctypedef bint _Bool # bool is not a reserved keyword in C, _Bool is
cimport rocm.bindings.util.types



cimport rocm.bindings.util.types
cimport rocm.bindings.llvm.c.cydisassemblertypes as cydisassemblertypes

cdef class LLVMDisasmContextRef(rocm.bindings.util.types.Pointer): pass

cdef class LLVMOpInfoCallback(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cydisassemblertypes.LLVMOpInfoCallback getElementPtr(self)

    @staticmethod
    cdef LLVMOpInfoCallback fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef LLVMOpInfoCallback fromPyobj(object pyobj)


cdef class LLVMOpInfoSymbol1(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cydisassemblertypes.LLVMOpInfoSymbol1* getElementPtr(self)

    @staticmethod
    cdef LLVMOpInfoSymbol1 fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef LLVMOpInfoSymbol1 fromPyobj(object pyobj)
    @staticmethod
    cdef __allocate(void* ptr)
    @staticmethod
    cdef LLVMOpInfoSymbol1 new()
    @staticmethod
    cdef LLVMOpInfoSymbol1 fromValue(cydisassemblertypes.LLVMOpInfoSymbol1 other)


cdef class LLVMOpInfo1(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cydisassemblertypes.LLVMOpInfo1* getElementPtr(self)

    @staticmethod
    cdef LLVMOpInfo1 fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef LLVMOpInfo1 fromPyobj(object pyobj)
    @staticmethod
    cdef __allocate(void* ptr)
    @staticmethod
    cdef LLVMOpInfo1 new()
    @staticmethod
    cdef LLVMOpInfo1 fromValue(cydisassemblertypes.LLVMOpInfo1 other)


cdef class LLVMSymbolLookupCallback(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cydisassemblertypes.LLVMSymbolLookupCallback getElementPtr(self)

    @staticmethod
    cdef LLVMSymbolLookupCallback fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef LLVMSymbolLookupCallback fromPyobj(object pyobj)
