# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.


"""
(No short description)


"""

import cython
import ctypes
import enum
# cimport (not import) is required so the with-nogil emitter can use
# the util types in `cdef` declarations — `cdef <T> name = ...` only
# works when T is visible to Cython at compile time, which means the
# defining module must be cimported. The plain Python `import` form
# would only make the names available to runtime attribute access.
cimport rocm.bindings.util.types



from rocm.bindings.llvm.c.types import LLVMMemoryBufferRef
from rocm.bindings.llvm.c.types import LLVMContextRef
from rocm.bindings.llvm.c.types import LLVMModuleRef
from rocm.bindings.llvm.c.types import LLVMTypeRef
from rocm.bindings.llvm.c.types import LLVMValueRef
from rocm.bindings.llvm.c.types import LLVMBasicBlockRef
from rocm.bindings.llvm.c.types import LLVMMetadataRef
from rocm.bindings.llvm.c.types import LLVMNamedMDNodeRef
from rocm.bindings.llvm.c.types import LLVMValueMetadataEntry
from rocm.bindings.llvm.c.types import LLVMBuilderRef
from rocm.bindings.llvm.c.types import LLVMDIBuilderRef
from rocm.bindings.llvm.c.types import LLVMModuleProviderRef
from rocm.bindings.llvm.c.types import LLVMPassManagerRef
from rocm.bindings.llvm.c.types import LLVMUseRef
from rocm.bindings.llvm.c.types import LLVMOperandBundleRef
from rocm.bindings.llvm.c.types import LLVMAttributeRef
from rocm.bindings.llvm.c.types import LLVMDiagnosticInfoRef
from rocm.bindings.llvm.c.types import LLVMComdatRef
from rocm.bindings.llvm.c.types import LLVMModuleFlagEntry
from rocm.bindings.llvm.c.types import LLVMJITEventListenerRef
from rocm.bindings.llvm.c.types import LLVMBinaryRef
from rocm.bindings.llvm.c.types import LLVMDbgRecordRef



def has_symbol(name) -> bool:
    r"""Probe whether the runtime-linked DLL exports a symbol.

    Non-raising. Lazily opens the DLL on first call (same
    resolution path as the per-symbol lazy loaders), then
    asks the loader whether the named symbol is present.
    Returns ``False`` if the DLL fails to open or the symbol
    isn't there.

    Args:
        name: Symbol name to probe (``str`` or ``bytes``).

    Returns:
        True if the symbol resolves, False otherwise.
    """
    cdef bytes name_bytes
    if isinstance(name, str):
        name_bytes = name.encode("utf-8")
    elif isinstance(name, (bytes, bytearray)):
        name_bytes = bytes(name)
    else:
        raise TypeError("name must be str, bytes, or bytearray")
    return cysupport.__support_has_symbol(<const char*>name_bytes)


@cython.embedsignature(True)
def LLVMLoadLibraryPermanently(object Filename):
    r"""This function permanently loads the dynamic library at the given path.

    It is safe to call this function multiple times for the same library.

    See:
        sys::DynamicLibrary::LoadLibraryPermanently()

    Args:
        Filename (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMLoadLibraryPermanently(const char * Filename)
    """
    cdef rocm.bindings.util.types.CStr _cy_LLVMLoadLibraryPermanently__arg_0_obj = rocm.bindings.util.types.CStr.fromPyobj(Filename)
    cdef const char * _cy_LLVMLoadLibraryPermanently__arg_0 = <const char *>_cy_LLVMLoadLibraryPermanently__arg_0_obj.getPtr()
    cdef int _LLVMLoadLibraryPermanently__retval = cysupport.LLVMLoadLibraryPermanently(_cy_LLVMLoadLibraryPermanently__arg_0)
    return _LLVMLoadLibraryPermanently__retval


@cython.embedsignature(True)
def LLVMParseCommandLineOptions(int argc, object argv, object Overview):
    r"""This function parses the given arguments using the LLVM command line parser.

    Note that the only stable thing about this function is its signature; you
    cannot rely on any particular set of command line arguments being interpreted
    the same way across LLVM versions.

    See:
        llvm::cl::ParseCommandLineOptions()

    Args:
        argc (:py:obj:`~.int`):
            (undocumented)

        argv (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        Overview (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMParseCommandLineOptions(int argc, const char *const * argv, const char * Overview)
    """
    cdef rocm.bindings.util.types.Pointer _cy_LLVMParseCommandLineOptions__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(argv)
    cdef const char *const * _cy_LLVMParseCommandLineOptions__arg_1 = <const char *const *>_cy_LLVMParseCommandLineOptions__arg_1_obj.getPtr()
    cdef rocm.bindings.util.types.CStr _cy_LLVMParseCommandLineOptions__arg_2_obj = rocm.bindings.util.types.CStr.fromPyobj(Overview)
    cdef const char * _cy_LLVMParseCommandLineOptions__arg_2 = <const char *>_cy_LLVMParseCommandLineOptions__arg_2_obj.getPtr()
    cysupport.LLVMParseCommandLineOptions(argc,_cy_LLVMParseCommandLineOptions__arg_1,_cy_LLVMParseCommandLineOptions__arg_2)


@cython.embedsignature(True)
def LLVMSearchForAddressOfSymbol(object symbolName):
    r"""This function will search through all previously loaded dynamic
    libraries for the symbol ``symbolName.`` If it is found, the address of
    that symbol is returned.

    If not, null is returned.

    See:
        sys::DynamicLibrary::SearchForAddressOfSymbol()

    Args:
        symbolName (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void * LLVMSearchForAddressOfSymbol(const char * symbolName)
    """
    cdef rocm.bindings.util.types.CStr _cy_LLVMSearchForAddressOfSymbol__arg_0_obj = rocm.bindings.util.types.CStr.fromPyobj(symbolName)
    cdef const char * _cy_LLVMSearchForAddressOfSymbol__arg_0 = <const char *>_cy_LLVMSearchForAddressOfSymbol__arg_0_obj.getPtr()
    _LLVMSearchForAddressOfSymbol__retval = rocm.bindings.util.types.Pointer.fromPtr(<void*>cysupport.LLVMSearchForAddressOfSymbol(_cy_LLVMSearchForAddressOfSymbol__arg_0))
    return None if _LLVMSearchForAddressOfSymbol__retval._ptr == NULL else _LLVMSearchForAddressOfSymbol__retval


@cython.embedsignature(True)
def LLVMAddSymbol(object symbolName, object symbolValue):
    r"""This functions permanently adds the symbol ``symbolName`` with the
    value ``symbolValue.``  These symbols are searched before any
    libraries.

    See:
        sys::DynamicLibrary::AddSymbol()

    Args:
        symbolName (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

        symbolValue (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMAddSymbol(const char * symbolName, void * symbolValue)
    """
    cdef rocm.bindings.util.types.CStr _cy_LLVMAddSymbol__arg_0_obj = rocm.bindings.util.types.CStr.fromPyobj(symbolName)
    cdef const char * _cy_LLVMAddSymbol__arg_0 = <const char *>_cy_LLVMAddSymbol__arg_0_obj.getPtr()
    cdef rocm.bindings.util.types.Pointer _cy_LLVMAddSymbol__arg_1_obj = rocm.bindings.util.types.Pointer.fromPyobj(symbolValue)
    cdef void * _cy_LLVMAddSymbol__arg_1 = <void *>_cy_LLVMAddSymbol__arg_1_obj.getPtr()
    cysupport.LLVMAddSymbol(_cy_LLVMAddSymbol__arg_0,_cy_LLVMAddSymbol__arg_1)

__all__ = [
    "LLVMLoadLibraryPermanently",
    "LLVMParseCommandLineOptions",
    "LLVMSearchForAddressOfSymbol",
    "LLVMAddSymbol",
    "has_symbol",
]