# AUTO-GENERATED by the hip-python code generator.
# Type stubs for rocm.bindings.llvm.c.targetmachine. Edits will be overwritten.

import enum
import rocm.bindings.util.types
from typing import Any

def has_symbol(name: str | bytes | bytearray) -> bool: ...

class LLVMOpaqueTargetMachineOptions(rocm.bindings.util.types.Pointer):
    r"""(No short description)
    """
    def __init__(self, *args, **kwargs): ...

LLVMTargetMachineOptionsRef = LLVMOpaqueTargetMachineOptions

class LLVMOpaqueTargetMachine(rocm.bindings.util.types.Pointer):
    r"""(No short description)
    """
    def __init__(self, *args, **kwargs): ...

LLVMTargetMachineRef = LLVMOpaqueTargetMachine

class LLVMTarget(rocm.bindings.util.types.Pointer):
    r"""(No short description)
    """
    def __init__(self, *args, **kwargs): ...

LLVMTargetRef = LLVMTarget

class LLVMCodeGenOptLevel(enum.IntEnum):
    r"""(No short description)
    """
    LLVMCodeGenLevelNone: int
    LLVMCodeGenLevelLess: int
    LLVMCodeGenLevelDefault: int
    LLVMCodeGenLevelAggressive: int

class LLVMRelocMode(enum.IntEnum):
    r"""(No short description)
    """
    LLVMRelocDefault: int
    LLVMRelocStatic: int
    LLVMRelocPIC: int
    LLVMRelocDynamicNoPic: int
    LLVMRelocROPI: int
    LLVMRelocRWPI: int
    LLVMRelocROPI_RWPI: int

class LLVMCodeModel(enum.IntEnum):
    r"""(No short description)
    """
    LLVMCodeModelDefault: int
    LLVMCodeModelJITDefault: int
    LLVMCodeModelTiny: int
    LLVMCodeModelSmall: int
    LLVMCodeModelKernel: int
    LLVMCodeModelMedium: int
    LLVMCodeModelLarge: int

class LLVMCodeGenFileType(enum.IntEnum):
    r"""(No short description)
    """
    LLVMAssemblyFile: int
    LLVMObjectFile: int

class LLVMGlobalISelAbortMode(enum.IntEnum):
    r"""(No short description)
    """
    LLVMGlobalISelAbortEnable: int
    LLVMGlobalISelAbortDisable: int
    LLVMGlobalISelAbortDisableWithDiag: int

def LLVMGetFirstTarget():
    r"""Returns the first llvm::Target in the registered targets list.

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetRef LLVMGetFirstTarget()
    """
    ...

def LLVMGetNextTarget(T):
    r"""Returns the next llvm::Target given a previous one (or null if there's none)

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetRef LLVMGetNextTarget(LLVMTargetRef T)
    """
    ...

def LLVMGetTargetFromName(Name):
    r"""Finds the target corresponding to the given name and stores it in ``T.``
    Returns 0 on success.

    Args:
        Name (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetRef LLVMGetTargetFromName(const char * Name)
    """
    ...

def LLVMGetTargetFromTriple(Triple):
    r"""Finds the target corresponding to the given triple and stores it in ``T.``
    Returns 0 on success.

    Optionally returns any error in ErrorMessage.
    Use LLVMDisposeMessage to dispose the message.

    Args:
        Triple (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        A :py:obj:`~.tuple` of size 3 that contains (in that order):

        * :py:obj:`~.int`: (undocumented)
        * T (:py:obj:`~.LLVMTarget`):
            (undocumented)
        * ErrorMessage (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMGetTargetFromTriple(const char * Triple, LLVMTargetRef * T, char ** ErrorMessage)
    """
    ...

def LLVMGetTargetName(T):
    r"""Returns the name of a target. See llvm::Target::getName

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        const char * LLVMGetTargetName(LLVMTargetRef T)
    """
    ...

def LLVMGetTargetDescription(T):
    r"""Returns the description  of a target. See llvm::Target::getDescription

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        const char * LLVMGetTargetDescription(LLVMTargetRef T)
    """
    ...

def LLVMTargetHasJIT(T):
    r"""Returns if the target has a JIT

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMTargetHasJIT(LLVMTargetRef T)
    """
    ...

def LLVMTargetHasTargetMachine(T):
    r"""Returns if the target has a TargetMachine associated

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMTargetHasTargetMachine(LLVMTargetRef T)
    """
    ...

def LLVMTargetHasAsmBackend(T):
    r"""Returns if the target as an ASM backend (required for emitting output)

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMTargetHasAsmBackend(LLVMTargetRef T)
    """
    ...

def LLVMCreateTargetMachineOptions():
    r"""Create a new set of options for an llvm::TargetMachine.

    The returned option structure must be released with
    LLVMDisposeTargetMachineOptions() after the call to
    LLVMCreateTargetMachineWithOptions().

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetMachineOptionsRef LLVMCreateTargetMachineOptions()
    """
    ...

def LLVMDisposeTargetMachineOptions(Options):
    r"""Dispose of an LLVMTargetMachineOptionsRef instance.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMDisposeTargetMachineOptions(LLVMTargetMachineOptionsRef Options)
    """
    ...

def LLVMTargetMachineOptionsSetCPU(Options, CPU):
    r"""Dispose of an LLVMTargetMachineOptionsRef instance.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

        CPU (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMTargetMachineOptionsSetCPU(LLVMTargetMachineOptionsRef Options, const char * CPU)
    """
    ...

def LLVMTargetMachineOptionsSetFeatures(Options, Features):
    r"""Set the list of features for the target machine.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

        Features (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            a comma-separated list of features.

    .. rubric:: C signature

    .. code-block:: c

        void LLVMTargetMachineOptionsSetFeatures(LLVMTargetMachineOptionsRef Options, const char * Features)
    """
    ...

def LLVMTargetMachineOptionsSetABI(Options, ABI):
    r"""Set the list of features for the target machine.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

        ABI (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMTargetMachineOptionsSetABI(LLVMTargetMachineOptionsRef Options, const char * ABI)
    """
    ...

def LLVMTargetMachineOptionsSetCodeGenOptLevel(Options, Level):
    r"""Set the list of features for the target machine.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

        Level (:py:obj:`~.LLVMCodeGenOptLevel`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMTargetMachineOptionsSetCodeGenOptLevel(LLVMTargetMachineOptionsRef Options, LLVMCodeGenOptLevel Level)
    """
    ...

def LLVMTargetMachineOptionsSetRelocMode(Options, Reloc):
    r"""Set the list of features for the target machine.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

        Reloc (:py:obj:`~.LLVMRelocMode`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMTargetMachineOptionsSetRelocMode(LLVMTargetMachineOptionsRef Options, LLVMRelocMode Reloc)
    """
    ...

def LLVMTargetMachineOptionsSetCodeModel(Options, CodeModel):
    r"""Set the list of features for the target machine.

    Args:
        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            (undocumented)

        CodeModel (:py:obj:`~.LLVMCodeModel`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMTargetMachineOptionsSetCodeModel(LLVMTargetMachineOptionsRef Options, LLVMCodeModel CodeModel)
    """
    ...

def LLVMCreateTargetMachineWithOptions(T, Triple, Options):
    r"""Create a new llvm::TargetMachine.

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            the target to create a machine for.

        Triple (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            a triple describing the target machine.

        Options (:py:obj:`~.LLVMOpaqueTargetMachineOptions`/:py:obj:`~.object`):
            additional configuration (see
            LLVMCreateTargetMachineOptions()).

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetMachineRef LLVMCreateTargetMachineWithOptions(LLVMTargetRef T, const char * Triple, LLVMTargetMachineOptionsRef Options)
    """
    ...

def LLVMCreateTargetMachine(T, Triple, CPU, Features, Level, Reloc, CodeModel):
    r"""Creates a new llvm::TargetMachine. See llvm::Target::createTargetMachine

    Args:
        T (:py:obj:`~.LLVMTarget`/:py:obj:`~.object`):
            (undocumented)

        Triple (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

        CPU (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

        Features (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

        Level (:py:obj:`~.LLVMCodeGenOptLevel`):
            (undocumented)

        Reloc (:py:obj:`~.LLVMRelocMode`):
            (undocumented)

        CodeModel (:py:obj:`~.LLVMCodeModel`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetMachineRef LLVMCreateTargetMachine(LLVMTargetRef T, const char * Triple, const char * CPU, const char * Features, LLVMCodeGenOptLevel Level, LLVMRelocMode Reloc, LLVMCodeModel CodeModel)
    """
    ...

def LLVMDisposeTargetMachine(T):
    r"""Dispose the LLVMTargetMachineRef instance generated by
    LLVMCreateTargetMachine.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMDisposeTargetMachine(LLVMTargetMachineRef T)
    """
    ...

def LLVMGetTargetMachineTarget(T):
    r"""Returns the Target used in a TargetMachine

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetRef LLVMGetTargetMachineTarget(LLVMTargetMachineRef T)
    """
    ...

def LLVMGetTargetMachineTriple(T):
    r"""Returns the triple used creating this target machine.

    See
    llvm::TargetMachine::getTriple. The result needs to be disposed with
    LLVMDisposeMessage.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMGetTargetMachineTriple(LLVMTargetMachineRef T)
    """
    ...

def LLVMGetTargetMachineCPU(T):
    r"""Returns the cpu used creating this target machine.

    See
    llvm::TargetMachine::getCPU. The result needs to be disposed with
    LLVMDisposeMessage.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMGetTargetMachineCPU(LLVMTargetMachineRef T)
    """
    ...

def LLVMGetTargetMachineFeatureString(T):
    r"""Returns the feature string used creating this target machine.

    See
    llvm::TargetMachine::getFeatureString. The result needs to be disposed with
    LLVMDisposeMessage.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMGetTargetMachineFeatureString(LLVMTargetMachineRef T)
    """
    ...

def LLVMCreateTargetDataLayout(T):
    r"""Create a DataLayout based on the targetMachine.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.None`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMTargetDataRef LLVMCreateTargetDataLayout(LLVMTargetMachineRef T)
    """
    ...

def LLVMSetTargetMachineAsmVerbosity(T, VerboseAsm):
    r"""Set the target machine's ASM verbosity.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        VerboseAsm (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMSetTargetMachineAsmVerbosity(LLVMTargetMachineRef T, LLVMBool VerboseAsm)
    """
    ...

def LLVMSetTargetMachineFastISel(T, Enable):
    r"""Enable fast-path instruction selection.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        Enable (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMSetTargetMachineFastISel(LLVMTargetMachineRef T, LLVMBool Enable)
    """
    ...

def LLVMSetTargetMachineGlobalISel(T, Enable):
    r"""Enable global instruction selection.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        Enable (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMSetTargetMachineGlobalISel(LLVMTargetMachineRef T, LLVMBool Enable)
    """
    ...

def LLVMSetTargetMachineGlobalISelAbort(T, Mode):
    r"""Set abort behaviour when global instruction selection fails to lower/select
    an instruction.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        Mode (:py:obj:`~.LLVMGlobalISelAbortMode`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMSetTargetMachineGlobalISelAbort(LLVMTargetMachineRef T, LLVMGlobalISelAbortMode Mode)
    """
    ...

def LLVMSetTargetMachineMachineOutliner(T, Enable):
    r"""Enable the MachineOutliner pass.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        Enable (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMSetTargetMachineMachineOutliner(LLVMTargetMachineRef T, LLVMBool Enable)
    """
    ...

def LLVMTargetMachineEmitToFile(T, M, Filename, codegen, ErrorMessage):
    r"""Emits an asm or object file for the given module to the filename.

    This
    wraps several c++ only classes (among them a file stream). Returns any
    error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        M (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        Filename (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

        codegen (:py:obj:`~.LLVMCodeGenFileType`):
            (undocumented)

        ErrorMessage (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMTargetMachineEmitToFile(LLVMTargetMachineRef T, LLVMModuleRef M, const char * Filename, LLVMCodeGenFileType codegen, char ** ErrorMessage)
    """
    ...

def LLVMTargetMachineEmitToMemoryBuffer(T, M, codegen, ErrorMessage, OutMemBuf):
    r"""Compile the LLVM IR stored in ``M`` and store the result in ``OutMemBuf.``

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        M (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        codegen (:py:obj:`~.LLVMCodeGenFileType`):
            (undocumented)

        ErrorMessage (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

        OutMemBuf (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.int`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        LLVMBool LLVMTargetMachineEmitToMemoryBuffer(LLVMTargetMachineRef T, LLVMModuleRef M, LLVMCodeGenFileType codegen, char ** ErrorMessage, LLVMMemoryBufferRef * OutMemBuf)
    """
    ...

def LLVMGetDefaultTargetTriple():
    r"""Get a triple for the host machine as a string.

    The result needs to be
    disposed with LLVMDisposeMessage.

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMGetDefaultTargetTriple()
    """
    ...

def LLVMNormalizeTargetTriple(triple):
    r"""Normalize a target triple.

    The result needs to be disposed with
    LLVMDisposeMessage.

    Args:
        triple (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`):
            (undocumented)

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMNormalizeTargetTriple(const char * triple)
    """
    ...

def LLVMGetHostCPUName():
    r"""Get the host CPU as a string.

    The result needs to be disposed with
    LLVMDisposeMessage.

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMGetHostCPUName()
    """
    ...

def LLVMGetHostCPUFeatures():
    r"""Get the host CPU's features as a string.

    The result needs to be disposed
    with LLVMDisposeMessage.

    Returns:
        :py:obj:`~.bytes`: (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        char * LLVMGetHostCPUFeatures()
    """
    ...

def LLVMAddAnalysisPasses(T, PM):
    r"""Adds the target-specific analysis passes to the pass manager.

    Args:
        T (:py:obj:`~.LLVMOpaqueTargetMachine`/:py:obj:`~.object`):
            (undocumented)

        PM (:py:obj:`~.rocm.bindings.util.types.Pointer`/:py:obj:`~.object`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void LLVMAddAnalysisPasses(LLVMTargetMachineRef T, LLVMPassManagerRef PM)
    """
    ...

__all__ = [
    'LLVMAddAnalysisPasses',
    'LLVMCodeGenFileType',
    'LLVMCodeGenOptLevel',
    'LLVMCodeModel',
    'LLVMCreateTargetDataLayout',
    'LLVMCreateTargetMachine',
    'LLVMCreateTargetMachineOptions',
    'LLVMCreateTargetMachineWithOptions',
    'LLVMDisposeTargetMachine',
    'LLVMDisposeTargetMachineOptions',
    'LLVMGetDefaultTargetTriple',
    'LLVMGetFirstTarget',
    'LLVMGetHostCPUFeatures',
    'LLVMGetHostCPUName',
    'LLVMGetNextTarget',
    'LLVMGetTargetDescription',
    'LLVMGetTargetFromName',
    'LLVMGetTargetFromTriple',
    'LLVMGetTargetMachineCPU',
    'LLVMGetTargetMachineFeatureString',
    'LLVMGetTargetMachineTarget',
    'LLVMGetTargetMachineTriple',
    'LLVMGetTargetName',
    'LLVMGlobalISelAbortMode',
    'LLVMNormalizeTargetTriple',
    'LLVMOpaqueTargetMachine',
    'LLVMOpaqueTargetMachineOptions',
    'LLVMRelocMode',
    'LLVMSetTargetMachineAsmVerbosity',
    'LLVMSetTargetMachineFastISel',
    'LLVMSetTargetMachineGlobalISel',
    'LLVMSetTargetMachineGlobalISelAbort',
    'LLVMSetTargetMachineMachineOutliner',
    'LLVMTarget',
    'LLVMTargetHasAsmBackend',
    'LLVMTargetHasJIT',
    'LLVMTargetHasTargetMachine',
    'LLVMTargetMachineEmitToFile',
    'LLVMTargetMachineEmitToMemoryBuffer',
    'LLVMTargetMachineOptionsRef',
    'LLVMTargetMachineOptionsSetABI',
    'LLVMTargetMachineOptionsSetCPU',
    'LLVMTargetMachineOptionsSetCodeGenOptLevel',
    'LLVMTargetMachineOptionsSetCodeModel',
    'LLVMTargetMachineOptionsSetFeatures',
    'LLVMTargetMachineOptionsSetRelocMode',
    'LLVMTargetMachineRef',
    'LLVMTargetRef',
    'has_symbol',
]
