# MIT License
#
# Copyright (c) 2024-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Unified hip-python code generator.

Produces Cython sources for the four generator-owned packages of hip-python:
  - rocm-bindings-hip
  - rocm-bindings-libraries
  - rocm-bindings-compiler
  - hip-python-interop

Output scope is strictly Cython sources (`.pxd`/`.pyx`), namespace package
markers (`__init__.pxd`) below `rocm/bindings/` and `cuda/bindings/`, and
CMake module-list/version include files (`cmake/generated_modules.cmake`,
`cmake/generated_versions.cmake`). NO Python-packaging files are produced —
those (handcoded `__init__.py`, `_version.py.in`, `pyproject.toml`,
`setup.py`, etc.) live in the hip-python repo as the source of truth.
See plan §B.7 and §A.1.
"""

import argparse
import os
import sys
from pathlib import Path

from interfacegen.support import gitversion

from .hip import generate_hip
from .llvm import generate_llvm
from .comgr import generate_comgr


# Map recipe name -> generate(opts) callable.
RECIPE_GENERATORS = {
    "hip":   generate_hip.generate,
    "llvm":  generate_llvm.generate,
    "comgr": generate_comgr.generate,
}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_unified_args(argv=None):
    p = argparse.ArgumentParser(
        prog="hip_python.codegen",
        description=(
            "Unified hip-python code generator. Produces Cython sources for "
            "rocm-bindings-{hip,libraries,compiler} and hip-python-interop."
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    p.add_argument(
        "output_dir",
        help=(
            "Root of the hip-python repo. The generator writes into "
            "<output_dir>/python/<package>/..."
        ),
    )
    p.add_argument("--rocm-version", required=True, help="ROCm version (e.g. 7.13.0)")
    p.add_argument("--rocm-path", default=os.environ.get("ROCM_PATH", "/opt/rocm"))
    p.add_argument("--platform", default="amd", choices=["amd", "nvidia"])
    p.add_argument("--clang-resource-dir", default=None)
    p.add_argument(
        "--recipes",
        default="hip,llvm,comgr",
        help="Comma-separated subset of {hip,llvm,comgr}",
    )
    p.add_argument(
        "--hip-libs",
        default="*",
        help="HIP library subset, e.g. 'hip,hiprtc,hipblas' or '*' or '^excludes'",
    )
    p.add_argument("--llvm-libs", default="*")
    p.add_argument("--comgr-libs", default="*")
    p.add_argument(
        "--no-rt-linking", action="store_true",
        help="Disable runtime linking; bind against the named shared libraries directly.",
    )
    p.add_argument("--license-path", default=None)
    p.add_argument(
        "--generator-args", nargs="*", default=[],
        help="Extra args passed through to libclang.",
    )
    args = p.parse_args(argv)
    args.runtime_linking = not args.no_rt_linking
    args.recipes = [r.strip() for r in args.recipes.split(",") if r.strip()]
    for r in args.recipes:
        if r not in RECIPE_GENERATORS:
            p.error(f"unknown recipe '{r}'; pick from {list(RECIPE_GENERATORS)}")
    return args


# ---------------------------------------------------------------------------
# Cross-cutting emission: namespace markers + CMake module/version lists
# ---------------------------------------------------------------------------

NAMESPACE_MARKER_BODY = (
    "# Cython namespace package marker — build-time only, not installed.\n"
    "# Auto-generated by the hip-python code generator.\n"
)


def write_namespace_markers(opts, recipe_results):
    """Drop `__init__.pxd` into every generator-created subdirectory.

    Top-of-namespace markers (`rocm/__init__.pxd`, `rocm/bindings/__init__.pxd`,
    `cuda/__init__.pxd`, `cuda/bindings/__init__.pxd`) are HANDCODED in the
    hip-python repo and not touched here (plan §A.1).

    This pass walks each generator-owned subtree (everything strictly below
    `rocm/bindings/` and `cuda/bindings/`) and writes a marker into each
    directory that contains a `.pxd` or `.pyx` but no `__init__.py` /
    `__init__.pxd` yet.
    """
    package_roots = [
        os.path.join(opts.output_dir, "python", "rocm-bindings-hip", "rocm", "bindings"),
        os.path.join(opts.output_dir, "python", "rocm-bindings-libraries", "rocm", "bindings"),
        os.path.join(opts.output_dir, "python", "rocm-bindings-compiler", "rocm", "bindings"),
        os.path.join(opts.output_dir, "python", "hip-python-interop", "cuda", "bindings"),
    ]
    for root in package_roots:
        if not os.path.isdir(root):
            continue
        # First pass: identify every directory that ends up containing a
        # .pxd/.pyx (directly or via a descendant). Then emit __init__.pxd
        # at every such directory below `root` (top-of-namespace is
        # handcoded — skip `root` itself).
        dirs_needing_marker = set()
        for dirpath, _dirnames, filenames in os.walk(root):
            if any(fn.endswith((".pxd", ".pyx")) for fn in filenames):
                cur = dirpath
                while cur != root and cur != os.path.dirname(cur):
                    dirs_needing_marker.add(cur)
                    cur = os.path.dirname(cur)
        for dirpath in dirs_needing_marker:
            existing = os.listdir(dirpath)
            if "__init__.py" in existing or "__init__.pxd" in existing:
                continue
            marker = os.path.join(dirpath, "__init__.pxd")
            with open(marker, "w") as f:
                f.write(NAMESPACE_MARKER_BODY)


def write_cmake_module_lists(opts, recipe_results):
    """Write per-package `cmake/generated_modules.cmake` files.

    Module lists come from each subgenerator's return value:
      - libraries:  comes from the HIP recipe's hip_modules excluding the
                    handcoded core (hip, hiprtc) and helper (_hip_helpers,
                    _hiprtc_helpers) modules. NOTE: today the libraries
                    list is hand-curated; this function preserves the
                    existing list when the HIP recipe didn't run.
      - compiler:   union of llvm_modules and comgr_modules from the LLVM
                    and COMGR recipes.
    """
    # rocm-bindings-libraries
    hip_result = recipe_results.get("hip")
    if hip_result is not None:
        libs = hip_result.get("libraries_modules") or []
        path = os.path.join(
            opts.output_dir, "python", "rocm-bindings-libraries", "cmake",
            "generated_modules.cmake",
        )
        Path(os.path.dirname(path)).mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(_AUTOGEN_HEADER)
            f.write(f"set(HIP_PYTHON_LIBRARIES_GENERATED_MODULES\n    {' '.join(libs)})\n")

    # rocm-bindings-compiler
    llvm_modules = recipe_results.get("llvm", {}).get("llvm_modules") or []
    comgr_modules = recipe_results.get("comgr", {}).get("comgr_modules") or []
    if llvm_modules or comgr_modules:
        path = os.path.join(
            opts.output_dir, "python", "rocm-bindings-compiler", "cmake",
            "generated_modules.cmake",
        )
        Path(os.path.dirname(path)).mkdir(parents=True, exist_ok=True)
        # Subdivide LLVM modules by their on-disk subdirectory.
        c_modules, transforms_modules, config_modules = [], [], []
        compiler_root = os.path.join(
            opts.output_dir, "python", "rocm-bindings-compiler", "rocm", "bindings", "llvm",
        )
        for m in llvm_modules:
            # llvm_modules is a list of py_global_name strings like
            # "rocm.bindings.llvm.c.core" — bucket by the subpath.
            parts = m.split(".")
            try:
                idx = parts.index("llvm")
            except ValueError:
                continue
            tail = parts[idx + 1:]  # e.g. ["c", "core"], ["c", "transforms", "passbuilder"]
            if not tail:
                continue
            leaf = tail[-1]
            if "transforms" in tail:
                transforms_modules.append(leaf)
            elif "config" in tail:
                config_modules.append(leaf)
            elif "c" in tail:
                c_modules.append(leaf)
        with open(path, "w") as f:
            f.write(_AUTOGEN_HEADER)
            for var, lst in (
                ("HIP_PYTHON_LLVM_C_MODULES", c_modules),
                ("HIP_PYTHON_LLVM_C_TRANSFORMS_MODULES", transforms_modules),
                ("HIP_PYTHON_LLVM_CONFIG_MODULES", config_modules),
                ("HIP_PYTHON_COMGR_MODULES", [m.split(".")[-1] for m in comgr_modules]),
            ):
                f.write(f"set({var}\n    {' '.join(lst)})\n\n")


def write_cmake_version_files(opts, recipe_results):
    """Write per-package `cmake/generated_versions.cmake` (plan §B.7)."""
    rocm_version = opts.rocm_version
    hip_version = recipe_results.get("hip", {}).get("hip_version")
    if hip_version:
        major, minor, patch, githash = hip_version
        hip_version_str = f"{major}.{minor}.{patch}-{githash}" if githash else f"{major}.{minor}.{patch}"
    else:
        hip_version_str = ""
    try:
        codegen_branch = gitversion.git_current_branch()
        codegen_rev = gitversion.git_rev()
        codegen_version = gitversion.version(append_hash=True, append_date=True)
    except Exception:
        codegen_branch = codegen_rev = codegen_version = ""
    body = (
        _AUTOGEN_HEADER
        + f'set(HIP_PYTHON_GENERATED_ROCM_VERSION    "{rocm_version}")\n'
        + f'set(HIP_PYTHON_GENERATED_HIP_VERSION     "{hip_version_str}")\n'
        + f'set(HIP_PYTHON_GENERATED_CODEGEN_BRANCH  "{codegen_branch}")\n'
        + f'set(HIP_PYTHON_GENERATED_CODEGEN_REV     "{codegen_rev}")\n'
        + f'set(HIP_PYTHON_GENERATED_CODEGEN_VERSION "{codegen_version}")\n'
    )
    for pkg in ("rocm-bindings-hip", "rocm-bindings-libraries",
                "rocm-bindings-compiler", "hip-python-interop"):
        path = os.path.join(opts.output_dir, "python", pkg, "cmake", "generated_versions.cmake")
        Path(os.path.dirname(path)).mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(body)


_AUTOGEN_HEADER = (
    "# AUTO-GENERATED by the hip-python code generator. Do not edit by hand.\n"
)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(argv=None):
    opts = parse_unified_args(argv)
    recipe_results = {}
    for recipe in opts.recipes:
        result = RECIPE_GENERATORS[recipe](opts) or {}
        recipe_results[recipe] = result
    write_namespace_markers(opts, recipe_results)
    write_cmake_module_lists(opts, recipe_results)
    write_cmake_version_files(opts, recipe_results)


if __name__ == "__main__":
    sys.exit(main())
