#include "/opt/rocm/llvm/include/llvm-c/Analysis.h"
#include "/opt/rocm/llvm/include/llvm-c/BitReader.h"
#include "/opt/rocm/llvm/include/llvm-c/BitWriter.h"
//#include "/opt/rocm/llvm/include/llvm-c/blake3.h"
//#include "/opt/rocm/llvm/include/llvm-c/Comdat.h"
//#include "/opt/rocm/llvm/include/llvm-c/Core.h" // breaks
//#include "/opt/rocm/llvm/include/llvm-c/DataTypes.h" // breaks, "child_nodes"
#include "/opt/rocm/llvm/include/llvm-c/DebugInfo.h"
//#include "/opt/rocm/llvm/include/llvm-c/Deprecated.h"
#include "/opt/rocm/llvm/include/llvm-c/Disassembler.h" 
#include "/opt/rocm/llvm/include/llvm-c/DisassemblerTypes.h"
//#include "/opt/rocm/llvm/include/llvm-c/Error.h"  // breaks "is_union"
#include "/opt/rocm/llvm/include/llvm-c/ErrorHandling.h"
//#include "/opt/rocm/llvm/include/llvm-c/ExecutionEngine.h" // breaks
//#include "/opt/rocm/llvm/include/llvm-c/ExternC.h"
//#include "/opt/rocm/llvm/include/llvm-c/Initialization.h"
#include "/opt/rocm/llvm/include/llvm-c/IRReader.h"
#include "/opt/rocm/llvm/include/llvm-c/Linker.h"
//#include "/opt/rocm/llvm/include/llvm-c/LLJIT.h" // breaks "is_union"
//#include "/opt/rocm/llvm/include/llvm-c/lto.h" // breaks "must be present in parent's child_nodes"
//#include "/opt/rocm/llvm/include/llvm-c/Object.h" // breaks "is_union"
//#include "/opt/rocm/llvm/include/llvm-c/Orc.h" // breaks, assertion "not implemented"
//#include "/opt/rocm/llvm/include/llvm-c/OrcEE.h"
//#include "/opt/rocm/llvm/include/llvm-c/Remarks.h"
//#include "/opt/rocm/llvm/include/llvm-c/Support.h" // breaks, "is_union"
//#include "/opt/rocm/llvm/include/llvm-c/Target.h" // breaks, "is_union"
//#include "/opt/rocm/llvm/include/llvm-c/TargetMachine.h" /root/code/AIST/projects/hip_python/interfacegen/recipes/python_cython/llvmc/codegen_llvmc.py
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/InstCombine.h"
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/IPO.h"
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/PassBuilder.h"
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/PassManagerBuilder.h"
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/Scalar.h"
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/Utils.h"
//#include "/opt/rocm/llvm/include/llvm-c/Transforms/Vectorize.h"
#include "/opt/rocm/llvm/include/llvm-c/Types.h"
