! MIT License
!
! Copyright (c) 2021-2024 Advanced Micro Devices, Inc.
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.



! This file has been autogenerated, do not modify.
module hipfort_amdsmi_enums

    implicit none
  enum, bind(c)
    enumerator ::  P_ALL
    enumerator :: P_PID = 1
    enumerator :: P_PGID = 2
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_INIT_ALL_PROCESSORS
    enumerator :: AMDSMI_INIT_AMD_CPUS = 1
    enumerator :: AMDSMI_INIT_AMD_GPUS = 2
    enumerator :: AMDSMI_INIT_NON_AMD_CPUS = 4
    enumerator :: AMDSMI_INIT_NON_AMD_GPUS = 8
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_MM_UVD
    enumerator :: AMDSMI_MM_VCE = 1
    enumerator :: AMDSMI_MM_VCN = 2
    enumerator :: AMDSMI_MM__MAX = 3
  end enum

  enum, bind(c)
    enumerator ::  CONTAINER_LXC
    enumerator :: CONTAINER_DOCKER = 1
  end enum

  enum, bind(c)
    enumerator ::  UNKNOWN
    enumerator :: AMD_GPU = 1
    enumerator :: AMD_CPU = 2
    enumerator :: NON_AMD_GPU = 3
    enumerator :: NON_AMD_CPU = 4
    enumerator :: AMD_CPU_CORE = 5
    enumerator :: AMD_APU = 6
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_STATUS_SUCCESS
    enumerator :: AMDSMI_STATUS_INVAL = 1
    enumerator :: AMDSMI_STATUS_NOT_SUPPORTED = 2
    enumerator :: AMDSMI_STATUS_NOT_YET_IMPLEMENTED = 3
    enumerator :: AMDSMI_STATUS_FAIL_LOAD_MODULE = 4
    enumerator :: AMDSMI_STATUS_FAIL_LOAD_SYMBOL = 5
    enumerator :: AMDSMI_STATUS_DRM_ERROR = 6
    enumerator :: AMDSMI_STATUS_API_FAILED = 7
    enumerator :: AMDSMI_STATUS_TIMEOUT = 8
    enumerator :: AMDSMI_STATUS_RETRY = 9
    enumerator :: AMDSMI_STATUS_NO_PERM = 10
    enumerator :: AMDSMI_STATUS_INTERRUPT = 11
    enumerator :: AMDSMI_STATUS_IO = 12
    enumerator :: AMDSMI_STATUS_ADDRESS_FAULT = 13
    enumerator :: AMDSMI_STATUS_FILE_ERROR = 14
    enumerator :: AMDSMI_STATUS_OUT_OF_RESOURCES = 15
    enumerator :: AMDSMI_STATUS_INTERNAL_EXCEPTION = 16
    enumerator :: AMDSMI_STATUS_INPUT_OUT_OF_BOUNDS = 17
    enumerator :: AMDSMI_STATUS_INIT_ERROR = 18
    enumerator :: AMDSMI_STATUS_REFCOUNT_OVERFLOW = 19
    enumerator :: AMDSMI_STATUS_BUSY = 30
    enumerator :: AMDSMI_STATUS_NOT_FOUND = 31
    enumerator :: AMDSMI_STATUS_NOT_INIT = 32
    enumerator :: AMDSMI_STATUS_NO_SLOT = 33
    enumerator :: AMDSMI_STATUS_DRIVER_NOT_LOADED = 34
    enumerator :: AMDSMI_STATUS_NO_DATA = 40
    enumerator :: AMDSMI_STATUS_INSUFFICIENT_SIZE = 41
    enumerator :: AMDSMI_STATUS_UNEXPECTED_SIZE = 42
    enumerator :: AMDSMI_STATUS_UNEXPECTED_DATA = 43
    enumerator :: AMDSMI_STATUS_NON_AMD_CPU = 44
    enumerator :: AMDSMI_NO_ENERGY_DRV = 45
    enumerator :: AMDSMI_NO_MSR_DRV = 46
    enumerator :: AMDSMI_NO_HSMP_DRV = 47
    enumerator :: AMDSMI_NO_HSMP_SUP = 48
    enumerator :: AMDSMI_NO_HSMP_MSG_SUP = 49
    enumerator :: AMDSMI_HSMP_TIMEOUT = 50
    enumerator :: AMDSMI_NO_DRV = 51
    enumerator :: AMDSMI_FILE_NOT_FOUND = 52
    enumerator :: AMDSMI_ARG_PTR_NULL = 53
    enumerator :: AMDSMI_STATUS_AMDGPU_RESTART_ERR = 54
    enumerator :: AMDSMI_STATUS_SETTING_UNAVAILABLE = 55
    enumerator :: AMDSMI_STATUS_MAP_ERROR = 4294967294
    enumerator :: AMDSMI_STATUS_UNKNOWN_ERROR = 4294967295
  end enum

  enum, bind(c)
    enumerator ::  CLK_TYPE_SYS
    enumerator ::  CLK_TYPE_FIRST
    enumerator ::  CLK_TYPE_GFX
    enumerator :: CLK_TYPE_DF = 1
    enumerator :: CLK_TYPE_DCEF = 2
    enumerator :: CLK_TYPE_SOC = 3
    enumerator :: CLK_TYPE_MEM = 4
    enumerator :: CLK_TYPE_PCIE = 5
    enumerator :: CLK_TYPE_VCLK0 = 6
    enumerator :: CLK_TYPE_VCLK1 = 7
    enumerator :: CLK_TYPE_DCLK0 = 8
    enumerator :: CLK_TYPE_DCLK1 = 9
    enumerator :: CLK_TYPE__MAX = 9
  end enum

  enum, bind(c)
    enumerator ::  COMPUTE_PARTITION_INVALID
    enumerator :: COMPUTE_PARTITION_CPX = 1
    enumerator :: COMPUTE_PARTITION_SPX = 2
    enumerator :: COMPUTE_PARTITION_DPX = 3
    enumerator :: COMPUTE_PARTITION_TPX = 4
    enumerator :: COMPUTE_PARTITION_QPX = 5
  end enum

  enum, bind(c)
    enumerator ::  MEMORY_PARTITION_UNKNOWN
    enumerator :: MEMORY_PARTITION_NPS1 = 1
    enumerator :: MEMORY_PARTITION_NPS2 = 2
    enumerator :: MEMORY_PARTITION_NPS4 = 3
    enumerator :: MEMORY_PARTITION_NPS8 = 4
  end enum

  enum, bind(c)
    enumerator ::  TEMPERATURE_TYPE_EDGE
    enumerator ::  TEMPERATURE_TYPE_FIRST
    enumerator :: TEMPERATURE_TYPE_HOTSPOT = 1
    enumerator :: TEMPERATURE_TYPE_JUNCTION = 1
    enumerator :: TEMPERATURE_TYPE_VRAM = 2
    enumerator :: TEMPERATURE_TYPE_HBM_0 = 3
    enumerator :: TEMPERATURE_TYPE_HBM_1 = 4
    enumerator :: TEMPERATURE_TYPE_HBM_2 = 5
    enumerator :: TEMPERATURE_TYPE_HBM_3 = 6
    enumerator :: TEMPERATURE_TYPE_PLX = 7
    enumerator :: TEMPERATURE_TYPE__MAX = 7
  end enum

  enum, bind(c)
    enumerator :: FW_ID_SMU = 1
    enumerator :: FW_ID_FIRST = 1
    enumerator :: FW_ID_CP_CE = 2
    enumerator :: FW_ID_CP_PFP = 3
    enumerator :: FW_ID_CP_ME = 4
    enumerator :: FW_ID_CP_MEC_JT1 = 5
    enumerator :: FW_ID_CP_MEC_JT2 = 6
    enumerator :: FW_ID_CP_MEC1 = 7
    enumerator :: FW_ID_CP_MEC2 = 8
    enumerator :: FW_ID_RLC = 9
    enumerator :: FW_ID_SDMA0 = 10
    enumerator :: FW_ID_SDMA1 = 11
    enumerator :: FW_ID_SDMA2 = 12
    enumerator :: FW_ID_SDMA3 = 13
    enumerator :: FW_ID_SDMA4 = 14
    enumerator :: FW_ID_SDMA5 = 15
    enumerator :: FW_ID_SDMA6 = 16
    enumerator :: FW_ID_SDMA7 = 17
    enumerator :: FW_ID_VCN = 18
    enumerator :: FW_ID_UVD = 19
    enumerator :: FW_ID_VCE = 20
    enumerator :: FW_ID_ISP = 21
    enumerator :: FW_ID_DMCU_ERAM = 22
    enumerator :: FW_ID_DMCU_ISR = 23
    enumerator :: FW_ID_RLC_RESTORE_LIST_GPM_MEM = 24
    enumerator :: FW_ID_RLC_RESTORE_LIST_SRM_MEM = 25
    enumerator :: FW_ID_RLC_RESTORE_LIST_CNTL = 26
    enumerator :: FW_ID_RLC_V = 27
    enumerator :: FW_ID_MMSCH = 28
    enumerator :: FW_ID_PSP_SYSDRV = 29
    enumerator :: FW_ID_PSP_SOSDRV = 30
    enumerator :: FW_ID_PSP_TOC = 31
    enumerator :: FW_ID_PSP_KEYDB = 32
    enumerator :: FW_ID_DFC = 33
    enumerator :: FW_ID_PSP_SPL = 34
    enumerator :: FW_ID_DRV_CAP = 35
    enumerator :: FW_ID_MC = 36
    enumerator :: FW_ID_PSP_BL = 37
    enumerator :: FW_ID_CP_PM4 = 38
    enumerator :: FW_ID_RLC_P = 39
    enumerator :: FW_ID_SEC_POLICY_STAGE2 = 40
    enumerator :: FW_ID_REG_ACCESS_WHITELIST = 41
    enumerator :: FW_ID_IMU_DRAM = 42
    enumerator :: FW_ID_IMU_IRAM = 43
    enumerator :: FW_ID_SDMA_TH0 = 44
    enumerator :: FW_ID_SDMA_TH1 = 45
    enumerator :: FW_ID_CP_MES = 46
    enumerator :: FW_ID_MES_KIQ = 47
    enumerator :: FW_ID_MES_STACK = 48
    enumerator :: FW_ID_MES_THREAD1 = 49
    enumerator :: FW_ID_MES_THREAD1_STACK = 50
    enumerator :: FW_ID_RLX6 = 51
    enumerator :: FW_ID_RLX6_DRAM_BOOT = 52
    enumerator :: FW_ID_RS64_ME = 53
    enumerator :: FW_ID_RS64_ME_P0_DATA = 54
    enumerator :: FW_ID_RS64_ME_P1_DATA = 55
    enumerator :: FW_ID_RS64_PFP = 56
    enumerator :: FW_ID_RS64_PFP_P0_DATA = 57
    enumerator :: FW_ID_RS64_PFP_P1_DATA = 58
    enumerator :: FW_ID_RS64_MEC = 59
    enumerator :: FW_ID_RS64_MEC_P0_DATA = 60
    enumerator :: FW_ID_RS64_MEC_P1_DATA = 61
    enumerator :: FW_ID_RS64_MEC_P2_DATA = 62
    enumerator :: FW_ID_RS64_MEC_P3_DATA = 63
    enumerator :: FW_ID_PPTABLE = 64
    enumerator :: FW_ID_PSP_SOC = 65
    enumerator :: FW_ID_PSP_DBG = 66
    enumerator :: FW_ID_PSP_INTF = 67
    enumerator :: FW_ID_RLX6_CORE1 = 68
    enumerator :: FW_ID_RLX6_DRAM_BOOT_CORE1 = 69
    enumerator :: FW_ID_RLCV_LX7 = 70
    enumerator :: FW_ID_RLC_SAVE_RESTORE_LIST = 71
    enumerator :: FW_ID_ASD = 72
    enumerator :: FW_ID_TA_RAS = 73
    enumerator :: FW_ID_TA_XGMI = 74
    enumerator :: FW_ID_RLC_SRLG = 75
    enumerator :: FW_ID_RLC_SRLS = 76
    enumerator :: FW_ID_PM = 77
    enumerator :: FW_ID_DMCU = 78
    enumerator :: FW_ID__MAX = 79
  end enum

  enum, bind(c)
    enumerator ::  VRAM_TYPE_UNKNOWN
    enumerator :: VRAM_TYPE_GDDR1 = 1
    enumerator :: VRAM_TYPE_DDR2 = 2
    enumerator :: VRAM_TYPE_GDDR3 = 3
    enumerator :: VRAM_TYPE_GDDR4 = 4
    enumerator :: VRAM_TYPE_GDDR5 = 5
    enumerator :: VRAM_TYPE_HBM = 6
    enumerator :: VRAM_TYPE_DDR3 = 7
    enumerator :: VRAM_TYPE_DDR4 = 8
    enumerator :: VRAM_TYPE_GDDR6 = 9
    enumerator :: VRAM_TYPE__MAX = 9
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_VRAM_VENDOR__PLACEHOLDER0
    enumerator :: AMDSMI_VRAM_VENDOR__SAMSUNG = 1
    enumerator :: AMDSMI_VRAM_VENDOR__INFINEON = 2
    enumerator :: AMDSMI_VRAM_VENDOR__ELPIDA = 3
    enumerator :: AMDSMI_VRAM_VENDOR__ETRON = 4
    enumerator :: AMDSMI_VRAM_VENDOR__NANYA = 5
    enumerator :: AMDSMI_VRAM_VENDOR__HYNIX = 6
    enumerator :: AMDSMI_VRAM_VENDOR__MOSEL = 7
    enumerator :: AMDSMI_VRAM_VENDOR__WINBOND = 8
    enumerator :: AMDSMI_VRAM_VENDOR__ESMT = 9
    enumerator :: AMDSMI_VRAM_VENDOR__PLACEHOLDER1 = 10
    enumerator :: AMDSMI_VRAM_VENDOR__PLACEHOLDER2 = 11
    enumerator :: AMDSMI_VRAM_VENDOR__PLACEHOLDER3 = 12
    enumerator :: AMDSMI_VRAM_VENDOR__PLACEHOLDER4 = 13
    enumerator :: AMDSMI_VRAM_VENDOR__PLACEHOLDER5 = 14
    enumerator :: AMDSMI_VRAM_VENDOR__MICRON = 15
  end enum

  enum, bind(c)
    enumerator :: CACHE_FLAGS_ENABLED = 1
    enumerator :: CACHE_FLAGS_DATA_CACHE = 2
    enumerator :: CACHE_FLAGS_INST_CACHE = 4
    enumerator :: CACHE_FLAGS_CPU_CACHE = 8
    enumerator :: CACHE_FLAGS_SIMD_CACHE = 16
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_DEV_PERF_LEVEL_AUTO
    enumerator ::  AMDSMI_DEV_PERF_LEVEL_FIRST
    enumerator :: AMDSMI_DEV_PERF_LEVEL_LOW = 1
    enumerator :: AMDSMI_DEV_PERF_LEVEL_HIGH = 2
    enumerator :: AMDSMI_DEV_PERF_LEVEL_MANUAL = 3
    enumerator :: AMDSMI_DEV_PERF_LEVEL_STABLE_STD = 4
    enumerator :: AMDSMI_DEV_PERF_LEVEL_STABLE_PEAK = 5
    enumerator :: AMDSMI_DEV_PERF_LEVEL_STABLE_MIN_MCLK = 6
    enumerator :: AMDSMI_DEV_PERF_LEVEL_STABLE_MIN_SCLK = 7
    enumerator :: AMDSMI_DEV_PERF_LEVEL_DETERMINISM = 8
    enumerator :: AMDSMI_DEV_PERF_LEVEL_LAST = 8
    enumerator :: AMDSMI_DEV_PERF_LEVEL_UNKNOWN = 256
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_EVNT_GRP_XGMI
    enumerator :: AMDSMI_EVNT_GRP_XGMI_DATA_OUT = 10
    enumerator :: AMDSMI_EVNT_GRP_INVALID = 4294967295
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_EVNT_FIRST
    enumerator ::  AMDSMI_EVNT_XGMI_FIRST
    enumerator ::  AMDSMI_EVNT_XGMI_0_NOP_TX
    enumerator :: AMDSMI_EVNT_XGMI_0_REQUEST_TX = 1
    enumerator :: AMDSMI_EVNT_XGMI_0_RESPONSE_TX = 2
    enumerator :: AMDSMI_EVNT_XGMI_0_BEATS_TX = 3
    enumerator :: AMDSMI_EVNT_XGMI_1_NOP_TX = 4
    enumerator :: AMDSMI_EVNT_XGMI_1_REQUEST_TX = 5
    enumerator :: AMDSMI_EVNT_XGMI_1_RESPONSE_TX = 6
    enumerator :: AMDSMI_EVNT_XGMI_1_BEATS_TX = 7
    enumerator :: AMDSMI_EVNT_XGMI_LAST = 7
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_FIRST = 10
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_0 = 10
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_1 = 11
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_2 = 12
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_3 = 13
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_4 = 14
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_5 = 15
    enumerator :: AMDSMI_EVNT_XGMI_DATA_OUT_LAST = 15
    enumerator :: AMDSMI_EVNT_LAST = 15
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_CNTR_CMD_START
    enumerator :: AMDSMI_CNTR_CMD_STOP = 1
  end enum

  enum, bind(c)
    enumerator :: AMDSMI_EVT_NOTIF_VMFAULT = 1
    enumerator :: AMDSMI_EVT_NOTIF_FIRST = 1
    enumerator :: AMDSMI_EVT_NOTIF_THERMAL_THROTTLE = 2
    enumerator :: AMDSMI_EVT_NOTIF_GPU_PRE_RESET = 3
    enumerator :: AMDSMI_EVT_NOTIF_GPU_POST_RESET = 4
    enumerator :: AMDSMI_EVT_NOTIF_LAST = 4
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_TEMP_CURRENT
    enumerator ::  AMDSMI_TEMP_FIRST
    enumerator :: AMDSMI_TEMP_MAX = 1
    enumerator :: AMDSMI_TEMP_MIN = 2
    enumerator :: AMDSMI_TEMP_MAX_HYST = 3
    enumerator :: AMDSMI_TEMP_MIN_HYST = 4
    enumerator :: AMDSMI_TEMP_CRITICAL = 5
    enumerator :: AMDSMI_TEMP_CRITICAL_HYST = 6
    enumerator :: AMDSMI_TEMP_EMERGENCY = 7
    enumerator :: AMDSMI_TEMP_EMERGENCY_HYST = 8
    enumerator :: AMDSMI_TEMP_CRIT_MIN = 9
    enumerator :: AMDSMI_TEMP_CRIT_MIN_HYST = 10
    enumerator :: AMDSMI_TEMP_OFFSET = 11
    enumerator :: AMDSMI_TEMP_LOWEST = 12
    enumerator :: AMDSMI_TEMP_HIGHEST = 13
    enumerator :: AMDSMI_TEMP_LAST = 13
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_VOLT_CURRENT
    enumerator ::  AMDSMI_VOLT_FIRST
    enumerator :: AMDSMI_VOLT_MAX = 1
    enumerator :: AMDSMI_VOLT_MIN_CRIT = 2
    enumerator :: AMDSMI_VOLT_MIN = 3
    enumerator :: AMDSMI_VOLT_MAX_CRIT = 4
    enumerator :: AMDSMI_VOLT_AVERAGE = 5
    enumerator :: AMDSMI_VOLT_LOWEST = 6
    enumerator :: AMDSMI_VOLT_HIGHEST = 7
    enumerator :: AMDSMI_VOLT_LAST = 7
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_VOLT_TYPE_FIRST
    enumerator ::  AMDSMI_VOLT_TYPE_VDDGFX
    enumerator ::  AMDSMI_VOLT_TYPE_LAST
    enumerator :: AMDSMI_VOLT_TYPE_INVALID = 4294967295
  end enum

  enum, bind(c)
    enumerator :: AMDSMI_PWR_PROF_PRST_CUSTOM_MASK = 1
    enumerator :: AMDSMI_PWR_PROF_PRST_VIDEO_MASK = 2
    enumerator :: AMDSMI_PWR_PROF_PRST_POWER_SAVING_MASK = 4
    enumerator :: AMDSMI_PWR_PROF_PRST_COMPUTE_MASK = 8
    enumerator :: AMDSMI_PWR_PROF_PRST_VR_MASK = 16
    enumerator :: AMDSMI_PWR_PROF_PRST_3D_FULL_SCR_MASK = 32
    enumerator :: AMDSMI_PWR_PROF_PRST_BOOTUP_DEFAULT = 64
    enumerator :: AMDSMI_PWR_PROF_PRST_LAST = 64
    enumerator :: AMDSMI_PWR_PROF_PRST_INVALID = 18446744073709551615
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_GPU_BLOCK_INVALID
    enumerator :: AMDSMI_GPU_BLOCK_FIRST = 1
    enumerator :: AMDSMI_GPU_BLOCK_UMC = 1
    enumerator :: AMDSMI_GPU_BLOCK_SDMA = 2
    enumerator :: AMDSMI_GPU_BLOCK_GFX = 4
    enumerator :: AMDSMI_GPU_BLOCK_MMHUB = 8
    enumerator :: AMDSMI_GPU_BLOCK_ATHUB = 16
    enumerator :: AMDSMI_GPU_BLOCK_PCIE_BIF = 32
    enumerator :: AMDSMI_GPU_BLOCK_HDP = 64
    enumerator :: AMDSMI_GPU_BLOCK_XGMI_WAFL = 128
    enumerator :: AMDSMI_GPU_BLOCK_DF = 256
    enumerator :: AMDSMI_GPU_BLOCK_SMN = 512
    enumerator :: AMDSMI_GPU_BLOCK_SEM = 1024
    enumerator :: AMDSMI_GPU_BLOCK_MP0 = 2048
    enumerator :: AMDSMI_GPU_BLOCK_MP1 = 4096
    enumerator :: AMDSMI_GPU_BLOCK_FUSE = 8192
    enumerator :: AMDSMI_GPU_BLOCK_LAST = 8192
    enumerator :: AMDSMI_GPU_BLOCK_RESERVED = 9223372036854775808
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_RAS_ERR_STATE_NONE
    enumerator :: AMDSMI_RAS_ERR_STATE_DISABLED = 1
    enumerator :: AMDSMI_RAS_ERR_STATE_PARITY = 2
    enumerator :: AMDSMI_RAS_ERR_STATE_SING_C = 3
    enumerator :: AMDSMI_RAS_ERR_STATE_MULT_UC = 4
    enumerator :: AMDSMI_RAS_ERR_STATE_POISON = 5
    enumerator :: AMDSMI_RAS_ERR_STATE_ENABLED = 6
    enumerator :: AMDSMI_RAS_ERR_STATE_LAST = 6
    enumerator :: AMDSMI_RAS_ERR_STATE_INVALID = 4294967295
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_MEM_TYPE_FIRST
    enumerator ::  AMDSMI_MEM_TYPE_VRAM
    enumerator :: AMDSMI_MEM_TYPE_VIS_VRAM = 1
    enumerator :: AMDSMI_MEM_TYPE_GTT = 2
    enumerator :: AMDSMI_MEM_TYPE_LAST = 2
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_FREQ_IND_MIN
    enumerator :: AMDSMI_FREQ_IND_MAX = 1
    enumerator :: AMDSMI_FREQ_IND_INVALID = 4294967295
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_XGMI_STATUS_NO_ERRORS
    enumerator :: AMDSMI_XGMI_STATUS_ERROR = 1
    enumerator :: AMDSMI_XGMI_STATUS_MULTIPLE_ERRORS = 2
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_MEM_PAGE_STATUS_RESERVED
    enumerator :: AMDSMI_MEM_PAGE_STATUS_PENDING = 1
    enumerator :: AMDSMI_MEM_PAGE_STATUS_UNRESERVABLE = 2
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_IOLINK_TYPE_UNDEFINED
    enumerator :: AMDSMI_IOLINK_TYPE_PCIEXPRESS = 1
    enumerator :: AMDSMI_IOLINK_TYPE_XGMI = 2
    enumerator :: AMDSMI_IOLINK_TYPE_NUMIOLINKTYPES = 3
    enumerator :: AMDSMI_IOLINK_TYPE_SIZE = 4294967295
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_UTILIZATION_COUNTER_FIRST
    enumerator ::  AMDSMI_COARSE_GRAIN_GFX_ACTIVITY
    enumerator :: AMDSMI_COARSE_GRAIN_MEM_ACTIVITY = 1
    enumerator :: AMDSMI_UTILIZATION_COUNTER_LAST = 1
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_AVERAGE_POWER
    enumerator :: AMDSMI_CURRENT_POWER = 1
    enumerator :: AMDSMI_INVALID_POWER = 4294967295
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_REG_XGMI
    enumerator :: AMDSMI_REG_WAFL = 1
    enumerator :: AMDSMI_REG_PCIE = 2
    enumerator :: AMDSMI_REG_USR = 3
    enumerator :: AMDSMI_REG_USR1 = 4
  end enum

  enum, bind(c)
    enumerator ::  AMDSMI_SLOT_TYPE__PCIE
    enumerator :: AMDSMI_SLOT_TYPE__CEM = 1
    enumerator :: AMDSMI_SLOT_TYPE__OAM = 2
    enumerator :: AMDSMI_SLOT_TYPE__RESERVED = 3
  end enum
contains

end module
