# MIT License
#
# Copyright (c) 2024-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""The hipRTC builtin header, taken from the installed ROCm.

Compiling HIP source with AMD COMGR means supplying the declarations hipRTC
would otherwise supply itself: ``malloc`` and ``free`` for the device, the
``__ocml_*`` maths entry points, the ``nan``/``modf``/... wrappers over them.
hipRTC keeps that text inside its builtins library, ``hiprtc-builtins``, which
exports it as a pair of data symbols so its own front end can prepend it.
Reading those symbols gets the same text hipRTC itself would use.

Reading it rather than shipping a copy matters because the text is not portable
between hosts. It is generated by running clang over HIP's device headers, so
whichever machine generated it froze its own data model into the result: on
Linux ``size_t`` comes out as ``long unsigned int``, on Windows as ``long long
unsigned int``. That is not cosmetic. HIP device compilation mirrors the host
target into the device job -- the ``-aux-triple`` clang receives -- so that
host and device agree on the layout of anything passed between them, which
means a Linux-generated copy fed to a Windows compilation declares ``size_t``
as a 32-bit type and contradicts the compilation's own. ROCm builds the header
per platform and its Windows copy also drops a bitfield union that MSVC layout
rules would size differently, so the installed copy is right by construction
where a shipped one can only be right by luck.

The version follows too: the text always describes the ROCm that is installed,
not the one that was current when this package was built.

Nothing is shipped as a fallback. Earlier releases carried a generated
``hiprtc_runtime.h``, produced by ci/internal/generate-bindings.sh configuring
clr/hipamd and building its ``hiprtc-builtins`` target; that step is gone. An
install without the builtins library cannot compile HIP source through COMGR
anyway, since it has no AMD COMGR either -- the two arrive together in every
ROCm distribution, and neither is part of the GPU driver.
"""

__author__ = "Advanced Micro Devices, Inc. <hip-python.maintainer@amd.com>"

import ctypes
import os
from pathlib import Path
from typing import Optional

from rocm.bindings.util import paths as _paths

#: Shortname of the library holding the header, resolved by
#: :py:func:`rocm.bindings.util.paths.get_library_path`, which knows the
#: per-platform filenames and the tree layouts.
BUILTINS_LIBRARY_SHORTNAME = "hiprtc-builtins"

#: The exported symbols. Both are internal to hipRTC -- they appear in no
#: public header -- so a future ROCm may rename them, which is what
#: :py:data:`HEADER_PATH_ENV_VAR` exists for.
HEADER_SYMBOL = "__hipRTC_header"
HEADER_SIZE_SYMBOL = "__hipRTC_header_size"

#: Set this to a file to use that text instead of the installed library's,
#: which is the escape hatch if a future ROCm renames or drops the symbols.
HEADER_PATH_ENV_VAR = "HIP_PYTHON_HIPRTC_RUNTIME_HEADER"

# (text, origin) once resolved. The library load and an 800 KB decode are not
# worth repeating, and callers such as numba-hip ask for the text repeatedly.
_cached = None


def find_builtins_library() -> Optional[Path]:
    """Path to the ``hiprtc-builtins`` library, or `None` if there is none.

    `None` is a normal outcome: a Windows install that has only the GPU driver
    ships the HIP runtime without hipRTC.
    """
    resolved = Path(
        os.fsdecode(_paths.get_library_path(BUILTINS_LIBRARY_SHORTNAME))
    )
    # get_library_path falls back to a bare filename for the system loader to
    # resolve, which is no use here: the symbols have to be read out of a file
    # this process can name.
    if resolved.is_absolute() and resolved.is_file():
        return resolved
    return None


def read_header_from_library(library_path) -> Optional[str]:
    """The header text held by the library at ``library_path``.

    `None` if the library will not load or does not export the symbols; the
    caller turns that into a message naming the library and the symbols, which
    is more use than a ctypes error mentioning neither.
    """
    try:
        library = ctypes.CDLL(str(library_path))
    except OSError:
        return None

    try:
        size = ctypes.c_size_t.in_dll(library, HEADER_SIZE_SYMBOL).value
        # The symbol is the character array itself, not a pointer to it, so
        # take its address rather than reading a pointer out of it.
        first_char = ctypes.c_char.in_dll(library, HEADER_SYMBOL)
        raw = ctypes.string_at(ctypes.addressof(first_char), size)
    except ValueError:
        return None  # symbol not exported

    # UTF-8, not ASCII: one doc comment carries a typographic apostrophe.
    return _normalize(raw.decode("utf-8"))


def _normalize(text: str) -> str:
    """Give every source of the header the same line endings.

    ROCm's Windows copy uses CRLF. Consumers that report positions in this text
    -- numba-hip parses it with libclang and maps cursors back to lines -- should
    not have to care which platform it came from.
    """
    return text.replace("\r\n", "\n")


def get_hiprtc_runtime_header() -> str:
    """The hipRTC builtin header text from the installed ROCm.

    Raises:
        RuntimeError: if the builtins library cannot be found, will not load, or
            does not export the header.
    """
    return _resolve()[0]


def get_hiprtc_runtime_header_origin() -> str:
    """The file :py:func:`get_hiprtc_runtime_header` read the text from."""
    return _resolve()[1]


def _resolve():
    global _cached
    if _cached is not None:
        return _cached

    override = os.environ.get(HEADER_PATH_ENV_VAR)
    if override:
        text = _normalize(Path(override).read_text(encoding="utf-8"))
        _cached = (text, override)
        return _cached

    library = find_builtins_library()
    if library is None:
        raise RuntimeError(
            f"could not locate the {BUILTINS_LIBRARY_SHORTNAME} library, which "
            "holds the hipRTC builtin header that compiling HIP source needs. "
            "Point ROCM_PATH at a ROCm installation, or install the rocm-sdk "
            f"wheels. Set {HEADER_PATH_ENV_VAR} to supply the header from a "
            "file instead."
        )

    text = read_header_from_library(library)
    if text is None:
        raise RuntimeError(
            f"'{library}' does not export {HEADER_SYMBOL} and "
            f"{HEADER_SIZE_SYMBOL}, or would not load. These symbols are "
            "internal to hipRTC, so a ROCm release may rename them; set "
            f"{HEADER_PATH_ENV_VAR} to supply the header from a file instead."
        )

    _cached = (text, str(library))
    return _cached
