import _cython_3_2_4
from _typeshed import Incomplete
from typing import Any, ClassVar

__reduce_cython__: _cython_3_2_4.cython_function_or_method
__setstate_cython__: _cython_3_2_4.cython_function_or_method
__test__: dict

class CStr(Pointer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    def decode(self, encoding=..., errors=...) -> Any: ...
    def encode(self, encoding=..., errors=...) -> Any: ...
    def free(self) -> void: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def malloc(self, Py_ssize_tsize_bytes) -> void: ...
    def __bool__(self) -> bool: ...
    def __buffer__(self, *args, **kwargs): ...
    def __getitem__(self, subscript) -> Any: ...
    def __len__(self) -> int: ...
    def __reduce__(self): ...
    def __release_buffer__(self, *args, **kwargs): ...

class DeviceArray(NDBuffer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def DeviceArray(pyobj) -> Any: ...
    def __reduce__(self): ...

class ImmortalCStr(CStr):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __reduce__(self): ...

class ListOfBytes(Pointer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __reduce__(self): ...

class ListOfInt(Pointer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __reduce__(self): ...

class ListOfPointer(Pointer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __reduce__(self): ...

class ListOfUnsigned(Pointer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __reduce__(self): ...

class ListOfUnsignedLong(Pointer):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, pyobj) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __reduce__(self): ...

class NDBuffer(Pointer):
    NUMPY_CHAR_CODES: ClassVar[tuple] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    is_read_only: Incomplete
    itemsize: Incomplete
    rank: Incomplete
    shape: Incomplete
    size: Incomplete
    stream_as_int: Incomplete
    typestr: Incomplete
    def __init__(self, pyobj) -> Any: ...
    def configure(self, **kwargs) -> Any: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __buffer__(self, *args, **kwargs): ...
    def __getitem__(self, subscript) -> Any: ...
    def __reduce__(self): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Pointer:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    is_ptr_null: Incomplete
    def __init__(self, pyobj=...) -> Any: ...
    def as_c_void_p(self) -> Any: ...
    def createRef(self) -> Pointer: ...
    @staticmethod
    def fromObj(pyobj) -> Any: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, offset) -> Any: ...
    def __int__(self) -> Any: ...
    def __reduce__(self): ...
