# MIT License
#
# Copyright (c) 2024-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Sphinx page + TOC YAML emission for the hip-python codegen tool.

These writers are docs-side outputs only — they consume the same
`recipe_results` structure that `binding_generator.generate(opts)`
returns but produce restructured-text wrapper pages and a `_toc.yml.in`
file under `<output_dir>/docs_src/`.

`generate.main()` calls `write_docs_pages` and `write_toc_yml_in` after
the binding generation pass; this module does not import anything from
`binding_generator` and is independent of the per-wheel generators.
"""

import os
from pathlib import Path


_AUTOGEN_RST_HEADER = (
    ".. AUTO-GENERATED by the hip-python code generator. Do not edit by hand.\n"
)

# Bucketing of `rocm.bindings.<leaf>` modules into their owning wheel.
# MUST match `binding_generator.AVAILABLE_GENERATORS` — every entry
# whose package shortname is "hip" / "compiler" / "systems" must
# appear in the corresponding set, or both the literalinclude path
# resolution (`_module_to_pxd_relpath`) and the toc bucketing
# (`write_toc_yml_in`) silently mis-route the docs.
_HIP_CORE = {"hip", "hiprtc", "_hip_helpers", "_hiprtc_helpers"}
_COMPILER_CORE = {"amd_comgr"}
_SYSTEMS_CORE = {"rccl", "roctx", "hipfile", "amdsmi", "hsa"}


_AUTOGEN_TOC_HEADER = (
    "# AUTO-GENERATED by the hip-python code generator from\n"
    "# `_toc.yml.in.in`. Do not edit by hand.\n"
)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _module_to_pxd_relpath(opts, module_name):
    """Return the .pxd path on disk for a generated module's `cy<name>` wrapper.

    Paths are returned **relative to docs_src/** (so they fit cleanly into a
    `literalinclude` directive). `module_name` is a high-level dotted name
    like `rocm.bindings.hipblas`; the corresponding cy* wrapper lives next
    to it.
    """
    parts = module_name.split(".")
    leaf = parts[-1]
    cy_leaf = leaf if leaf.startswith("cy") else f"cy{leaf}"
    if module_name.startswith("rocm.bindings.llvm."):
        # rocm.bindings.llvm.c.core → packages/rocm-bindings-compiler/src/rocm/bindings/llvm/c/cycore.pxd
        subdir = "/".join(parts[2:-1])  # llvm/c, llvm/c/transforms, llvm/config
        rel = f"packages/rocm-bindings-compiler/src/rocm/bindings/{subdir}/{cy_leaf}.pxd"
    elif module_name.startswith("rocm.bindings."):
        # decide hip vs libraries vs systems vs compiler by leaf name
        bare = leaf[2:] if leaf.startswith("cy") else leaf
        if bare in _HIP_CORE:
            pkg = "rocm-bindings-hip"
        elif bare in _COMPILER_CORE:
            pkg = "rocm-bindings-compiler"
        elif bare in _SYSTEMS_CORE:
            pkg = "rocm-bindings-systems"
        else:
            pkg = "rocm-bindings-libraries"
        rel = f"packages/{pkg}/src/rocm/bindings/{cy_leaf}.pxd"
    elif module_name.startswith("cuda.bindings."):
        rel = f"packages/hip-python-interop/src/cuda/bindings/{cy_leaf}.pxd"
    else:
        return None
    # docs_src/python_api/<page>.rst → ../../<rel>
    return f"../../{rel}"


def _all_emitted_modules(recipe_results):
    """Collect every dotted module name produced across all subgenerators."""
    modules = []

    def _add(name):
        if name and name not in modules:
            modules.append(name)

    # `llvm` is a multi-module parent entry that appears in both
    # `hip_modules` (from `lib_names`) and `compiler_modules` (its
    # AVAILABLE_GENERATORS pkg_short is "compiler"). It has no top-level
    # cy* wrapper of its own — its real submodules surface via
    # `llvm_modules` below. Adding `rocm.bindings.llvm` from either list
    # would emit a stale literalinclude page and bucket it into the
    # wrong wheel (rocm-bindings-libraries) downstream.
    hip_result = recipe_results.get("hip") or {}
    for name in hip_result.get("hip_modules") or []:
        if name == "llvm":
            continue
        _add(f"rocm.bindings.{name}")
    # The HIP recipe also emits CUDA interop modules.
    for name in ("driver", "runtime", "nvrtc"):
        _add(f"cuda.bindings.{name}")

    # llvm modules now flow through the hip recipe's llvm_modules.
    hip_llvm = (recipe_results.get("hip") or {}).get("llvm_modules") or []
    for global_name in hip_llvm:
        # global_name is already in dotted form (rocm.bindings.llvm.c.core).
        _add(global_name)

    # comgr modules now flow through the hip recipe's compiler_modules.
    hip_compiler = (recipe_results.get("hip") or {}).get("compiler_modules") or []
    for libname in hip_compiler:
        if libname == "llvm":
            continue  # see comment above
        # `compiler_modules` is a list of library short names (e.g. "amd_comgr"),
        # so prepend the rocm.bindings namespace to match the dotted form.
        _add(f"rocm.bindings.{libname}")

    return modules


# ---------------------------------------------------------------------------
# Sphinx .rst page emission per generated module
# ---------------------------------------------------------------------------

def write_docs_pages(opts, recipe_results):
    """Emit one Sphinx .rst page per generated cy* module.

    The high-level Python modules are documented by sphinx-autoapi
    directly (it walks the source tree configured in
    ``autoapi_dirs`` and writes one ``index.rst`` per module). The
    generator therefore does NOT emit wrapper pages for them — the
    TOC (see ``write_toc_yml_in``) points at the autoapi-emitted
    paths instead. Earlier versions wrote a ``.. autoapi-module::``
    stub here, but that directive does not exist in sphinx-autoapi
    and produced empty pages.

    For each cy* C-level wrapper, this function emits a real
    ``literalinclude`` page that embeds the .pxd source with Cython
    syntax highlighting (the .pxd is the readable contract for
    downstream Cython users; cy* modules are not Python-importable
    and thus not autoapi targets).

    Cleanup: any `.rst` (or leftover `.md`) under
    ``docs_src/python_api/`` that starts with the autogen header AND
    no longer corresponds to a current cy* module is removed.
    Handcoded pages (no autogen header) are preserved.
    """
    docs_dir = os.path.join(opts.output_dir, "docs_src", "python_api")
    Path(docs_dir).mkdir(parents=True, exist_ok=True)

    high_level = _all_emitted_modules(recipe_results)
    # Only cy* pages are generator-owned now; the cleanup pass uses
    # `expected` to know which autogen-headered files to keep.
    expected = set()
    for module in high_level:
        leaf = module.rsplit(".", 1)[-1]
        if leaf.startswith("cy") or leaf.startswith("_"):
            continue
        cy_dotted = ".".join(module.rsplit(".", 1)[:-1] + [f"cy{leaf}"])
        expected.add(f"{cy_dotted}.rst")

    # Emit cy* literalinclude pages.
    for module in high_level:
        leaf = module.rsplit(".", 1)[-1]
        if leaf.startswith("_") or leaf.startswith("cy"):
            continue
        cy_dotted = ".".join(module.rsplit(".", 1)[:-1] + [f"cy{leaf}"])
        cy_underline = "=" * len(cy_dotted)
        pxd_rel = _module_to_pxd_relpath(opts, module)
        if pxd_rel is None:
            continue
        # The high-level autoapi-emitted index lives at
        # `python_api/<slash/path>/index` — link from the cy* page so
        # readers can hop to the Python API for the same module.
        autoapi_doc = "/".join(["", "python_api", *module.split("."), "index"])
        with open(os.path.join(docs_dir, f"{cy_dotted}.rst"), "w") as f:
            f.write(
                f"{_AUTOGEN_RST_HEADER}\n"
                f"{cy_dotted}\n{cy_underline}\n\n"
                f"Cython declarations for the C-level interface. Use\n"
                f"``cimport {cy_dotted}`` from your Cython code to access\n"
                f"these declarations directly.\n\n"
                f".. seealso::\n\n"
                f"   The high-level Python API is documented at "
                f":doc:`{autoapi_doc}`.\n\n"
                f".. literalinclude:: {pxd_rel}\n"
                f"   :language: cython\n"
            )

    # Cleanup pass: remove autogen pages whose module is no longer
    # present, including the legacy ``<dotted>.rst`` wrappers from the
    # broken-`.. autoapi-module::` era.
    for fn in os.listdir(docs_dir):
        if fn in expected:
            continue
        if not (fn.endswith(".rst") or fn.endswith(".md")):
            continue
        path = os.path.join(docs_dir, fn)
        try:
            with open(path) as f:
                head = f.read(len(_AUTOGEN_RST_HEADER) * 2)
        except OSError:
            continue
        if _AUTOGEN_RST_HEADER.strip() in head or "<!-- AUTO-GENERATED" in head:
            try:
                os.remove(path)
            except OSError:
                pass


def write_toc_yml_in(opts, recipe_results):
    """Render `_toc.yml.in.in` → `_toc.yml.in` with discovered modules.

    The handcoded template at `<output_dir>/docs_src/sphinx/_toc.yml.in.in`
    contains a `@TOC_ENTRIES_<SECTION>@` placeholder per generator-owned
    subtree (rocm-bindings-{hip,libraries,compiler}, hip-python-interop,
    cython-level). This pass substitutes each placeholder with the
    discovered TOC entries.

    High-level modules point at the autoapi-emitted index path
    (``python_api/<slash/path>/index``); cy* modules keep the dotted
    form because they are real generator-emitted literalinclude pages
    (see ``write_docs_pages``).

    Handcoded subtrees (User Guide, rocm-bindings-core, hip compat shim,
    Manual API) are listed inline in the template and left unchanged.
    """
    template_path = os.path.join(
        opts.output_dir, "docs_src", "sphinx", "_toc.yml.in.in"
    )
    output_path = os.path.join(
        opts.output_dir, "docs_src", "sphinx", "_toc.yml.in"
    )
    if not os.path.exists(template_path):
        return  # template missing; skip silently (e.g. truncated checkout)

    # Bucket every emitted module into its TOC section.
    sections = {
        "ROCM_BINDINGS_HIP": [],
        "ROCM_BINDINGS_LIBRARIES": [],
        "ROCM_BINDINGS_SYSTEMS": [],
        "ROCM_BINDINGS_COMPILER": [],
        "HIP_PYTHON_INTEROP": [],
        "CYTHON_LEVEL": [],
    }
    # llvm.c.* and llvm.config.* pages are nested under a single
    # collapsible parent entry in COMPILER (see assembly below) so the
    # 30+ submodules don't dominate the sidebar.
    llvm_children = []
    for module in _all_emitted_modules(recipe_results):
        leaf = module.rsplit(".", 1)[-1]
        if leaf.startswith("_"):
            continue  # handcoded helpers
        autoapi_path = "/".join(["python_api", *module.split("."), "index"])
        if module.startswith("rocm.bindings.llvm."):
            llvm_children.append(autoapi_path)
            section = None  # nested separately below
        elif module.startswith("rocm.bindings."):
            bare = leaf[2:] if leaf.startswith("cy") else leaf
            if bare in _HIP_CORE:
                section = "ROCM_BINDINGS_HIP"
            elif bare in _COMPILER_CORE:
                section = "ROCM_BINDINGS_COMPILER"
            elif bare in _SYSTEMS_CORE:
                section = "ROCM_BINDINGS_SYSTEMS"
            else:
                section = "ROCM_BINDINGS_LIBRARIES"
        elif module.startswith("cuda.bindings."):
            section = "HIP_PYTHON_INTEROP"
        else:
            continue
        if section is not None:
            sections[section].append(f"      - file: {autoapi_path}")
        # Each high-level entry has a paired cy* entry (in the cy subtree)
        # — that one IS a real generator-emitted page, so use the dotted
        # form to match the file the generator writes.
        if not leaf.startswith("cy"):
            cy_dotted = ".".join(module.rsplit(".", 1)[:-1] + [f"cy{leaf}"])
            sections["CYTHON_LEVEL"].append(
                f"      - file: python_api/{cy_dotted}"
            )

    # Reference only the llvm package index. sphinx-autoapi emits nested
    # toctrees inside the package index pages (rocm.bindings.llvm -> c /
    # config -> submodules), so the submodules already render as an
    # expandable `rocm.bindings.llvm.c` subtree. Listing them explicitly
    # here too made every llvm submodule appear twice. Mirrors how every
    # other subpackage (e.g. rocm.hipfile) is represented: parent only.
    if llvm_children:
        sections["ROCM_BINDINGS_COMPILER"] = (
            ["      - file: python_api/rocm/bindings/llvm/index"]
            + sections["ROCM_BINDINGS_COMPILER"]
        )

    with open(template_path) as f:
        rendered = f.read()
    for var, entries in sections.items():
        rendered = rendered.replace(
            f"@TOC_ENTRIES_{var}@", "\n".join(entries)
        )

    Path(os.path.dirname(output_path)).mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(_AUTOGEN_TOC_HEADER)
        f.write(rendered)
