#!/usr/bin/env python3
# MIT License
#
# Copyright (c) 2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Normalize a `mypy stubgen` `.pyi` before it lands in the source tree.

Run by the `<cython-target>_stub` CMake targets (see
`hip_python_add_stubgen_target` in `cmake/HipPythonBuild.cmake`) between
`stubgen` and the copy into the source tree. Three jobs:

1.  **Drop the Cython version from the stub.** stubgen renders a compiled
    Cython module's module-level `cpdef`/`def` objects as
    `_cython_<major>_<minor>_<patch>.cython_function_or_method`, naming
    Cython's private runtime module for the exact version that compiled
    the extension. Committing that makes the stub depend on whichever
    Cython the developer happened to have installed: the same `.pyx`
    produces a different `.pyi` on a machine one patch release behind,
    and every Cython bump churns every stub. `Callable[..., Any]` says
    the same thing to a type checker without the version coupling.

2.  **Mark the file as generated.** The interfacegen-produced stubs open
    with an `AUTO-GENERATED ... Edits will be overwritten` banner; the
    handcoded-module stubs did not, and several commits hand-edited them
    instead of re-running the target. The banner makes that visibly wrong
    in review.

3.  **Refuse a stub taken from a limited-API build.** An extension
    compiled against the CPython stable ABI (`HIP_PYTHON_ABI3_FLOOR`)
    tells stubgen much less about itself: Cython replaces the per-method
    docstrings with CPython's generic ones and names its runtime module
    `_cython_<major>_<minor>_<patch>limitednofinalize`, which job 1's
    pattern does not match. The result compiles the same and looks
    plausible, but it would strip the documentation sphinx-autoapi
    renders from these stubs, so it must never reach the source tree.

Usage:
    hip_python_postprocess_stub.py <module> <input.pyi> <output.pyi>
"""

from __future__ import annotations

import os
import re
import sys

#: `_cython_3_2_4.cython_function_or_method` and the matching
#: `import _cython_3_2_4`, for any Cython version.
_CYTHON_MODULE = re.compile(r"_cython_\d+_\d+_\d+")
_CYTHON_ATTR = re.compile(r"_cython_\d+_\d+_\d+\.(\w+)")

#: The same runtime module under a limited-API build, which suffixes the
#: version with the ABI flavour: `_cython_3_2_9limitednofinalize`. The
#: trailing `\w+` is what distinguishes it from the plain spelling above,
#: where a `.` or a line end follows the version.
_CYTHON_LIMITED_MODULE = re.compile(r"_cython_\d+_\d+_\d+\w+")

#: The only attribute stubgen reaches for on that module. Anything else
#: is unexpected and worth failing on rather than silently mistyping.
_ATTR_REPLACEMENTS = {"cython_function_or_method": "Callable[..., Any]"}

_TYPING_IMPORT = re.compile(r"^from typing import (.+)$")


def _banner(module: str) -> str:
    return (
        "# AUTO-GENERATED by `mypy stubgen` from the compiled extension module.\n"
        f"# Type stubs for {module}. Edits will be overwritten.\n"
        "# Regenerate with `ci/docs/regenerate-stubs.sh` after editing the .pyx.\n"
    )


def _replace_cython_attrs(text: str) -> tuple[str, bool]:
    """Rewrite `_cython_X_Y_Z.<attr>` references; report whether any matched."""
    unknown = {
        attr
        for attr in _CYTHON_ATTR.findall(text)
        if attr not in _ATTR_REPLACEMENTS
    }
    if unknown:
        raise SystemExit(
            f"unexpected Cython runtime attribute(s) {sorted(unknown)} in stub; "
            f"extend _ATTR_REPLACEMENTS in {__file__}"
        )
    new_text, count = _CYTHON_ATTR.subn(
        lambda m: _ATTR_REPLACEMENTS[m.group(1)], text
    )
    return new_text, count > 0


def _ensure_typing_names(lines: list[str], names: set[str]) -> list[str]:
    """Make sure `from typing import ...` covers `names`, adding it if absent."""
    for i, line in enumerate(lines):
        match = _TYPING_IMPORT.match(line)
        if match is None:
            continue
        existing = {n.strip() for n in match.group(1).split(",") if n.strip()}
        lines[i] = f"from typing import {', '.join(sorted(existing | names))}"
        return lines

    # No typing import to extend. Put one after the last import line so the
    # stub keeps stubgen's import-block-first layout.
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith(("import ", "from ")):
            insert_at = i + 1
    lines.insert(insert_at, f"from typing import {', '.join(sorted(names))}")
    return lines


def _reject_limited_api_stub(module: str, text: str) -> None:
    """Abort if `text` came from an extension built against the stable ABI."""
    match = _CYTHON_LIMITED_MODULE.search(text)
    if match is None:
        return
    raise SystemExit(
        f"the stub for {module} was generated from a limited-API build "
        f"(stubgen reached for '{match.group(0)}'). Such a stub loses the "
        "docstrings that sphinx-autoapi publishes and must not be committed. "
        "Re-configure the build tree without HIP_PYTHON_ABI3_FLOOR and run "
        "the stub target again."
    )


def postprocess(module: str, text: str) -> str:
    """Return `text` with Cython version references removed and a banner added."""
    _reject_limited_api_stub(module, text)
    text, substituted = _replace_cython_attrs(text)

    lines = text.splitlines()
    # The bare `import _cython_X_Y_Z` is dead once the annotations are gone.
    lines = [
        line
        for line in lines
        if not (
            line.startswith("import ") and _CYTHON_MODULE.fullmatch(line[7:])
        )
    ]
    if substituted:
        lines = _ensure_typing_names(lines, {"Any", "Callable"})

    body = "\n".join(lines)
    if body and not body.endswith("\n"):
        body += "\n"
    return _banner(module) + "\n" + body


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    module, src, dst = argv[1], argv[2], argv[3]
    if not os.path.exists(src):
        # stubgen skips a module it cannot import and still exits 0, so a
        # missing input here is how an unimportable module surfaces. Left
        # unchecked it would leave the previous `.pyi` in place and report
        # a successful regeneration.
        raise SystemExit(
            f"stubgen produced no stub for {module} (expected {src}). It most "
            "likely failed to import the module — check the stubgen output "
            "above for the underlying ImportError."
        )
    with open(src, encoding="utf-8") as handle:
        text = handle.read()
    with open(dst, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(postprocess(module, text))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
