# MIT License
#
# Copyright (c) 2023-2024 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

__author__ = "Advanced Micro Devices, Inc."

import re
import os
import keyword
import textwrap

from datetime import datetime

import logging

_log = logging.getLogger("interfacegen")

import clang.cindex

import Cython.Tempita

from . import tree

from . import cythontemplates
from . import cparser
from . import control
from . import doxyparser
from .support import cython as support

indent = " " * 2

# TODO
restricted_names = []

restricted_names = keyword.kwlist + [
    "cdef",
    "cpdef",  # TODO extend
]

c_interface_funptr_name_template = "_{name}__funptr"

python_interface_retval_template = "_{name}__retval"

python_interface_record_properties_name = "PROPERTIES"

python_interface_pyobj_role_template = r":py:obj:`.{name}`"


def C_TO_FORTRAN(canonical_ctype: str):
    """Map a canonical C type to the Fortran type.

    Returns:
        `str`: The Fortran type.

    Note:
        For implementation details, see
        https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fC_005fBINDING.html
    """
    tokens = [
        tk for tk in canonical_ctype.split(" ") if tk not in ("const", "unsigned")
    ]
    if tokens in [
        ["char", "*"],
        ["char", "[]"],
    ]:
        raise NotImplementedError(
            "string handling not implemented, distinction between buffer and null-terminated strings required"
        )
        return "bytes"
    elif tokens == ["char"]:
        return "character(kind=c_char)"
    elif tokens in (["short"], ["int"], ["long"], ["long", "long"]):
        return f"integer(kind=c_{'_'.join(tokens)})"
    elif tokens in [
        ["float"],
        ["double"],
        ["long", "double"],
    ]:
        return f"real(kind=c_{'_'.join(tokens)})"
    elif tokens in [
        ["bint"],
    ]:
        return "bool"
    elif len(tokens) == 2 and tokens[0] in ("union", "struct", "enum"):
        raise NotImplementedError("struct, union, enum types are not handled")
    else:
        raise NotImplementedError(f"unsure how to handle type '{canonical_ctype}'")


def DEFAULT_RENAMER(name):  # backend-specific
    result = name
    while result in restricted_names:
        result += "_"
    if "[]" in result:  # Fortran does not like this in certain signatures
        result = result.replace("[]", "*")
    return result


def DEFAULT_RAW_COMMENT_CLEANER(raw_comment: str):
    return raw_comment


def DEFAULT_DOXYGEN_CLEANER(doxygen: str):
    return doxygen


def DEFAULT_MACRO_TYPE(node):  # backend-specific
    return "integer(kind=c_int)"


# Utility types


def CREATE_DEFAULT_PTR_COMPLICATED_TYPE_HANDLER(util_types_prefix: str = ""):
    """Creates the default type handler routine."""
    return "type(c_ptr)"


LICENSE_TEXT = f"""\
{support.render_license_MIT(year_start=2021,comment_char="!")}
"""

default_module_prolog = f"""\
{LICENSE_TEXT}

! This file has been autogenerated, do not modify.
"""


class FortranMixin:
    def __init__(self):
        self.renamer = DEFAULT_RENAMER
        self.sep = "_"

    @property
    def fortran_name(self):
        return self.renamer(self.name)

    @property
    def fortran_global_name(self):
        return self.renamer(self.global_name)

    def _raw_comment_cleaned(self):
        from . import tree

        assert isinstance(self, tree.Node)
        if self.raw_comment != None:
            cleaned_raw_comment = self.raw_comment_cleaner(self.raw_comment)
            return doxyparser.remove_doxygen_comment_chars(cleaned_raw_comment)
        else:
            return ""

    def _remove_doxygen_comment_chars(self, text: str):
        return doxyparser.remove_doxygen_comment_chars(text)

    def _raw_comment_as_fortran_comment(self, comment_chars="!<"):
        from . import tree

        assert isinstance(self, tree.Node)
        if self.raw_comment != None:
            comment = self._raw_comment_cleaned()
            return "".join(
                [f"{comment_chars} " + l for l in comment.splitlines(keepends=True)]
            )
        else:
            return ""

    def render_c_interface(self):
        """Render a Fortran interface for external C code."""
        return None


class Root(tree.Root, FortranMixin):
    def __init__(self, *args, **kwargs):
        tree.Root.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)

class Typed:
    @property
    def fortran_global_typename(self):
        from . import tree

        assert isinstance(self, tree.Typed)
        result = self.global_typename(self.sep, self.renamer, prefer_canonical=True)
        # if "[]" in result: # Fortran does not like this in signatures
        #    result = result.replace("[]", "*")
        return result

    @property
    def actual_rank(self):
        """The actual rank of the parameter, if this is an indirection."""
        return self.ptr_rank(self)

    @property
    def has_array_rank(self):
        from . import tree

        assert isinstance(self, tree.Typed)
        if self.is_any_array:
            return True
        else:
            return self.actual_rank(self)

    @property
    def is_ptr(self):
        from . import tree

        assert isinstance(self, tree.Parm)
        return self.get_pointer_degree(incomplete_array=True) > 0

    @property
    def is_indirection(self):
        """If this is not the actual value but an indirection.

        Returns:
            bool: If this is not the actual value but an indirection.
        """
        from . import tree

        actual_rank = self.ptr_rank(self)
        assert isinstance(self, tree.Parm)
        return self.get_pointer_degree() > actual_rank

    @property
    def actual_rank(self):
        """The actual rank of the parameter, if this is an indirection."""
        return self.ptr_rank(self)

    @property
    def is_out_ptr(self):
        """If this parameter has been specified as out parameter."""
        assert self.is_ptr
        return self.ptr_intent(self) == control.ParmIntent.OUT

    @property
    def is_inout_ptr(self):
        """If this is an inout parameter."""
        assert self.is_ptr
        return self.ptr_intent(self) == control.ParmIntent.INOUT

    @property
    def is_in_ptr(self):
        """If this is an inout parameter."""
        assert self.is_ptr
        return self.ptr_intent(self) == control.ParmIntent.IN

    # TODO fortran fix this
    @property
    def is_autoconverted_by_cython(self):
        from . import tree

        assert isinstance(self, tree.Typed)

        return (
            self.is_basic_type
            or self.is_basic_type_constantarray(rank=1)
            or self.is_pointer_to_char(incomplete_array=True)
        )


class Enum(tree.Enum, FortranMixin):
    # Examples:
    # enum, bind(c)
    #    enumerator :: HIP_SUCCESS = 0
    #    enumerator :: HIP_ERROR_INVALID_VALUE
    #    enumerator :: HIP_ERROR_NOT_INITIALIZED
    #    enumerator :: HIP_ERROR_LAUNCH_OUT_OF_RESOURCES
    # end enum
    #
    # enum, bind(c)
    #    enumerator :: hipMemoryTypeHost
    #    enumerator :: hipMemoryTypeDevice
    #    enumerator :: hipMemoryTypeArray
    #    enumerator :: hipMemoryTypeUnified
    # end enum

    def __init__(self, *args, **kwargs):
        tree.Enum.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)

    def _render_fortran_enums(self):
        """Yields expressions of the form '"enumerator" "::" name [ "=" value]'."""
        for child_cursor in self.cursor.get_children():
            assert isinstance(child_cursor, clang.cindex.Cursor)
            name = self.fortran_name(child_cursor.spelling)
            value = child_cursor.enum_value
            if value:
                yield f"enumerator :: {name} = {value}"
            else:
                yield f"enumerator ::  {name}"

    def render_c_interface(self):
        # TODO fortran implement correctly
        global indent
        return (
            "enum, bind(c)"
            + textwrap.indent("\n".join(self._render_fortran_enums()), indent)
            + "end enum"
        )


class Parm(tree.Parm, FortranMixin, Typed):
    def __init__(self, *args, **kwargs):
        global CREATE_DEFAULT_PTR_COMPLICATED_TYPE_HANDLER
        tree.Parm.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)
        self.ptr_rank = control.DEFAULT_PTR_RANK
        self.ptr_intent = control.DEFAULT_PTR_PARM_INTENT
        self.ptr_complicated_type_handler = CREATE_DEFAULT_PTR_COMPLICATED_TYPE_HANDLER

    @property
    def fortran_decl(self):
        """Returns the Fortran interface declaration for the parameter."""
        name = self.fortran_name
        if self.is_any_pointer(degree=-1):
            return f"type(c_ptr),value :: {name}"
        else:
            return C_TO_FORTRAN(self.cursor.type.get_canonical().spelling)


class Function(tree.Function, FortranMixin, Typed):

    def __init__(self, *args, **kwargs):
        tree.Function.__init__(self, *args, **kwargs)
        FortranMixin.__init__(self)
        Typed.__init__(self)

    @property
    def _has_funptr_parm(self):
        from . import tree

        assert isinstance(self, tree.Function)
        for node in self.walk():
            if isinstance(node, tree.Parm):
                if isinstance(node.typeref, tree.FunctionPointer):
                    return True
        return False

    def _fortran_retval(self,fn_name):
        """Returns """

        typename = self.cython_global_typename
        if self.is_void:
            return None
        elif self.is_basic_type or self.is_pointer_to_char(degree=1):
            return f"{C_TO_FORTRAN(typename)} :: {fn_name}"
        elif self.is_enum or self.is_record:
            return f"integer(kind({typename})) :: {fn_name}"
        else:
            return None

    def render_c_interface(self, modifiers_front="", modifiers=""):
        """
        Renders the C interface.

        Example:

        ```f90
        !>  @brief Returns the approximate HIP driver version.
        !>
        !>  @param [out] driverVersion
        !>
        !>  @returns hipSuccess, hipErrorInavlidValue
        !>
        !>  @warning The HIP feature set does not correspond to an exact CUDA SDK driver revision.
        !>  This function always set *driverVersion to 4 as an approximation though HIP supports
        !>  some features which were introduced in later CUDA SDK revisions.
        !>  HIP apps code should not rely on the driver revision number here and should
        !>  use arch feature flags to test device capabilities or conditional compilation.
        !>
        !>  @see hipRuntimeGetVersion
        interface hipDriverGetVersion
        #ifdef USE_CUDA_NAMES
            function hipDriverGetVersion_(driverVersion) bind(c, name="cudaDriverGetVersion")
        #else
            function hipDriverGetVersion_(driverVersion) bind(c, name="hipDriverGetVersion")
        #endif
            use iso_c_binding
        #ifdef USE_CUDA_NAMES
            use hipfort_cuda_errors
        #endif
            use hipfort_enums
            use hipfort_types
            implicit none
        #ifdef USE_CUDA_NAMES
            integer(kind(cudaSuccess)) :: hipDriverGetVersion_
        #else
            integer(kind(hipSuccess)) :: hipDriverGetVersion_
        #endif
            type(c_ptr),value :: driverVersion
            end function
        end interface
        ```
        """
        hipfn = self.fortran_name
        binding = f"{hipfn}"
        parm_names = ",".join(parm.name for parm in self.parms])
        parm_decls = "\n".join([parm.fortran_repr for parm in self.parms])
        
        return textwrap.dedent(
            f"""\
            {{doxygen}}
            interface {hipfn}(parm_names)
                function {hipfn}_(driverVersion) bind(c, name="{binding}")
            {{parm_decls}}
                end function
            end interface
            """
        ).format(
            doxygen=self._raw_comment_as_fortran_comment().rstrip(),
            parm_names=parm_names,
            parm_decls=textwrap.indent(parm_decls,indent*2),
        )

class FortranBackend:
    def from_libclang_translation_unit(
        translation_unit: clang.cindex.TranslationUnit,
        filename: str,
        warn_mode: control.Warnings = control.Warnings.IGNORE,
        **opts,
    ):
        """See `FortranBackend.__init__` for further details."""
        from . import tree

        root = tree.from_libclang_translation_unit(translation_unit, warn_mode)
        return FortranBackend(
            root,
            filename,
            **opts,
        )

    def __init__(
        self,
        root,
        filename: str,
        util_pkg: str = "",
        node_filter: callable = control.DEFAULT_NODE_FILTER,
        macro_type: callable = DEFAULT_MACRO_TYPE,
        ptr_parm_intent: callable = control.DEFAULT_PTR_PARM_INTENT,
        ptr_rank: callable = control.DEFAULT_PTR_RANK,
        ptr_complicated_type_handler=None,
        renamer: callable = DEFAULT_RENAMER,
        raw_comment_cleaner: callable = DEFAULT_RAW_COMMENT_CLEANER,
        doxygen_cleaner: callable = DEFAULT_DOXYGEN_CLEANER,
        node_init: callable = lambda node: None,
    ):
        """Constructor.

        Args:
            node_filter (callable, optional):
                Filter for selecting the nodes to include in generated output. Defaults to ``lambda x: True``.
                Note that other callbacks are applied to non-filtered nodes also.
            node_init (callable, optional):
                Callback that can be used to modify certain nodes arbitrarily.
                Note that this callback is applied after all other callbacks (excluding ``node_filter``).
                Defaults to no-operation.
            macro_type (callable, optional):
                Assigns a type to a macro node. Defaults to ``lambda x: "int"``.
            ptr_parm_intent (callable, optional):
                Assigns the intent (in,out,inout,create) to a pointer-type function parameter/struct field node..
            ptr_rank (callable, optional):
                Assigns the "rank" (scalar,buffer) to a function parameter node.
            ptr_complicated_type_handler (callable, optional):
                A handler that infers a type for complicated pointer types.
                Selects `CREATE_DEFAULT_PTR_COMPLICATED_TYPE_HANDLER(f"{util_pkg}.types.")`
                if the default value `None` is not overwritten with a user callback.
        Note:
            Argument 'root' has no type hint in order to prevent a circular inclusion error.
            Instead an assertion is used in the body that checks if the type is `tree.Root`.
        """
        from . import tree

        assert isinstance(root, tree.Root)
        self.root = root
        self.filename = filename
        self.util_pkg = util_pkg
        self.node_filter = node_filter
        self.macro_type = macro_type
        self.ptr_parm_intent = ptr_parm_intent
        self.ptr_rank = ptr_rank
        if ptr_complicated_type_handler == None:
            self.ptr_complicated_type_handler = (
                CREATE_DEFAULT_PTR_COMPLICATED_TYPE_HANDLER(f"{util_pkg}.types.")
            )
        else:
            self.ptr_complicated_type_handler = ptr_complicated_type_handler
        self.renamer = renamer
        self.raw_comment_cleaner = raw_comment_cleaner
        self.doxygen_cleaner = doxygen_cleaner
        self.node_init = node_init

        self.initialize_nodes()

    def initialize_nodes(self):
        """Initializes all nodes.

        Note:
            Post-order walk, touches nested struct/union/enum declarations before their
            parent.
        """
        for node in self.root.walk(postorder=True):
            if isinstance(node, FortranMixin):
                # set defaults
                setattr(node, "sep", "_")
                # set user callbacks
                setattr(node, "renamer", self.renamer)
                setattr(node, "raw_comment_cleaner", self.raw_comment_cleaner)
                setattr(node, "docstring_cleaner", self.doxygen_cleaner)
                # if isinstance(node, MacroDefinitionMixin):
                #     setattr(node, "macro_type", self.macro_type)
                if isinstance(node, Parm):
                    setattr(node, "ptr_rank", self.ptr_rank)
                    setattr(node, "ptr_intent", self.ptr_parm_intent)
                    setattr(
                        node,
                        "ptr_complicated_type_handler",
                        self.ptr_complicated_type_handler,
                    )
                elif isinstance(node, Function):
                    setattr(node, "ptr_rank", self.ptr_rank)
                    setattr(
                        node,
                        "ptr_complicated_type_handler",
                        self.ptr_complicated_type_handler,
                    )
                self.node_init(node)

    def walk_filtered_nodes(self):
        """Walks the filtered nodes in post-order and sets the renamer of each node.

        Note:
            Post-order walk, touches nested struct/union/enum declarations before their
            parent.
        """
        for node in self.root.walk(postorder=True):
            if isinstance(node, FortranMixin):
                if not isinstance(node, (Parm, Root)):
                    if self.node_filter(node):
                        _log.debug(
                            f" touch {node.__class__.__name__} {node.name} from {node.cursor.kind} {node.cursor.spelling} ({node.render_location()})"
                        )
                        yield node

    def create_c_interface(self):
        """Returns the content of a Fortran bindings file.

        Creates the content of a Fortran bindings file.
        Contains Fortran declarations per C declaration
        plus helper types that have been introduced for nested enum/struct/union types.

        Note:
            Anonymous types for which we have a tree node with
            autogenerated name must be excluded from the `extern from "<header_name.h>`
            block as entities listed within the body of the construct,
            are assumed by Fortran to be present in C code whenever
            the respective header is included.

            Moving those entities out of the `extern from` block
            ensures that Fortran creates a proper C type on its own.
        """
        from . import tree

        global indent
        curr_indent = ""
        result = []

        for node in self.walk_filtered_nodes():
            if isinstance(node, (Enum, Function)):
                contrib = node.render_c_interface()
                if contrib != None:
                    result.append(textwrap.indent(contrib, curr_indent))
        return result

    def render_c_interface_decl_part(self, runtime_linking: bool = False):
        """Returns the Fortran bindings file content for the given headers."""
        nl = "\n\n"
        return nl.join(self.create_c_interface(runtime_linking))


class FortranModuleGenerator:
    """Generate Fortran modules for a C library.

    Generates a Fortran module from a C header file.
    """

    def __init__(
        self,
        module_name: str,
        module_ext: str,
        include_dir: str,
        header: str,
        cflags=[],
        **opts,
    ):
        r"""Constructor.

        Args:
            module_name (str):
                The Fortran module name without the Fortran file extension, e.g.,
                "mymodule" instead of "mymodule.f".
            module_ext (str):
                Module file extension to use, e.g., ".f" or ".f90".
                Defaults to ".f90".
            include_dir (str):
                Name of the main include dir.
            header (str|tuple):
                Name of the header file. Absolute paths or w.r.t. to include dir.
            cflags (list(str), optional):
                Flags to pass to the C parser.
            \*\*opts:
                Further optional keyword arguments.
                See `FortranBackend` for further details.
        """
        global default_module_prolog
        self.module_name = module_name
        self.enum_module_name = module_name+"_enums"
        self.module_ext = module_ext

        self.include_dir = include_dir
        self.header = header
        self.cflags = cflags
        self.c_interface_prolog = default_module_prolog

        if isinstance(header, str):
            filename = header
            unsaved_files = None
        elif isinstance(header, tuple):
            filename = header[0]
            unsaved_files = [header]
        else:
            raise ValueError("type of 'headers' must be str or tuple")
        _log.info(" " + filename)
        if include_dir != None:
            abspath = os.path.join(include_dir, filename)
        else:
            abspath = filename
        cflags = self.cflags + ["-I", f"{include_dir}"]
        parser = cparser.CParser(
            abspath, append_cflags=cflags, unsaved_files=unsaved_files
        )
        parser.parse()

        self.backend = FortranBackend.from_libclang_translation_unit(
            parser.translation_unit, header, **opts
        )

    def write_module_files(self, output_dir: str = None):
        """Write all files required to build this Fortran module.

        Args:
            module_name (str): Name of the module that should be generated. Influences filesnames.
        """

        # enums, types
        with open(f"{output_dir}/{self.module_name}_enums.{self.module_ext}", "w") as outfile:
            outfile.write(self.c_interface_prolog)
            outfile.write(
                self.backend.render_c_interface_decl_part(
                    runtime_linking=self.runtime_linking
                )
            )
            outfile.write(self.c_interface_decl_epilog)

        # functions, other
        with open(f"{output_dir}/{self.module_name}_enums.{self.module_ext}", "w") as outfile:
            outfile.write(self.c_interface_prolog)
            outfile.write(
                self.backend.render_c_interface_decl_part(
                    runtime_linking=self.runtime_linking
                )
            )
            outfile.write(self.c_interface_decl_epilog)
