# MIT License
#
# Copyright (c) 2021-2026 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This file has been autogenerated, do not modify.

from libc cimport stdlib
from libc cimport string
from libc.stdint cimport *
cimport cpython.long
cimport cpython.buffer
ctypedef bint _Bool # bool is not a reserved keyword in C, _Bool is
from rocm.bindings.hip cimport ihipStream_t

cimport rocm.bindings.util.types
cimport rocm.bindings.cyrccl as cyrccl

cdef class ncclComm(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclComm* getElementPtr(self)

    @staticmethod
    cdef ncclComm fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclComm fromPyobj(object pyobj)


cdef class ncclWindow_vidmem(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclWindow_vidmem* getElementPtr(self)

    @staticmethod
    cdef ncclWindow_vidmem fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclWindow_vidmem fromPyobj(object pyobj)


cdef class ncclUniqueId(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclUniqueId* getElementPtr(self)

    @staticmethod
    cdef ncclUniqueId fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclUniqueId fromPyobj(object pyobj)
    @staticmethod
    cdef __allocate(void* ptr)
    @staticmethod
    cdef ncclUniqueId new()
    @staticmethod
    cdef ncclUniqueId fromValue(cyrccl.ncclUniqueId other)


cdef class ncclConfig_v22800(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclConfig_v22800* getElementPtr(self)

    @staticmethod
    cdef ncclConfig_v22800 fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclConfig_v22800 fromPyobj(object pyobj)
    @staticmethod
    cdef __allocate(void* ptr)
    @staticmethod
    cdef ncclConfig_v22800 new()
    @staticmethod
    cdef ncclConfig_v22800 fromValue(cyrccl.ncclConfig_v22800 other)


cdef class ncclSimInfo_v22200(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclSimInfo_v22200* getElementPtr(self)

    @staticmethod
    cdef ncclSimInfo_v22200 fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclSimInfo_v22200 fromPyobj(object pyobj)
    @staticmethod
    cdef __allocate(void* ptr)
    @staticmethod
    cdef ncclSimInfo_v22200 new()
    @staticmethod
    cdef ncclSimInfo_v22200 fromValue(cyrccl.ncclSimInfo_v22200 other)


cdef class ncclWaitSignalDesc_t(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclWaitSignalDesc_t* getElementPtr(self)

    @staticmethod
    cdef ncclWaitSignalDesc_t fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclWaitSignalDesc_t fromPyobj(object pyobj)
    @staticmethod
    cdef __allocate(void* ptr)
    @staticmethod
    cdef ncclWaitSignalDesc_t new()
    @staticmethod
    cdef ncclWaitSignalDesc_t fromValue(cyrccl.ncclWaitSignalDesc_t other)


cdef class ncclParamHandle(rocm.bindings.util.types.Pointer):
    cdef bint _is_ptr_owner

    cdef cyrccl.ncclParamHandle* getElementPtr(self)

    @staticmethod
    cdef ncclParamHandle fromPtr(void* ptr, bint owner=*)
    @staticmethod
    cdef ncclParamHandle fromPyobj(object pyobj)
