# AUTO-GENERATED by the hip-python code generator.
# Type stubs for rocm.bindings.roctx. Edits will be overwritten.

import enum
import rocm.bindings.util.types
from typing import Any

def has_symbol(name: str | bytes | bytearray) -> bool: ...

ROCTX_VERSION_MAJOR: Any

ROCTX_VERSION_MINOR: Any

def roctx_version_major():
    r"""Query the major version of the installed library.

    Return the major version of the installed library. This can be used to check
    if it is compatible with this interface version.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.int`: Returns the major version number.

    .. rubric:: C signature

    .. code-block:: c

        uint32_t roctx_version_major()
    """
    ...

def roctx_version_minor():
    r"""Query the minor version of the installed library.

    Return the minor version of the installed library. This can be used to check
    if it is compatible with this interface version.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.int`: Returns the minor version number.

    .. rubric:: C signature

    .. code-block:: c

        uint32_t roctx_version_minor()
    """
    ...

def roctxMarkA(message):
    r"""Mark an event.

    Args:
        message (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`) -- *IN*:
            The message associated with the event.

    .. rubric:: C signature

    .. code-block:: c

        void roctxMarkA(const char * message)
    """
    ...

def roctxRangePushA(message):
    r"""Start a new nested range.

    Nested ranges are stacked and local to the current CPU thread.

    Args:
        message (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`) -- *IN*:
            The message associated with this range.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.int`: Returns the level this nested range is started at. Nested range
            levels are 0 based.

    .. rubric:: C signature

    .. code-block:: c

        int roctxRangePushA(const char * message)
    """
    ...

def roctxRangePop():
    r"""Stop the current nested range.

    Stop the current nested range, and pop it from the stack. If a nested range
    was active before the last one was started, it becomes again the current
    nested range.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.int`: Returns the level the stopped nested range was started at, or a
            negative value if there was no nested range active.

    .. rubric:: C signature

    .. code-block:: c

        int roctxRangePop()
    """
    ...

def roctxRangeStartA(message):
    r"""Starts a process range.

    Start/stop ranges can be started and stopped in different threads. Each
    timespan is assigned a unique range ID.

    Args:
        message (:py:obj:`~.rocm.bindings.util.types.CStr`/:py:obj:`~.object`) -- *IN*:
            The message associated with this range.

    Returns:
        A :py:obj:`~.tuple` of size 1 that contains (in that order):

        * :py:obj:`~.int`: Returns the ID of the new range.

    .. rubric:: C signature

    .. code-block:: c

        roctx_range_id_t roctxRangeStartA(const char * message)
    """
    ...

def roctxRangeStop(id):
    r"""Stop a process range.

    Args:
        id (:py:obj:`~.int`):
            (undocumented)

    .. rubric:: C signature

    .. code-block:: c

        void roctxRangeStop(roctx_range_id_t id)
    """
    ...

__all__ = [
    'ROCTX_VERSION_MAJOR',
    'ROCTX_VERSION_MINOR',
    'has_symbol',
    'roctxMarkA',
    'roctxRangePop',
    'roctxRangePushA',
    'roctxRangeStartA',
    'roctxRangeStop',
    'roctx_version_major',
    'roctx_version_minor',
]
